import React, { useMemo, useState } from "react";
import { Camera, Target, TrendingUp } from "lucide-react";
import type { Deal } from "@/modules/deals";
import { resolveWorkspaceMemberLabel } from "@/platform/member-directory";
import { Button } from "@/shared/components/ui";
import { buildAdvancedForecastSnapshot, buildForecastTrend, loadForecastSnapshots, reconcileForecastAccuracy, saveForecastSnapshot } from "./advancedForecast";

export const AdvancedForecastPanel: React.FC<{ workspaceId: string; locale: "vi" | "en"; deals: Deal[]; periodStart: string; periodEnd: string; formatMoney: (value: number) => string }> = ({ workspaceId, locale, deals, periodStart, periodEnd, formatMoney }) => {
  const vi = locale === "vi";
  const [revision, setRevision] = useState(0);
  const current = useMemo(() => reconcileForecastAccuracy(buildAdvancedForecastSnapshot({ workspaceId, deals, periodStart, periodEnd }), deals), [workspaceId, deals, periodStart, periodEnd, revision]);
  const snapshots = useMemo(() => loadForecastSnapshots(workspaceId).map((item) => reconcileForecastAccuracy(item, deals)), [workspaceId, deals, revision]);
  const trend = useMemo(() => buildForecastTrend(snapshots), [snapshots]);
  const capture = () => { saveForecastSnapshot(current); setRevision((value) => value + 1); };
  return <section data-guidance-id="reports.advanced-forecast" className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <header className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-black text-slate-950"><TrendingUp size={16} className="text-violet-600"/>{vi ? "Forecast nâng cao" : "Advanced forecast"}</div><p className="mt-1 text-[11px] text-slate-500">{vi ? "Commit, Best Case, Pipeline, weighted forecast, snapshot lịch sử và độ chính xác." : "Commit, Best Case, Pipeline, weighted forecast, historical snapshots, and accuracy."}</p></div><Button type="button" actionIntent="create" size="sm" icon={<Camera size={13}/>} onClick={capture}>{vi ? "Chụp snapshot" : "Capture snapshot"}</Button></header>
    <div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4">{current.categories.map((item) => <div key={item.category} className="rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">{item.category === "BEST_CASE" ? "BEST CASE" : item.category}</div><div className="mt-2 text-lg font-black text-slate-950">{formatMoney(item.amount)}</div><div className="mt-1 text-[10px] text-slate-500">{item.dealCount} {vi ? "cơ hội" : "deals"} · {vi ? "Có trọng số" : "Weighted"} {formatMoney(item.weightedAmount)}</div></div>)}<div className="rounded-2xl bg-violet-50 p-4"><div className="flex items-center gap-1 text-[10px] font-black uppercase tracking-wider text-violet-600"><Target size={12}/>{vi ? "Độ chính xác Commit" : "Commit accuracy"}</div><div className="mt-2 text-lg font-black text-violet-900">{current.accuracyPercent ?? 0}%</div><div className="mt-1 text-[10px] text-violet-700">{vi ? "Thực tế thắng" : "Actual won"} {formatMoney(current.actualWonAmount ?? 0)}</div></div></div>
    <div className="grid gap-4 border-t border-slate-100 p-5 lg:grid-cols-2"><div><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">{vi ? "Theo người phụ trách" : "By owner"}</div><div className="mt-2 space-y-2">{current.owners.slice(0, 5).map((owner) => <div key={owner.ownerId} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 px-3 py-2"><span className="crm-text-wrap text-[11px] font-bold text-slate-700">{resolveWorkspaceMemberLabel(owner.ownerId, locale)}</span><span className="shrink-0 text-[11px] font-black text-slate-950">{formatMoney(owner.weightedAmount)}</span></div>)}{current.owners.length === 0 && <div className="text-[11px] text-slate-400">{vi ? "Không có cơ hội trong kỳ." : "No deals in the period."}</div>}</div></div><div><div className="text-[10px] font-black uppercase tracking-wider text-slate-400">{vi ? "Lịch sử snapshot" : "Snapshot history"}</div><div className="mt-2 space-y-2">{trend.slice(-5).reverse().map((item) => <div key={item.capturedAt} className="rounded-xl border border-slate-200 px-3 py-2"><div className="flex justify-between gap-2 text-[10px]"><span className="font-semibold text-slate-500">{new Date(item.capturedAt).toLocaleString(vi ? "vi-VN" : "en-US")}</span><span className="font-black text-violet-700">{item.accuracy ?? 0}%</span></div><div className="mt-1 text-[10px] text-slate-600">{vi ? "Cam kết" : "Commit"} {formatMoney(item.commit)} · {vi ? "Tốt nhất" : "Best Case"} {formatMoney(item.bestCase)} · {vi ? "Có trọng số" : "Weighted"} {formatMoney(item.weighted)}</div></div>)}{trend.length === 0 && <div className="text-[11px] text-slate-400">{vi ? "Chưa có snapshot lịch sử." : "No historical snapshots yet."}</div>}</div></div></div>
  </section>;
};
