import type { Contact } from "../domain/model/contact.types";

export const CONTACT_SEED: Contact[] = [
  {
    id: "con1",
    contactCode: "CN0001",
    name: "Nguyễn Văn An",
    fullName: "Nguyễn Văn An",
    title: "Giám đốc IT",
    organizationAccountId: "org_c1",
    companyName: "Công ty TNHH TechVision",
    organizationName: "Công ty TNHH TechVision",
    email: "an.nguyen@techvision.com.vn",
    workEmail: "an.nguyen@techvision.com.vn",
    phone: "+84 905 123 456",
    mobilePhone: "+84 905 123 456",
    zaloId: "zalo.me/0905123456",
    zalo: "zalo.me/0905123456",
    address: "Keangnam, Mễ Trì, Nam Từ Liêm, Hà Nội",
    department: "Công nghệ thông tin",
    ownerId: "u5",
    status: "needs_follow_up", // New ContactStatus
    priority: "HIGH",
    source: "Hội thảo / Webinar",
    tags: ["Decision Maker", "Cloud IT", "ERP-Interest"],
    lastContactedAt: "2026-06-01T10:00:00Z",
    lastInteractionAt: "2026-06-01T10:00:00Z",
    nextFollowUpAt: "2026-06-25T09:00:00Z", // Future date
    followUpNote: "Gọi lại tư vấn sâu thêm về giải pháp ERP Cloud tích hợp hóa đơn điện tử.",
    decisionRole: "decision_maker",
    relationshipLevel: "good",
    isPrimaryContact: true,
    createdFrom: "lead_conversion",
    convertedFromLeadId: "lead_001",
    createdAt: "2026-01-10T08:30:00Z",
    notes: "Được chuyển đổi từ Lead sau khi thẩm định nhu cầu ERP rất rõ ràng. Cần chăm sóc đặc biệt để chuẩn bị tạo Cơ hội bán hàng mới."
  },
  {
    id: "con2",
    contactCode: "CN0002",
    name: "Trần Thị Bình",
    fullName: "Trần Thị Bình",
    title: "Trưởng phòng Mua sắm",
    organizationAccountId: "org_c1",
    companyName: "Công ty TNHH TechVision",
    organizationName: "Công ty TNHH TechVision",
    email: "b.tran@techvision.com.vn",
    workEmail: "b.tran@techvision.com.vn",
    phone: "+84 903 456 789",
    mobilePhone: "+84 903 456 789",
    zaloId: "zalo.me/0903456789",
    zalo: "zalo.me/0903456789",
    address: "Keangnam, Mễ Trì, Nam Từ Liêm, Hà Nội",
    department: "Hành chính & Mua sắm",
    ownerId: "u5",
    status: "in_consulting",
    priority: "LOW",
    source: "Hội thảo / Webinar",
    tags: ["Evaluator", "Contracts"],
    lastContactedAt: "2026-06-05T14:30:00Z",
    lastInteractionAt: "2026-06-05T14:30:00Z",
    nextFollowUpAt: "2026-06-20T10:00:00Z",
    followUpNote: "Cung cấp báo giá chi tiết cho các gói dịch vụ bổ sung cấu phần HRM.",
    decisionRole: "influencer",
    relationshipLevel: "warm",
    isPrimaryContact: false,
    createdFrom: "manual",
    createdAt: "2026-01-12T14:20:00Z",
    notes: "Yêu cầu cung cấp thông tin so sánh các tính năng và điều khoản thanh toán."
  },
  {
    id: "con3",
    contactCode: "CN0003",
    name: "Lê Văn Cường",
    fullName: "Lê Văn Cường",
    title: "Trưởng nhóm vận hành CRM",
    organizationAccountId: "org_c2",
    companyName: "Công ty TNHH TechHub",
    organizationName: "Công ty TNHH TechHub",
    email: "c.le@techhub.vn",
    workEmail: "c.le@techhub.vn",
    phone: "0904 123 456",
    mobilePhone: "0904 123 456",
    address: "Tòa nhà sông Đà, Phạm Hùng, Mỹ Đình, Hà Nội",
    department: "Kỹ thuật vận hành",
    ownerId: "u3",
    status: "has_open_opportunity",
    priority: "MEDIUM",
    source: "Tư vấn trực tiếp",
    tags: ["Tech Lead", "CRM-Upgrade"],
    lastContactedAt: "2026-05-20T09:00:00Z",
    lastInteractionAt: "2026-05-20T09:00:00Z",
    nextFollowUpAt: "2026-06-18T14:00:00Z",
    decisionRole: "technical",
    relationshipLevel: "strong",
    isPrimaryContact: true,
    createdFrom: "lead_conversion",
    convertedFromLeadId: "lead_002",
    relatedOpportunityIds: ["deal_003"],
    openOpportunityCount: 1,
    createdAt: "2026-03-15T09:00:00Z",
    notes: "Đại diện chính về mặt kỹ thuật cho dự án nâng cấp hệ thống CRM cho 200 nhân viên hỗ trợ khách hàng."
  },
  {
    id: "con4",
    contactCode: "CN0004",
    name: "Trần Thế Minh",
    fullName: "Trần Thế Minh",
    title: "Nhà đầu tư cá nhân",
    email: "tranminh.investor@gmail.com",
    personalEmail: "tranminh.investor@gmail.com",
    phone: "0912 345 678",
    mobilePhone: "0912 345 678",
    address: "15 Lê Thánh Tôn, Bến Nghé, Quận 1, TP.HCM",
    ownerId: "u2",
    status: "active",
    priority: "MEDIUM",
    source: "Facebook",
    tags: ["Individual Investor", "Cold Lead Converted"],
    decisionRole: "other",
    relationshipLevel: "cold",
    createdFrom: "lead_conversion",
    convertedFromLeadId: "lead_fb_01",
    createdAt: "2026-06-10T11:30:00Z",
    notes: "Liên hệ unlinked từ Facebook Messenger, chưa liên kết với bất kỳ Customer (tài khoản doanh nghiệp) nào. Đang tìm hiểu gói đầu tư cá nhân."
  },
  {
    id: "con5",
    contactCode: "CN0005",
    name: "Lê Hải Phương",
    fullName: "Lê Hải Phương",
    title: "Giám đốc tài chính (CFO)",
    organizationAccountId: "org_c5",
    companyName: "Công ty Cổ phần Đầu tư Hoàng Gia",
    organizationName: "Công ty Cổ phần Đầu tư Hoàng Gia",
    email: "lephuong@royalinvest.com.vn",
    workEmail: "lephuong@royalinvest.com.vn",
    phone: "0987 654 321",
    mobilePhone: "0987 654 321",
    address: "12 Láng Hạ, Đống Đa, Hà Nội",
    department: "Tài chính - Kế toán",
    ownerId: "u1",
    status: "needs_follow_up",
    priority: "HIGH",
    source: "Google Search",
    tags: ["High Budget", "Ready to Buy"],
    lastContactedAt: "2026-06-11T16:00:00Z",
    lastInteractionAt: "2026-06-11T16:00:00Z",
    nextFollowUpAt: "2026-06-14T09:00:00Z", // Past date (overdue)
    followUpNote: "Gửi báo cáo thẩm định đầu tư CRM tối ưu chi phí hạ tầng.",
    decisionRole: "finance",
    relationshipLevel: "good",
    isPrimaryContact: true,
    createdFrom: "manual",
    createdAt: "2026-05-10T11:00:00Z",
    notes: "Mẫu người làm việc khoa học, chú trọng tỷ lệ hoàn vốn ROI. Cần chăm sóc hẹn gặp trực tiếp trước ngày 20."
  },
  {
    id: "con6",
    contactCode: "CN0006",
    name: "Hoàng Hoài Nam",
    fullName: "Hoàng Hoài Nam",
    title: "Phó giám đốc kỹ thuật",
    email: "hoangnam@freelancer.vn",
    personalEmail: "hoangnam@freelancer.vn",
    phone: "0909 999 888",
    mobilePhone: "0909 999 888",
    address: "Hải Châu, Đà Nẵng, Việt Nam",
    ownerId: "u4",
    status: "do_not_contact",
    priority: "URGENT",
    source: "Giới thiệu / Referral",
    tags: ["Consultant", "Nurturing"],
    lastContactedAt: "2026-06-08T15:00:00Z",
    lastInteractionAt: "2026-06-08T15:00:00Z",
    doNotContact: true,
    doNotContactReason: "Khách hàng yêu cầu ngừng liên hệ mời chào dịch vụ do thay đổi nơi làm việc.",
    decisionRole: "technical",
    relationshipLevel: "cold",
    createdFrom: "campaign",
    createdAt: "2026-04-01T10:00:00Z",
    notes: "Đã chuyển sang công ty khác không hoạt động trong mảng này, không có nhu cầu tiếp tục tư vấn."
  },
  {
    id: "con7",
    contactCode: "CN0007",
    name: "Phạm Minh Tuấn",
    fullName: "Phạm Minh Tuấn",
    title: "Trưởng phòng Kế hoạch",
    organizationAccountId: "org_c4",
    companyName: "Tập đoàn Vận tải Viễn Đông",
    organizationName: "Tập đoàn Vận tải Viễn Đông",
    email: "tuan.pm@viendongtrans.vn",
    workEmail: "tuan.pm@viendongtrans.vn",
    phone: "0388 777 666",
    mobilePhone: "0388 777 666",
    address: "Bình Thạnh, TP.HCM",
    department: "Phòng Kế hoạch & Đầu tư",
    ownerId: "u1",
    status: "active",
    priority: "MEDIUM",
    source: "Google Ads",
    tags: ["Corporate Customer", "Deal Won Ref"],
    lastContactedAt: "2026-06-12T10:00:00Z",
    lastInteractionAt: "2026-06-12T10:00:00Z",
    decisionRole: "buyer",
    relationshipLevel: "vip",
    isPrimaryContact: true,
    createdFrom: "lead_conversion",
    convertedFromLeadId: "lead_009",
    wonOpportunityId: "deal_won_009",
    createdAt: "2026-05-01T09:00:00Z",
    notes: "Đã chốt hợp đồng lớn thành công ngày 12/06. Hiện đã chuyển đổi để ghi nhận khách hàng mua hàng thực tế."
  },
  {
    id: "contact_customer_c3",
    contactCode: "KH0000003",
    name: "Nguyễn Minh Tuấn",
    fullName: "Nguyễn Minh Tuấn",
    email: "tuan.nguyen@gmail.com",
    personalEmail: "tuan.nguyen@gmail.com",
    phone: "0912345678",
    mobilePhone: "0912345678",
    address: "72 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    ownerId: "u3",
    status: "active",
    priority: "MEDIUM",
    source: "Facebook Ads",
    tags: ["Retail", "B2C Loyalty"],
    relationshipLevel: "good",
    createdFrom: "customer",
    createdAt: "2026-05-18T00:00:00Z",
    notes: "Imported from legacy individual Customer KH0000003.",
  },
];
