import type { CustomerMigrationProfile } from "../application/ports/CustomerRuntimePort";


/**
 * Committed relationship/profile backfill. Profile customerState and counters
 * are not runtime owners: Purchase Evidence drives state, count, and latest
 * purchase, while these values remain legacy presentation backfill for fields
 * whose canonical source owner is not yet available.
 */
export const CUSTOMER_VIEW_MIGRATION_PROFILES: CustomerMigrationProfile[] = [
  {
    relationshipRef: { type: "ORGANIZATION_ACCOUNT", id: "org_c1" },
    legacyCustomerId: "c1",
    legacyCustomerCode: "KH0000001",
    customerState: "ACTIVE",
    historicalPurchaseCount: 2,
    latestPurchaseAt: "2025-12-12",
    segment: "Enterprise",
    source: "Hội thảo / Webinar",
    totalRevenue: 336000000,
    outstandingDebt: 0,
    purchaseCycleDays: 90,
    monthlyRecurringRevenue: 28000000,
    renewalAt: "2026-12-12",
    health: "GOOD",
    ownedProducts: [
      {
        id: "po1",
        productId: "prod_3",
        productName: "Enterprise ERP Suite 2024",
        quantity: 1,
        purchasedAt: "2025-12-12",
        amount: 28000000,
        status: "ACTIVE",
        expiresAt: "2026-12-12",
      },
      {
        id: "po2",
        productId: "prod_4",
        productName: "Dịch vụ Triển khai Onboarding & Đào Tạo",
        quantity: 1,
        purchasedAt: "2025-12-12",
        amount: 0,
        status: "ACTIVE",
        expiresAt: "2026-07-01",
      },
    ],
  },
  {
    relationshipRef: { type: "ORGANIZATION_ACCOUNT", id: "org_c2" },
    legacyCustomerId: "c2",
    legacyCustomerCode: "KH0000002",
    customerState: "ACTIVE",
    historicalPurchaseCount: 4,
    latestPurchaseAt: "2026-02-15",
    segment: "Enterprise",
    source: "Tư vấn trực tiếp",
    totalRevenue: 540000000,
    outstandingDebt: 45000000,
    purchaseCycleDays: 180,
    monthlyRecurringRevenue: 45000000,
    renewalAt: "2026-11-20",
    health: "RISK",
    ownedProducts: [
      {
        id: "po3",
        productId: "prod_2",
        productName: "Unicore CRM Cloud Suite",
        quantity: 1,
        purchasedAt: "2026-02-15",
        amount: 45000000,
        status: "ACTIVE",
        expiresAt: "2026-11-20",
      },
    ],
  },
  {
    relationshipRef: { type: "CONTACT", id: "contact_customer_c3" },
    legacyCustomerId: "c3",
    legacyCustomerCode: "KH0000003",
    customerState: "ACTIVE",
    historicalPurchaseCount: 5,
    latestPurchaseAt: "2026-05-18",
    segment: "Standard",
    source: "Facebook Ads",
    totalRevenue: 15400000,
    outstandingDebt: 0,
    purchaseCycleDays: 30,
    monthlyRecurringRevenue: 0,
    health: "WATCH",
    ownedProducts: [],
  },
  {
    relationshipRef: { type: "ORGANIZATION_ACCOUNT", id: "org_c4" },
    legacyCustomerId: "c4",
    legacyCustomerCode: "KH0000004",
    customerState: "ACTIVE",
    historicalPurchaseCount: 1,
    latestPurchaseAt: "2026-06-12",
    segment: "Enterprise",
    source: "Google Ads",
    totalRevenue: 500000000,
    outstandingDebt: 0,
    monthlyRecurringRevenue: 0,
    health: "GOOD",
    ownedProducts: [],
  },
  {
    relationshipRef: { type: "ORGANIZATION_ACCOUNT", id: "org_c5" },
    legacyCustomerId: "c5",
    legacyCustomerCode: "KH0000005",
    customerState: "ACTIVE",
    historicalPurchaseCount: 1,
    latestPurchaseAt: "2026-06-11",
    segment: "Key Account",
    source: "Google Search",
    totalRevenue: 450000000,
    outstandingDebt: 0,
    monthlyRecurringRevenue: 0,
    health: "GOOD",
    ownedProducts: [],
  },
];
