import { CAPABILITIES } from "@/platform/access-control/domain/capabilityCatalog";
import type { WorkflowGuidance } from "@/guidance/domain/guidance.types";

const reviewedAt = "2026-07-12";
const owner = "Product Enablement";

export const WORKFLOW_GUIDANCE: WorkflowGuidance[] = [
  {
    id: "workflow.lead-to-order",
    title: { vi: "Từ khách hàng tiềm năng đến đơn hàng", en: "Lead to order" },
    summary: { vi: "Biến một nhu cầu đã xác minh thành cơ hội, báo giá và cam kết mua mà không tạo bước ẩn.", en: "Turn a verified need into an opportunity, quote, and purchase commitment without hidden steps." },
    productSpaces: ["crm"],
    version: 2,
    steps: [
      { id: "lead", title: { vi: "Tiếp nhận và xác minh khách hàng tiềm năng", en: "Capture and verify the lead" }, body: { vi: "Bổ sung thông tin liên hệ, nhu cầu, nguồn và người phụ trách; sau đó chốt kết quả xác minh phù hợp.", en: "Complete contact, need, source, and owner information, then resolve the appropriate qualification outcome." }, route: "leads", requiredCapabilities: [CAPABILITIES.LEADS_READ], requiredData: [{ vi: "Thông tin nhận diện, nhu cầu, nguồn và người phụ trách.", en: "Identity, need, source, and owner information." }] },
      { id: "deal", title: { vi: "Theo dõi cơ hội khi cần pipeline", en: "Track an opportunity when pipeline is needed" }, body: { vi: "Tạo cơ hội nếu cần quản lý giai đoạn, giá trị, khả năng thắng và bước tiếp theo.", en: "Create an opportunity when stage, value, probability, and next-step tracking is needed." }, route: "deals", requiredCapabilities: [CAPABILITIES.DEALS_READ], requiredData: [{ vi: "Người mua, giá trị dự kiến, giai đoạn và bước tiếp theo.", en: "Buyer, expected value, stage, and next step." }] },
      { id: "quote", title: { vi: "Lập và phê duyệt báo giá", en: "Prepare and approve the quote" }, body: { vi: "Chọn sản phẩm, giá và điều khoản; phê duyệt trước khi phát hành nếu chính sách yêu cầu.", en: "Select products, pricing, and terms; approve before issuance when policy requires it." }, route: "quotes", requiredCapabilities: [CAPABILITIES.QUOTES_READ], requiredData: [{ vi: "Sản phẩm, số lượng, giá, thuế, chiết khấu và thời hạn.", en: "Products, quantities, prices, tax, discount, and validity." }] },
      { id: "order", title: { vi: "Tạo đơn hàng", en: "Create the order" }, body: { vi: "Tạo từ báo giá đã chấp nhận hoặc bán trực tiếp; giữ Buyer là Contact/Organization và chỉ bắt buộc giao nhận cho hàng vật lý.", en: "Create from an accepted quote or an allowed direct sale; preserve the Contact/Organization buyer and require delivery data only for physical goods." }, route: "orders/new", requiredCapabilities: [CAPABILITIES.ORDERS_CREATE], requiredData: [{ vi: "Buyer, sản phẩm, kế hoạch thanh toán và giao nhận khi có hàng vật lý.", en: "Buyer, products, payment plan, and delivery data when physical goods exist." }] },
    ],
    keywords: { vi: "lead cơ hội báo giá đơn hàng chuyển đổi bán hàng", en: "lead opportunity quote order conversion sales" },
    owner,
    reviewedAt,
  },
  {
    id: "workflow.order-to-shipping",
    title: { vi: "Từ đơn hàng đến thanh toán và vận đơn", en: "Order to payment and shipping" },
    summary: { vi: "Giữ Đơn hàng, Thanh toán và Vận đơn đúng ranh giới sở hữu nhưng vẫn theo dõi được toàn bộ tiến trình.", en: "Keep Order, Payment, and Shipping ownership separate while preserving an end-to-end operational view." },
    productSpaces: ["crm"],
    version: 2,
    steps: [
      { id: "order", title: { vi: "Xác nhận đơn hàng hợp lệ", en: "Confirm a valid order" }, body: { vi: "Kiểm tra Buyer, owner, sản phẩm và kế hoạch thanh toán; chỉ đơn có hàng vật lý mới bắt buộc dữ liệu giao nhận.", en: "Verify buyer, owner, products, and payment plan; delivery data is mandatory only when physical lines exist." }, route: "orders", requiredCapabilities: [CAPABILITIES.ORDERS_READ] },
      { id: "payment", title: { vi: "Ghi nhận khoản thu thực tế", en: "Record actual collections" }, body: { vi: "Tạo giao dịch trong Thanh toán và đối soát khi cần; không ghi trạng thái thanh toán trực tiếp trên đơn.", en: "Create the transaction in Payments and reconcile when needed; do not write payment state directly on the order." }, route: "payments", requiredCapabilities: [CAPABILITIES.PAYMENTS_READ] },
      { id: "shipping", title: { vi: "Tạo vận đơn", en: "Create the shipping booking" }, body: { vi: "Chỉ tạo cho đơn có dòng hàng vật lý; nếu dữ liệu người nhận gốc thiếu, quay lại cập nhật Order trước.", en: "Create a booking only for orders with physical lines; if canonical recipient data is missing, update the Order first." }, route: "shipping", requiredCapabilities: [CAPABILITIES.SHIPPING_READ] },
      { id: "delivery", title: { vi: "Theo dõi giao hàng", en: "Track delivery" }, body: { vi: "Đồng bộ trạng thái và chỉ coi là đã giao khi có bằng chứng cùng thời điểm giao thành công.", en: "Synchronize status and treat delivery as complete only when successful delivery evidence and time exist." }, route: "shipping", requiredCapabilities: [CAPABILITIES.SHIPPING_READ] },
    ],
    keywords: { vi: "đơn hàng thanh toán vận đơn giao hàng COD", en: "order payment shipping delivery COD" },
    owner,
    reviewedAt,
  },
  {
    id: "workflow.order-return-resolution",
    title: { vi: "Đổi / Trả hàng và phương án xử lý", en: "Return and resolution" },
    summary: { vi: "Tách rõ điều kiện, phê duyệt, nhận hàng và bằng chứng hoàn tiền hoặc gửi thay thế.", en: "Separate eligibility, approval, receipt, and refund or replacement evidence." },
    productSpaces: ["crm"],
    version: 1,
    steps: [
      { id: "request", title: { vi: "Tiếp nhận yêu cầu theo dòng hàng", en: "Capture the line-level request" }, body: { vi: "Chọn đơn hàng, sản phẩm, số lượng, lý do và phương án mong muốn.", en: "Choose the order, product lines, quantities, reason, and requested resolution." }, route: "returns/new", requiredCapabilities: [CAPABILITIES.RETURNS_UPDATE] },
      { id: "eligibility", title: { vi: "Kiểm tra điều kiện và phê duyệt", en: "Check eligibility and decide" }, body: { vi: "Xem kết quả điều kiện trước khi phê duyệt hoặc từ chối; ghi lý do khi cần ngoại lệ.", en: "Review eligibility before approving or rejecting; record a reason for any override." }, route: "returns", requiredCapabilities: [CAPABILITIES.RETURNS_UPDATE] },
      { id: "receive", title: { vi: "Xác nhận hàng thực nhận", en: "Confirm actual receipt" }, body: { vi: "Ghi số lượng nhận, chấp nhận, từ chối và ghi chú kiểm tra.", en: "Record received, accepted, and rejected quantities with inspection notes." }, route: "returns", requiredCapabilities: [CAPABILITIES.RETURNS_UPDATE] },
      { id: "resolve", title: { vi: "Hoàn tất phương án", en: "Complete the resolution" }, body: { vi: "Chỉ hoàn tất hoàn tiền sau Payment thành công hoặc đổi hàng sau Shipping giao thành công.", en: "Complete a refund only after Payment succeeds, or a replacement only after Shipping delivers successfully." }, route: "returns", requiredCapabilities: [CAPABILITIES.RETURNS_RESOLVE] },
    ],
    keywords: { vi: "đổi trả hoàn tiền hàng thay thế nhận hàng kiểm tra", en: "return refund replacement receipt inspection" },
    owner,
    reviewedAt,
  },
  {
    id: "workflow.support-to-task",
    title: { vi: "Từ phiếu hỗ trợ đến công việc xử lý", en: "Support ticket to assigned task" },
    summary: { vi: "Theo dõi ngữ cảnh khách hàng trong phiếu và chỉ tạo công việc cho hành động cụ thể cần giao.", en: "Keep customer context in the ticket and create tasks only for concrete assigned actions." },
    productSpaces: ["crm"],
    version: 1,
    steps: [
      { id: "ticket", title: { vi: "Tạo phiếu hỗ trợ", en: "Create the support ticket" }, body: { vi: "Ghi chủ đề, khách hàng hoặc liên hệ, loại yêu cầu, mức ưu tiên và người phụ trách.", en: "Record subject, customer or contact, request type, priority, and owner." }, route: "support/cases", requiredCapabilities: [CAPABILITIES.SUPPORT_READ] },
      { id: "follow-up", title: { vi: "Lập lần hẹn tiếp theo", en: "Set the next follow-up" }, body: { vi: "Cập nhật tiến trình trên phiếu và đặt mốc theo dõi tiếp theo.", en: "Update progress on the ticket and set the next follow-up time." }, route: "support/cases", requiredCapabilities: [CAPABILITIES.SUPPORT_UPDATE] },
      { id: "task", title: { vi: "Giao công việc cụ thể", en: "Assign a concrete task" }, body: { vi: "Tạo công việc khi cần một người thực hiện hành động rõ ràng với hạn xử lý.", en: "Create a task when a specific person must perform a clear action by a due time." }, route: "tasks", requiredCapabilities: [CAPABILITIES.TASKS_CREATE] },
    ],
    keywords: { vi: "phiếu hỗ trợ công việc chăm sóc giao việc hẹn tiếp", en: "support ticket task care assignment follow-up" },
    owner,
    reviewedAt,
  },
  {
    id: "workflow.task-execution",
    title: { vi: "Từ công việc được giao đến kết quả", en: "Assigned task to outcome" },
    summary: { vi: "Biến một yêu cầu hành động thành công việc có người phụ trách, hạn xử lý và kết quả rõ ràng.", en: "Turn an action request into work with a clear owner, due time, and outcome." },
    productSpaces: ["crm"],
    version: 1,
    steps: [
      { id: "define", title: { vi: "Xác định hành động cụ thể", en: "Define a concrete action" }, body: { vi: "Mô tả việc cần làm, kết quả mong đợi và bản ghi liên quan.", en: "Describe the action, expected outcome, and related record." }, route: "tasks", requiredCapabilities: [CAPABILITIES.TASKS_CREATE] },
      { id: "assign", title: { vi: "Giao người phụ trách và hạn xử lý", en: "Assign an owner and due time" }, body: { vi: "Chọn người có trách nhiệm và thời hạn khả thi; bổ sung mức ưu tiên khi cần.", en: "Choose the responsible person and a realistic due time; add priority when needed." }, route: "tasks", requiredCapabilities: [CAPABILITIES.TASKS_ASSIGN] },
      { id: "work", title: { vi: "Cập nhật tiến trình", en: "Update progress" }, body: { vi: "Ghi nhận thay đổi, trở ngại và lần theo dõi tiếp theo trong quá trình thực hiện.", en: "Record progress, blockers, and the next follow-up while working." }, route: "my-work", requiredCapabilities: [CAPABILITIES.TASKS_UPDATE] },
      { id: "outcome", title: { vi: "Ghi kết quả và hoàn thành", en: "Record the outcome and complete" }, body: { vi: "Chỉ hoàn thành khi hành động thực tế đã xong và kết quả được ghi rõ.", en: "Complete only when the real action is done and the outcome is clearly recorded." }, route: "tasks", requiredCapabilities: [CAPABILITIES.TASKS_COMPLETE] },
    ],
    keywords: { vi: "công việc giao việc hạn xử lý tiến trình kết quả", en: "task assignment due progress outcome" },
    owner,
    reviewedAt,
  },
  {
    id: "workflow.product-to-sale",
    title: { vi: "Từ sản phẩm đến giao dịch bán", en: "Product to sale" },
    summary: { vi: "Đưa một sản phẩm hợp lệ vào báo giá hoặc đơn hàng mà vẫn giữ đúng giá và bằng chứng thương mại.", en: "Use a valid product in a quote or order while preserving pricing and commercial evidence." },
    productSpaces: ["crm"],
    version: 1,
    steps: [
      { id: "catalog", title: { vi: "Hoàn thiện sản phẩm", en: "Complete the catalog record" }, body: { vi: "Khai báo mã, đơn vị, giá và trạng thái để sản phẩm có thể được chọn trong giao dịch.", en: "Define code, unit, price, and status so the product can be selected in transactions." }, route: "products", requiredCapabilities: [CAPABILITIES.PRODUCTS_READ] },
      { id: "quote", title: { vi: "Chốt giá trong báo giá", en: "Commit pricing in a quote" }, body: { vi: "Kiểm tra số lượng, giá, thuế và chiết khấu trước khi phát hành.", en: "Review quantity, price, tax, and discount before issuance." }, route: "quotes", requiredCapabilities: [CAPABILITIES.QUOTES_READ] },
      { id: "order", title: { vi: "Giữ bằng chứng trên đơn hàng", en: "Preserve order evidence" }, body: { vi: "Đơn hàng giữ dòng hàng và giá đã cam kết; thay đổi danh mục không viết lại lịch sử.", en: "The order preserves committed line items and prices; catalog changes do not rewrite history." }, route: "orders", requiredCapabilities: [CAPABILITIES.ORDERS_READ] },
    ],
    keywords: { vi: "sản phẩm danh mục giá báo giá đơn hàng doanh thu", en: "product catalog pricing quote order revenue" },
    owner,
    reviewedAt,
  },
  {
    id: "workflow.relationship-management",
    title: { vi: "Quản lý quan hệ khách hàng", en: "Customer relationship management" },
    summary: { vi: "Giữ Liên hệ, Tổ chức và Khách hàng đúng vai trò để theo dõi quan hệ mà không tạo dữ liệu trùng.", en: "Keep Contacts, Organizations, and Customers in their proper roles to track relationships without duplicates." },
    productSpaces: ["crm"],
    version: 1,
    steps: [
      { id: "identity", title: { vi: "Xác định cá nhân hoặc tổ chức", en: "Identify the person or organization" }, body: { vi: "Tìm hồ sơ hiện có trước khi tạo mới và kiểm tra thông tin nhận diện chính.", en: "Search existing records before creating a new one and verify core identity data." }, route: "contacts", requiredCapabilities: [CAPABILITIES.CONTACTS_READ] },
      { id: "relationship", title: { vi: "Liên kết đúng quan hệ", en: "Link the correct relationship" }, body: { vi: "Liên hệ có thể đại diện cho Tổ chức; Khách hàng phản ánh quan hệ nghiệp vụ đã hình thành.", en: "A Contact may represent an Organization; a Customer reflects an established business relationship." }, route: "organizations", requiredCapabilities: [CAPABILITIES.ORGANIZATIONS_READ] },
      { id: "history", title: { vi: "Theo dõi lịch sử thương mại và hỗ trợ", en: "Review commercial and support history" }, body: { vi: "Mở hồ sơ khách hàng để xem giao dịch, phiếu hỗ trợ và tín hiệu quan hệ.", en: "Open the customer profile to review transactions, support tickets, and relationship signals." }, route: "customers", requiredCapabilities: [CAPABILITIES.CUSTOMERS_VIEW] },
      { id: "action", title: { vi: "Tạo hành động tiếp theo", en: "Create the next action" }, body: { vi: "Dùng phiếu hỗ trợ hoặc công việc khi cần người phụ trách và kết quả cụ thể.", en: "Use a support ticket or task when an owner and concrete outcome are required." }, route: "tasks", requiredCapabilities: [CAPABILITIES.TASKS_READ] },
    ],
    keywords: { vi: "liên hệ tổ chức khách hàng quan hệ lịch sử chăm sóc", en: "contact organization customer relationship history care" },
    owner,
    reviewedAt,
  },
  {
    id: "workflow.access-governance",
    title: { vi: "Quản trị vòng đời truy cập", en: "Access lifecycle governance" },
    summary: { vi: "Quản lý lời mời, vai trò, phạm vi dữ liệu và nhật ký thay đổi trong suốt vòng đời người dùng.", en: "Manage invitations, roles, data scope, and change history throughout the user lifecycle." },
    productSpaces: ["people"],
    version: 1,
    steps: [
      { id: "invite", title: { vi: "Mời hoặc cấp tài khoản", en: "Invite or provision an account" }, body: { vi: "Xác nhận email, vai trò ban đầu và phạm vi cần thiết trước khi cấp quyền.", en: "Confirm email, initial role, and required scope before granting access." }, route: "members", productSpace: "people", requiredCapabilities: [CAPABILITIES.ACCESS_CONFIGURE] },
      { id: "role", title: { vi: "Gán quyền tối thiểu cần thiết", en: "Assign least required access" }, body: { vi: "Rà soát capability, phạm vi dữ liệu và quyền trường theo trách nhiệm công việc.", en: "Review capabilities, data scope, and field access for the job responsibility." }, route: "roles", productSpace: "people", requiredCapabilities: [CAPABILITIES.ACCESS_CONFIGURE] },
      { id: "review", title: { vi: "Rà soát định kỳ", en: "Review periodically" }, body: { vi: "Kiểm tra thành viên không còn hoạt động, vai trò quá rộng và thay đổi trách nhiệm.", en: "Review inactive members, overly broad roles, and responsibility changes." }, route: "members", productSpace: "people", requiredCapabilities: [CAPABILITIES.ACCESS_READ] },
      { id: "audit", title: { vi: "Đối chiếu nhật ký", en: "Inspect the audit log" }, body: { vi: "Dùng nhật ký để xác nhận ai đã thay đổi tài khoản hoặc quyền và khi nào.", en: "Use the audit log to verify who changed accounts or access and when." }, route: "audit", productSpace: "people", requiredCapabilities: [CAPABILITIES.AUDIT_READ] },
    ],
    keywords: { vi: "quản trị truy cập lời mời vai trò phạm vi nhật ký", en: "access governance invitation role scope audit" },
    owner,
    reviewedAt,
  },
];
