import { repositoryRoot } from "../../../scripts/quality/core/repo-context.mjs";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = repositoryRoot;
const read = (relativePath: string) => fs.readFileSync(path.join(root, relativePath), "utf8");

const sidebar = read("src/app/shell/layout/Sidebar.tsx");
const sidebarItem = read("src/app/shell/layout/SidebarItem.tsx");
const appShell = read("src/app/shell/layout/AppShell.tsx");
const topBar = read("src/app/shell/layout/TopBar.tsx");
const reports = read("src/workspaces/crm/presentation/pages/ReportsPage.tsx");
const aiButton = read("src/components/ai/AiAssistantButton.tsx");
const aiDrawer = read("src/components/ai/AiAssistantDrawer.tsx");
const aiChat = read("src/components/ai/AiChatPanel.tsx");
const aiContext = read("src/workspaces/crm/ai-context/presentation/useGlobalAiContext.ts");
const loading = read("src/components/loading/RouteLoadingExperience.tsx");
const css = read("src/index.css");
const tabs = read("src/shared/components/ui/Tabs.tsx");
const tabTransition = read("src/shared/components/ui/RecordTabTransition.tsx");
const operationTabs = read("src/components/crm/operations/OperationDetailTabs.tsx");

const workGroupStart = sidebar.indexOf('renderSidebarGroup("crm-work"');
const serviceGroupStart = sidebar.indexOf('renderSidebarGroup("crm-service"');
assert.ok(workGroupStart >= 0 && serviceGroupStart > workGroupStart, "Sidebar must keep Work before Service.");
assert.ok(sidebar.slice(workGroupStart, serviceGroupStart).includes('path("tasks"), label("Công việc", "Tasks")'), "Tasks must live in the Work group.");
assert.equal(sidebar.includes("Workspace đang hoạt động"), false, "Sidebar must not show the redundant active-workspace footer card.");
assert.ok(sidebar.includes("crm-sidebar-scroll"), "Sidebar must use the refined vertical scroll surface.");
assert.ok(sidebarItem.includes('data-sidebar-item="v2"'), "Sidebar items must use the upgraded interactive surface.");
assert.ok(sidebarItem.includes("unicore-sidebar-active-surface"), "Sidebar must animate the active item surface.");
assert.ok(css.includes(".crm-sidebar-scroll:hover::-webkit-scrollbar-thumb"), "Sidebar scrollbar must reveal subtly on hover.");
assert.ok(sidebar.includes('path("reports"), label("Báo cáo", "Reports")'), "Reports must be visible in CRM navigation when permitted.");
assert.ok(sidebar.includes('path("dashboard"), "Dashboard"'), "Dashboard must be directly available in CRM navigation.");
assert.equal(sidebar.includes("Bàn làm việc"), false, "The retired Workbench label must not return to CRM navigation.");
assert.ok(reports.includes('data-report-design="v2"'), "Reports must use the redesigned analytics experience.");
assert.equal(reports.includes("baseRevenue"), false, "Reports must not seed fake revenue trends.");
assert.equal(sidebar.includes('data-sidebar-toggle="v4"'), false, "Sidebar must not keep the old protruding edge handle.");
assert.ok(topBar.includes('data-sidebar-toggle="v5"'), "Sidebar collapse control must live in the top toolbar.");
assert.ok(topBar.includes("PanelLeftOpen") && topBar.includes("PanelLeftClose"), "Sidebar toggle must use standard panel affordances.");

assert.ok(aiButton.includes("<Bot") && aiButton.includes("<Sparkles"), "AI floating utility must use a friendly assistant identity.");
assert.ok(aiButton.includes("bg-gradient-to-r from-violet-600 via-indigo-600 to-sky-500"), "AI floating utility must avoid the retired black launcher surface.");
assert.ok(aiButton.includes("whileHover") && aiButton.includes("whileTap") && aiButton.includes("useReducedMotion"), "AI launcher motion must be responsive and reduced-motion safe.");
assert.ok(aiButton.includes('data-ai-floating-utility="enterprise"'), "AI floating utility must expose the enterprise launcher contract.");
assert.ok(aiButton.includes("createPortal") && aiButton.includes("document.body"), "AI floating utility must portal to document.body so its fixed position is anchored to the viewport, not transformed page content.");
assert.ok(aiButton.includes('data-ai-viewport-anchor="fixed"'), "AI floating utility must declare its viewport-fixed anchoring contract.");
assert.ok(aiButton.includes('position: "fixed"') && aiButton.includes('right: "max(1rem, env(safe-area-inset-right))"') && aiButton.includes('bottom: "max(1rem, env(safe-area-inset-bottom))"'), "AI floating utility must stay pinned to the lower-right viewport safe area.");
assert.equal(aiButton.includes("proactiveCount"), false, "AI floating utility must not show reminder statistics.");
assert.ok(aiButton.includes("Trợ lý AI") && aiButton.includes("AI assistant"), "AI launcher must expose a clear product label on supported viewports.");
assert.ok(aiDrawer.includes('data-ai-workspace="v3"'), "AI must retain a full-screen workspace contract.");
assert.ok(aiDrawer.includes('data-ai-layout="chat-history"'), "AI workspace must use chat plus conversation history.");
assert.ok(aiDrawer.includes('transformOrigin: "calc(100% - 44px) calc(100% - 44px)"') && aiDrawer.includes("scale: 0.96"), "AI workspace must open from the launcher with a polished transition.");
assert.ok(aiDrawer.includes("getAiChatThreads") && aiDrawer.includes("createAiChatThread"), "AI workspace must load and create persistent chat threads.");
assert.equal(aiDrawer.includes("buildProactiveAiReminders"), false, "AI page must not render the previous reminder dashboard.");
assert.equal(aiDrawer.includes("context.globalContext.customersCount"), false, "AI page must not render CRM statistics panels.");
assert.ok(aiChat.includes('data-ai-chat-panel="v3"'), "AI chat must use the conversation-first panel contract.");
assert.ok(aiChat.includes("askCrmAi(text, context)"), "AI responses must execute against the active CRM context.");
assert.ok(aiChat.includes("createTaskCommand"), "AI chat must support confirmed task creation through the typed command boundary.");
assert.equal(aiChat.includes("createTaskSnapshot"), false, "AI chat must not write through the retired browser snapshot boundary.");
assert.ok(aiChat.includes("askNextTaskQuestion"), "AI task commands must request missing information.");
assert.ok(aiChat.includes("isConfirmIntent"), "AI must require confirmation before writing a task.");
assert.ok(aiContext.includes("parseCanonicalRoute(pathname)"), "AI record focus must resolve canonical workspace routes.");

assert.equal(appShell.includes('data-page-transition="v1"'), false, "Legacy loading-like page transitions must remain removed.");
assert.equal(appShell.includes('data-route-progress="v1"'), false, "Normal route changes must not show synthetic progress feedback.");
assert.ok(appShell.includes('data-route-content="stable"'), "The application shell must keep route content visually stable.");
assert.ok(appShell.includes('data-navigation-motion="v2"'), "Normal navigation should use the lightweight non-loading route motion.");
assert.ok(appShell.includes("useAnimationControls") && appShell.includes("duration: 0.16"), "Navigation motion must be short, controlled and non-blocking.");
assert.equal(appShell.includes('key={location.pathname}'), false, "Navigation motion must not remount route content on every path change.");
assert.ok(tabs.includes("layoutId") && tabs.includes("onChange(id);"), "Shared tabs must animate their active surface and commit selection synchronously.");
assert.equal(tabs.includes("React.startTransition"), false, "Tab selection must not be wrapped in a transition because suspended tab content can leave the previous tab active.");
assert.equal(operationTabs.includes("React.startTransition"), false, "Operation tabs must commit selection synchronously.");
assert.ok(operationTabs.includes('data-operation-detail-tabs="v2"'), "Operation tabs must use the upgraded motion contract.");
assert.ok(tabTransition.includes('data-tab-content-motion="v2"') && tabTransition.includes('mode="popLayout"'), "Tab content must transition without a blank wait frame.");
assert.ok(loading.includes("data-async-route-loading=\"v2\""), "A loading indicator must remain available for real lazy-route suspension.");
assert.ok(loading.includes("window.setTimeout") && loading.includes("delayMs"), "Lazy-route feedback must be delayed so fast loads stay invisible.");
assert.equal(loading.includes("route-skeleton-shimmer"), false, "Generic route fallback must not render a full-page skeleton for every lazy screen.");
assert.ok(css.includes("@media (prefers-reduced-motion: reduce)"), "Motion must respect reduced-motion preferences.");

console.log("Shell, AI and loading experience contracts: PASS");
