import { Product } from "../../domain/model/product.types";

export const PRODUCT_DEMO_SEED: Product[] = [
  {
    id: "prod_1",
    sku: "CRM-STARTER-SUB",
    name: "CRM Starter Subscription",
    type: "subscription",
    status: "active",
    category: "Software License",
    description: "Bộ tính năng CRM cơ bản cho các nhóm kinh doanh dưới 5 người, hỗ trợ quản lý phễu cơ hội và danh bạ cơ bản.",
    unit: "User/Tháng",
    listPrice: 150000,
    currency: "VND",
    taxRate: 10,
    taxMode: "exclusive",
    billingCycle: "monthly",
    costPrice: 30000,
    marginPercent: 80,
    isSubscription: true,
    isRenewable: true,
    warrantyMonths: 0,
    defaultContractMonths: 12,
    tags: ["SaaS", "Starter", "License"],
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-05-20T10:30:00Z"
  },
  {
    id: "prod_2",
    sku: "CRM-PROF-SUB",
    name: "CRM Professional Subscription",
    type: "subscription",
    status: "active",
    category: "Software License",
    description: "Phiên bản chuyên nghiệp hỗ trợ quy trình bán hàng nâng cao, tự động hóa phễu, phân tích AI cơ bản và báo cáo đa chiều.",
    unit: "User/Tháng",
    listPrice: 350000,
    currency: "VND",
    taxRate: 10,
    taxMode: "exclusive",
    billingCycle: "yearly",
    costPrice: 50000,
    marginPercent: 85.7,
    isSubscription: true,
    isRenewable: true,
    warrantyMonths: 0,
    defaultContractMonths: 12,
    tags: ["SaaS", "Professional", "Best Seller"],
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-06-01T09:15:00Z"
  },
  {
    id: "prod_3",
    sku: "CRM-ENT-SUITE",
    name: "CRM Enterprise Suite",
    type: "subscription",
    status: "active",
    category: "Software License",
    description: "Hệ sinh thái CRM toàn diện cho tập đoàn lớn. Tích hợp không giới hạn, bảo mật cấp độ cao nhất, hỗ trợ tùy biến thực địa.",
    unit: "User/Tháng",
    listPrice: 750000,
    currency: "VND",
    taxRate: 10,
    taxMode: "exclusive",
    billingCycle: "yearly",
    costPrice: 100000,
    marginPercent: 86.7,
    isSubscription: true,
    isRenewable: true,
    warrantyMonths: 0,
    defaultContractMonths: 24,
    tags: ["SaaS", "Enterprise", "Customizable"],
    createdAt: "2026-01-12T09:00:00Z",
    updatedAt: "2026-06-12T14:20:00Z"
  },
  {
    id: "prod_4",
    sku: "CRM-IMPL-PKG",
    name: "Implementation Package",
    type: "implementation",
    status: "active",
    category: "Professional Services",
    description: "Gói dịch vụ vận hành và triển khai hệ thống CRM tương thích cho quy trình doanh nghiệp, thiết lập phễu và trường dữ liệu mẫu.",
    unit: "Gói",
    listPrice: 25000000,
    currency: "VND",
    taxRate: 8,
    taxMode: "exclusive",
    billingCycle: "one_time",
    costPrice: 12000000,
    marginPercent: 52,
    isSubscription: false,
    isRenewable: false,
    warrantyMonths: 6,
    defaultContractMonths: 1,
    tags: ["Service", "Deployment", "Setup"],
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-01-15T11:00:00Z"
  },
  {
    id: "prod_5",
    sku: "CRM-MIGR-SRV",
    name: "Data Migration Service",
    type: "service",
    status: "active",
    category: "Professional Services",
    description: "Chuyển đổi dữ liệu và làm sạch lịch sử khách hàng từ hệ thống CRM cũ (Salesforce, HubSpot, Excel) sang hệ thống UnicoreCRM ròng.",
    unit: "Dự án",
    listPrice: 15000000,
    currency: "VND",
    taxRate: 8,
    taxMode: "inclusive",
    billingCycle: "one_time",
    costPrice: 8000000,
    marginPercent: 46.7,
    isSubscription: false,
    isRenewable: false,
    warrantyMonths: 3,
    defaultContractMonths: 2,
    tags: ["Service", "Database", "Setup"],
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-03-10T16:45:00Z"
  },
  {
    id: "prod_6",
    sku: "CRM-TRAIN-SRV",
    name: "Training Service",
    type: "service",
    status: "active",
    category: "Professional Services",
    description: "Chương trình đào tạo thực hành trực tiếp và cấp chứng chỉ sử dụng UnicoreCRM cho đội ngũ nhân sự B2B & chăm sóc khách hàng.",
    unit: "Khóa học",
    listPrice: 8000000,
    currency: "VND",
    taxRate: 8,
    taxMode: "inclusive",
    billingCycle: "one_time",
    costPrice: 2000000,
    marginPercent: 75,
    isSubscription: false,
    isRenewable: false,
    warrantyMonths: 0,
    defaultContractMonths: 0,
    tags: ["Training", "Consulting", "Service"],
    createdAt: "2026-01-25T15:00:00Z",
    updatedAt: "2026-01-25T15:00:00Z"
  },
  {
    id: "prod_7",
    sku: "CRM-SUPP-SLA",
    name: "Priority Support SLA",
    type: "support_sla",
    status: "active",
    category: "Support SLA",
    description: "Cam kết phản hồi dưới 1 giờ phòng vệ, tổng đài hỗ trợ 24/7 chuyên biệt, chuyên viên hỗ trợ kĩ thuật xử lý sự cố nóng tức thì.",
    unit: "Tháng",
    listPrice: 5000000,
    currency: "VND",
    taxRate: 10,
    taxMode: "exclusive",
    billingCycle: "monthly",
    costPrice: 1500000,
    marginPercent: 70,
    isSubscription: true,
    isRenewable: true,
    warrantyMonths: 0,
    defaultContractMonths: 12,
    tags: ["SLA", "Enterprise", "Support"],
    createdAt: "2026-02-01T08:30:00Z",
    updatedAt: "2026-02-01T08:30:00Z"
  },
  {
    id: "prod_8",
    sku: "CRM-ZALO-ADD",
    name: "Zalo/Email Marketing Add-on",
    type: "addon",
    status: "active",
    category: "Marketing Plugins",
    description: "Tiện ích mở rộng kết nối trực tiếp Zalo ZNS và hệ thống gửi Email chăm sóc tự động theo hành vi trạng thái phễu hoặc kịch bản thiết lập.",
    unit: "Tháng",
    listPrice: 500000,
    currency: "VND",
    taxRate: 10,
    taxMode: "exclusive",
    billingCycle: "monthly",
    costPrice: 150000,
    marginPercent: 70,
    isSubscription: true,
    isRenewable: true,
    warrantyMonths: 0,
    defaultContractMonths: 12,
    tags: ["Marketing", "Plugin", "Addon"],
    createdAt: "2026-02-15T09:10:00Z",
    updatedAt: "2026-05-15T11:00:00Z"
  },
  {
    id: "prod_9",
    sku: "CRM-API-PKG",
    name: "API Integration Package",
    type: "package",
    status: "inactive",
    category: "Professional Services",
    description: "Bộ thư viện Webhooks & API mở tích hợp hệ thống nội bộ ERP, kết nối thanh toán tự động và đồng bộ hóa đa kênh thời gian thực.",
    unit: "Dự án",
    listPrice: 35000000,
    currency: "VND",
    taxRate: 8,
    taxMode: "exclusive",
    billingCycle: "one_time",
    costPrice: 18000000,
    marginPercent: 48.6,
    isSubscription: false,
    isRenewable: false,
    warrantyMonths: 12,
    defaultContractMonths: 3,
    tags: ["API", "Integration", "ERP"],
    createdAt: "2026-02-20T14:00:00Z",
    updatedAt: "2026-06-05T13:40:00Z"
  },
  {
    id: "prod_10",
    sku: "CRM-REPT-PKG",
    name: "Custom Report Package",
    type: "addon",
    status: "draft",
    category: "Analytics Tools",
    description: "Gói xây dựng và tùy biến 5 hệ dashboard phân tích chuyên sâu đa nguồn theo mẫu yêu cầu độc quyền của giám đốc kinh doanh.",
    unit: "Gói",
    listPrice: 12000000,
    currency: "VND",
    taxRate: 10,
    taxMode: "exclusive",
    billingCycle: "one_time",
    costPrice: 4000000,
    marginPercent: 66.7,
    isSubscription: false,
    isRenewable: false,
    warrantyMonths: 6,
    defaultContractMonths: 1,
    tags: ["Report", "BI", "Analytics"],
    createdAt: "2026-03-01T15:00:00Z",
    updatedAt: "2026-03-01T15:00:00Z"
  },
  {
    id: "prod_11",
    sku: "CRM-ONS-CONS",
    name: "Onsite Consulting Day",
    type: "service",
    status: "active",
    category: "Professional Services",
    description: "Bản kĩ năng cao cấp từ chuyên gia chuyên sâu tư vấn tái thiết kế trực tiếp phễu thương mại, sắp đặt KPI chuyển đổi kinh doanh tại chỗ.",
    unit: "Ngày",
    listPrice: 10000000,
    currency: "VND",
    taxRate: 8,
    taxMode: "none",
    billingCycle: "one_time",
    costPrice: 2000000,
    marginPercent: 80,
    isSubscription: false,
    isRenewable: false,
    warrantyMonths: 0,
    defaultContractMonths: 0,
    tags: ["Consulting", "Executive", "Service"],
    createdAt: "2026-03-10T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z"
  },
  {
    id: "prod_12",
    sku: "CRM-RENEW-SUPP",
    name: "Renewal Support Package",
    type: "support_sla",
    status: "archived",
    category: "Support SLA",
    description: "Gói gia hạn chăm sóc kĩ thuật kế thừa đặc quyền và nâng cấp bảo trì các phân hệ phụ trợ ERP phát sinh sau giai đoạn đóng dự án.",
    unit: "Gói",
    listPrice: 7000000,
    currency: "VND",
    taxRate: 10,
    taxMode: "inclusive",
    billingCycle: "yearly",
    costPrice: 3000000,
    marginPercent: 57.1,
    isSubscription: true,
    isRenewable: true,
    warrantyMonths: 0,
    defaultContractMonths: 12,
    tags: ["Obsolete", "SLA", "Renewal"],
    createdAt: "2026-01-05T09:00:00Z",
    updatedAt: "2026-05-10T11:20:00Z"
  }
];
