import assert from "node:assert/strict";
import { money } from "@/shared/money";
import { InMemoryPaymentRepository } from "@/modules/payments/infrastructure/InMemoryPaymentRepository";
import { PAYMENT_METHOD_CATALOG, PAYMENT_PROVIDER_CATALOG } from "@/modules/payments/infrastructure/paymentCatalog.seed";
import { applyAuthoritativePaymentIntentSnapshot, cancelPaymentIntent, createPaymentIntent, retryPaymentIntent } from "@/modules/payments/application/commands/paymentIntentCommands";
const now = "2026-07-15T00:00:00.000Z";
const repo = new InMemoryPaymentRepository({ methodCatalog: PAYMENT_METHOD_CATALOG, providerCatalog: PAYMENT_PROVIDER_CATALOG });
const input = { id: "intent-1", buyerRef: { type: "CONTACT", id: "buyer" } as const, amount: money("100", "VND"), methodCode: "gateway-card", providerCode: "development-gateway", returnContext: { routeKey: "payments" }, checkoutUrl: "https://checkout.example.invalid/pay/intent-1", expiresAt: "2026-07-15T00:15:00.000Z", idempotencyKey: "intent-key", now };
const created = createPaymentIntent(repo, input);
assert.equal(created.state, "REQUIRES_ACTION");
assert.equal(createPaymentIntent(repo, { ...input, id: "different" }).id, created.id, "Idempotent replay must not duplicate intents");
assert.throws(() => createPaymentIntent(repo, { ...input, id: "bad", idempotencyKey: "bad", checkoutUrl: "https://evil.example/pay" }), /origin/i);
const failed = applyAuthoritativePaymentIntentSnapshot(repo, { ...created, state: "FAILED", failureCode: "DECLINED", version: 2, updatedAt: "2026-07-15T00:01:00.000Z" });
const retry = retryPaymentIntent(repo, failed.id, { id: "intent-2", expectedVersion: failed.version, expiresAt: "2026-07-15T00:20:00.000Z", idempotencyKey: "retry-key", now: "2026-07-15T00:02:00.000Z", checkoutUrl: "https://checkout.example.invalid/pay/intent-2" });
assert.equal(retry.clientPayload?.retryOfIntentId, failed.id);
assert.equal(repo.listIntents().find((item) => item.id === failed.id)?.state, "FAILED", "Retry must preserve failed history");
assert.throws(() => cancelPaymentIntent(repo, retry.id, { expectedVersion: retry.version + 1, now }), /VERSION_CONFLICT/);
const cancelled = cancelPaymentIntent(repo, retry.id, { expectedVersion: retry.version, now });
assert.equal(cancelled.state, "CANCELLED");
console.log("Payment Intent contracts: PASS");
