import type { ArchiveOrdersBatchRequest, CreateDirectOrderDraftRequest, CreateDirectOrderDraftResponse, OrderBatchMutationResponse, OrderMutationResponse, RecordOrderSendEvidenceRequest, ReplaceOrderDraftRequest } from "@/platform/api/generated/commercialApi";
import type { DirectOrderDraftAuthorityResult, OrderBatchMutationResult, OrderMutationEvidence, OrderMutationResult, OrderVersionItem, RecordOrderSendEvidenceInput } from "../../application/ports/OrderApiRuntime";
import { projectOrderReadModel, type OrderReadModel } from "../../application/read-models/orderReadModel";
import type { CustomerOrder } from "../../domain/model/order.types";
export function mapOrderDraft(order: CustomerOrder): CreateDirectOrderDraftRequest | ReplaceOrderDraftRequest {
  if (!order.paymentAgreementSnapshot) throw new Error("ORDER_PAYMENT_AGREEMENT_REQUIRED");
  return compact({ buyerRef: order.buyerRef, sourceDealId: order.sourceDealId, currency: (order.currency ?? "VND").toUpperCase(), items: order.items.map((line) => ({ productId: line.productId, productName: line.productNameSnapshot || line.productName || line.name || "", sku: line.skuSnapshot, description: line.descriptionSnapshot, quantity: line.quantity, unitPrice: { amount: String(line.unitPriceSnapshot), currency: (order.currency ?? "VND").toUpperCase() }, discountPercent: String(line.discountPercent ?? 0), taxRate: String(line.taxRateSnapshot ?? 0), taxMode: line.taxModeSnapshot ?? "none", fulfillmentKind: line.fulfillmentKind ?? "NONE", billingCycle: line.billingCycleSnapshot })), adjustments: order.adjustments?.map((item) => ({ label: item.label, type: item.type, calculation: item.calculation, value: String(item.value) })), recipientName: order.recipientName, recipientPhone: order.recipientPhone, recipientEmail: order.recipientEmail, shippingAddress: order.shippingAddress, expectedDeliveryDate: order.expectedDeliveryDate, paymentAgreement: order.paymentAgreementSnapshot, notes: order.notes, internalNotes: order.internalNotes }) as CreateDirectOrderDraftRequest;
}
export function mapRecordOrderSendEvidence(input: RecordOrderSendEvidenceInput): RecordOrderSendEvidenceRequest { return compact({ deliveryId: input.id, channel: input.channel === "CHAT_APP" || input.channel === "SMS" ? "OTHER" : input.channel, evidenceType: input.evidenceType ?? "USER_CONFIRMED_SENT", recipientEmail: input.recipientEmail, recipient: input.recipient, note: input.note, sentAt: input.sentAt, fileName: input.fileName }); }
export function mapArchiveOrdersBatch(items: readonly OrderVersionItem[], reason: string): ArchiveOrdersBatchRequest { return { items: items.map((item) => ({ orderId: item.orderId, expectedVersion: item.expectedVersion })), reason: reason.trim() }; }
export function mapDirectOrderDraftMutation(response: CreateDirectOrderDraftResponse): DirectOrderDraftAuthorityResult { return { order: projectOrderReadModel(response.result.order as OrderReadModel), paymentPlan: { agreementSnapshot: { version: response.result.paymentPlan.agreementSnapshot.version } }, commercialSnapshotFingerprint: response.result.commercialSnapshotFingerprint, evidence: mapEvidence(response) }; }
export function mapOrderMutation(response: OrderMutationResponse): OrderMutationResult { return { order: projectOrderReadModel(response.result.order as OrderReadModel), evidence: mapEvidence(response) }; }
export function mapOrderBatchMutation(response: OrderBatchMutationResponse): OrderBatchMutationResult { return { orders: response.result.orders.map((item) => projectOrderReadModel(item as OrderReadModel)), evidence: mapEvidence(response) }; }
function mapEvidence(response: CreateDirectOrderDraftResponse | OrderMutationResponse | OrderBatchMutationResponse): OrderMutationEvidence { return { authority: "backend", commandId: response.commandId, correlationId: response.correlationId, aggregateId: response.aggregateId, aggregateType: response.aggregateType, version: response.version, occurredAt: response.occurredAt, outcome: response.outcome, warnings: response.warnings ?? [], emittedEventIds: response.emittedEventIds ?? [], auditEvidenceIds: response.auditEvidenceIds ?? [] }; }
function compact<T extends Record<string, unknown>>(value: T): T { return Object.fromEntries(Object.entries(value).filter(([, item]) => item !== undefined)) as T; }
