// @generated by scripts/api/generate-openapi-client.mjs from OpenAPI and docs/backend-readiness/query-registry.json.
export interface ProductionModuleQueryDefinition {
  key: string;
  list?: { operationId: string; path: string; allowedQueryParameters: readonly string[] };
  detail?: { operationId: string; pathTemplate: string; pathParameter: string };
}

export const PRODUCTION_MODULE_QUERY_DEFINITIONS = [
  { key: "commercialEvidence" },
  { key: "contacts", list: { operationId: "listContacts", path: "/contacts", allowedQueryParameters: [] }, detail: { operationId: "getContact", pathTemplate: "/contacts/{contactId}", pathParameter: "contactId" } },
  { key: "customers", list: { operationId: "listCustomers", path: "/customers", allowedQueryParameters: [] }, detail: { operationId: "getCustomer", pathTemplate: "/customers/{customerId}", pathParameter: "customerId" } },
  { key: "deals", list: { operationId: "listDeals", path: "/deals", allowedQueryParameters: ["cursor","limit","search","sortBy","sortDirection","stageCode","stageCategory","ownerId","buyerType","buyerId"] }, detail: { operationId: "getDeal", pathTemplate: "/deals/{dealId}", pathParameter: "dealId" } },
  { key: "invoices", list: { operationId: "listInvoices", path: "/invoices", allowedQueryParameters: [] }, detail: { operationId: "getInvoice", pathTemplate: "/invoices/{invoiceId}", pathParameter: "invoiceId" } },
  { key: "leads", list: { operationId: "listLeads", path: "/leads", allowedQueryParameters: ["cursor","limit","search","workState","ownerId"] }, detail: { operationId: "getLead", pathTemplate: "/leads/{leadId}", pathParameter: "leadId" } },
  { key: "orders", list: { operationId: "listOrders", path: "/orders", allowedQueryParameters: ["cursor","limit","search","sortBy","sortDirection","state","sourceQuoteId","sourceDealId","buyerType","buyerId"] }, detail: { operationId: "getOrder", pathTemplate: "/orders/{orderId}", pathParameter: "orderId" } },
  { key: "organizations", list: { operationId: "listOrganizations", path: "/organizations", allowedQueryParameters: ["q","status","industry","sizeBand","ownerId","cursor","limit"] }, detail: { operationId: "getOrganization", pathTemplate: "/organizations/{organizationId}", pathParameter: "organizationId" } },
  { key: "payments", list: { operationId: "listPaymentRecords", path: "/payments", allowedQueryParameters: ["buyerId"] }, detail: { operationId: "getPaymentRecordDetail", pathTemplate: "/payments/{paymentRecordId}/detail", pathParameter: "paymentRecordId" } },
  { key: "products", list: { operationId: "listProducts", path: "/products", allowedQueryParameters: [] }, detail: { operationId: "getProduct", pathTemplate: "/products/{productId}", pathParameter: "productId" } },
  { key: "quotes", list: { operationId: "listQuotes", path: "/quotes", allowedQueryParameters: ["cursor","limit","search","sortBy","sortDirection","status","sourceDealId","buyerType","buyerId"] }, detail: { operationId: "getQuote", pathTemplate: "/quotes/{quoteId}", pathParameter: "quoteId" } },
  { key: "returns", list: { operationId: "listReturns", path: "/returns", allowedQueryParameters: ["cursor","limit","search","sortBy","sortDirection","status","orderId","buyerType","buyerId"] }, detail: { operationId: "getReturn", pathTemplate: "/returns/{returnId}", pathParameter: "returnId" } },
  { key: "shipping", list: { operationId: "listShippingBookings", path: "/shipping", allowedQueryParameters: ["cursor","limit","search","sortBy","sortDirection","sourceType","sourceId","bookingStatus","externalStatus"] }, detail: { operationId: "getShippingBooking", pathTemplate: "/shipping/{bookingId}", pathParameter: "bookingId" } },
  { key: "support", list: { operationId: "listSupportCases", path: "/support/cases", allowedQueryParameters: ["cursor","limit","search","sortBy","sortDirection","status","priority","category","ownerId","relationshipType","relationshipId","slaStatus"] }, detail: { operationId: "getSupportCase", pathTemplate: "/support/cases/{caseId}", pathParameter: "caseId" } },
  { key: "tasks", list: { operationId: "listTasks", path: "/tasks", allowedQueryParameters: ["cursor","limit","search","sortBy","sortDirection","status","priority","assigneeId","relationshipType","relationshipId","recordModuleKey","recordId","overdueAt"] }, detail: { operationId: "getTask", pathTemplate: "/tasks/{taskId}", pathParameter: "taskId" } },
] as const satisfies readonly ProductionModuleQueryDefinition[];
