import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { JSDOM } from "jsdom";
import type { HttpClient, HttpRequest } from "@/platform/api/client/HttpClient";
import type { LeadDocument } from "@/platform/api/generated/commercialApi";

const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', { url: "http://localhost", pretendToBeVisual: true });
const { window } = dom;
for (const key of ["window", "document", "navigator", "localStorage", "HTMLElement", "SVGElement", "Element", "Node", "Event", "CustomEvent", "EventTarget", "MutationObserver"] as const) {
  Object.defineProperty(globalThis, key, { value: key === "window" ? window : window[key], configurable: true });
}
Object.defineProperty(globalThis, "IS_REACT_ACT_ENVIRONMENT", { value: true, configurable: true });
const { signIn } = await import("@/platform/identity-auth");
assert.equal(signIn({ email: "admin@unicorecrm.local", password: "admin123" }).ok, true);
const { initializeApplicationComposition } = await import("@/app/composition");
await initializeApplicationComposition({ mode: "demo" });
const React = await import("react");
const { act } = React;
const { createRoot } = await import("react-dom/client");
const { I18nProvider } = await import("@/i18n");
const { ApplicationError } = await import("@/shared/domain");
const { createLeadConnectedApiRuntime } = await import("@/modules/leads/infrastructure/http/createLeadConnectedApiRuntime");
const { configureLeadApplication, getLeadApplicationServices } = await import("@/modules/leads/application/composition/leadApplicationServices");
const { mapLeadDocumentToApplication } = await import("@/modules/leads/infrastructure/http/LeadApiMapper");
const { useLeadQueueClaim } = await import("@/modules/leads/presentation/hooks/useLeadQueueClaim");
const { useLeadSelection } = await import("@/modules/leads/presentation/hooks/useLeadSelection");
const { LeadClaimButton } = await import("@/modules/leads/presentation/components/LeadClaimButton");
const { LEAD_OPERATION, isLeadOperationAvailable } = await import("@/modules/leads/application/leadOperationAvailability");
const shared = await import("@/shared/application");
const { useLeadOwnerAssign } = await import("@/modules/leads/presentation/hooks/useLeadOwnerAssign");
const { LeadOwnerAssignDialog, LeadOwnerAssignAction } = await import("@/modules/leads/presentation/components/LeadOwnerAssignAction");
const document: LeadDocument = { id: "lead_assign_ui", displayName: "Assign Lead", ownerId: null, version: 5, createdAt: "2026-09-30T00:00:00Z", updatedAt: "2026-09-30T00:00:00Z", leadWorkState: "NEW", score: 0, interestedProducts: [], activityProjection: "NOT_INCLUDED" };
const requests: HttpRequest[] = [];
let mode: "SUCCESS" | "PENDING" | "NETWORK" | "VERSION" | "DENIED" | "HIDDEN" | "INVALID" = "SUCCESS";
let release: (() => void) | undefined;
let version = 5;
const client: HttpClient = { async request<TResponse, TBody = unknown>(input: HttpRequest<TBody>): Promise<TResponse> {
  requests.push(input);
  if (input.operationId === "getLead") return { ...document, version } as TResponse;
  if (input.operationId === "listLeads") return { items: [], pageInfo: { hasNextPage: false, totalCount: 0 } } as TResponse;
  if (mode === "PENDING") await new Promise<void>(resolve => { release = resolve; });
  if (mode === "NETWORK") throw new ApplicationError({ code: "NETWORK_ERROR", category: "NETWORK", message: "ambiguous", retryable: true });
  if (mode === "VERSION") throw new ApplicationError({ code: "VERSION_CONFLICT", category: "CONFLICT", message: "stale", status: 412 });
  if (mode === "DENIED") throw new ApplicationError({ code: "ACCESS_DENIED", category: "AUTHORIZATION", message: "denied", status: 403 });
  if (mode === "HIDDEN") throw new ApplicationError({ code: "RESOURCE_NOT_FOUND", category: "NOT_FOUND", message: "hidden", status: 404 });
  if (mode === "INVALID") throw new ApplicationError({ code: "LEAD_OWNER_NOT_ASSIGNABLE", category: "VALIDATION", message: "invalid target", status: 422 });
  const ownerId = (input.body as { ownerId: string }).ownerId;
  return { commandId: "assign_cmd", correlationId: "assign_corr", aggregateId: document.id, aggregateType: "LEAD", version: 6, occurredAt: document.updatedAt, outcome: "COMMITTED", warnings: [], emittedEventIds: ["assign_event"], auditEvidenceIds: ["assign_audit"], result: { ...document, ownerId, version: 6 } } as TResponse;
}};
const base = getLeadApplicationServices();
let records = [mapLeadDocumentToApplication(document)];
const services = { ...base, repository: { list: () => [...records], getById: (id: string) => records.find(record => record.id === id), replace: (next: typeof records) => { records = next; }, subscribe: () => () => {} } };
const api = createLeadConnectedApiRuntime(client);
configureLeadApplication({ ...services, api });
assert.equal(isLeadOperationAvailable(LEAD_OPERATION.ASSIGN_OWNER), true);
assert.equal(isLeadOperationAvailable(LEAD_OPERATION.CLAIM), true);
const before = requests.length;
await assert.rejects(() => api.commands.assignLeadOwnerBatch({ ownerId: "member_target", reason: "r", items: [{ leadId: document.id, expectedVersion: 5 }] }, { idempotencyKey: "batch" }));
await assert.rejects(() => api.commands.handoverLeadWithTasks(document.id, { nextOwnerId: "member_target", reason: "r", taskTargets: [] }, { idempotencyKey: "handover", expectedVersion: 5 }));
assert.equal(requests.length, before, "Future operations send zero HTTP");
let current!: ReturnType<typeof useLeadOwnerAssign>;
let selection = [document.id, "lead_other"];
let queue = [document.id, "lead_other"];
let refreshCount = 0;
const root = createRoot(window.document.getElementById("root")!);
function Fixture() {
  current = useLeadOwnerAssign(mapLeadDocumentToApplication(document), id => { selection = selection.filter(value => value !== id); }, async () => { refreshCount++; queue = queue.filter(id => id !== document.id); });
  return null;
}
async function mount() { await act(async () => { root.render(React.createElement(I18nProvider, null, React.createElement(Fixture, { key: String(Math.random()) }))); }); }
await mount();
let count = requests.length;
await act(async () => { assert.equal(await current.submit("member_target", "   "), false); });
assert.equal(requests.length, count, "Blank reason sends zero request");
mode = "PENDING";
let submission: Promise<boolean>;
await act(async () => { submission = current.submit("member_target", "Coverage"); await Promise.resolve(); });
assert.equal(current.pending, true);
assert.equal(records[0].ownerId, undefined, "No optimistic ownership");
count = requests.length;
await act(async () => { assert.equal(await current.submit("member_target", "Coverage"), false); });
assert.equal(requests.length, count, "Double submit sends exactly one request");
await act(async () => { release?.(); await submission; });
assert.equal(records[0].ownerId, "member_target", "Server projection is authoritative");
assert.deepEqual(selection, ["lead_other"]);
assert.deepEqual(queue, ["lead_other"]);
assert.equal(refreshCount, 1);
const first = requests.find(input => input.operationId === "assignLeadOwner")!;
assert.deepEqual(first.body, { ownerId: "member_target", reason: "Coverage" });
assert.equal(first.path, `/leads/${document.id}/assign`);
assert.equal(first.expectedVersion, 5);
assert.ok(first.idempotencyKey);
await mount(); mode = "NETWORK";
await act(async () => { assert.equal(await current.submit("member_target", "Coverage"), false); });
const ambiguous = requests.at(-1)!;
assert.equal(current.ambiguous, true);
await act(async () => { await current.submit("member_target", "Coverage"); });
assert.equal(requests.at(-1)!.idempotencyKey, ambiguous.idempotencyKey);
assert.equal(requests.at(-1)!.expectedVersion, 5);
function VisibilityFixture({ open }: { open: boolean }) {
  current = useLeadOwnerAssign(mapLeadDocumentToApplication(document));
  return open ? React.createElement("span", null, "dialog") : null;
}
await act(async () => { root.render(React.createElement(VisibilityFixture, { open: true })); });
mode = "NETWORK";
await act(async () => { await current.submit("member_target", "Coverage"); });
const closedAttempt = requests.at(-1)!;
await act(async () => { root.render(React.createElement(VisibilityFixture, { open: false })); });
await act(async () => { root.render(React.createElement(VisibilityFixture, { open: true })); });
await act(async () => { await current.submit("member_target", "Coverage"); });
assert.equal(requests.at(-1)!.idempotencyKey, closedAttempt.idempotencyKey, "Close/reopen keeps ambiguous key");
assert.equal(requests.at(-1)!.expectedVersion, closedAttempt.expectedVersion, "Close/reopen keeps ambiguous version");
await mount(); mode = "VERSION"; version = 6;
count = requests.filter(input => input.operationId === "assignLeadOwner").length;
await act(async () => { await current.submit("member_target", "Coverage"); });
assert.equal(requests.filter(input => input.operationId === "assignLeadOwner").length, count + 1, "412 never automatically retries");
assert.equal(current.observed.resourceVersion, 6);
assert.equal(current.blocked, false);
const stale = requests.filter(input => input.operationId === "assignLeadOwner").at(-1)!;
mode = "SUCCESS";
await act(async () => { await current.submit("member_target", "Coverage"); });
const fresh = requests.filter(input => input.operationId === "assignLeadOwner").at(-1)!;
assert.equal(fresh.expectedVersion, 6);
assert.notEqual(fresh.idempotencyKey, stale.idempotencyKey);
for (const errorMode of ["DENIED", "HIDDEN", "INVALID"] as const) {
  await mount(); mode = errorMode;
  await act(async () => { assert.equal(await current.submit("member_target", "Coverage"), false); });
  assert.ok(current.error, `Typed ${errorMode} error retained for user presentation`);
}
const action = readFileSync("src/modules/leads/presentation/components/LeadOwnerAssignAction.tsx", "utf8");
assert.match(action, /allowedCommands.includes\("lead.assign-owner"\)/);
assert.match(action, /assignableOwners/);
assert.match(action, /getScopedTaskCollectionResource\(\{ filters: \{ recordModuleKey: "leads", recordId: lead.id \} \}\)/);
assert.match(action, /isOpen=\{open\}/);
assert.match(action, /task.status === "OPEN"/);
assert.match(action, /Open Tasks keep their assignee/);
assert.doesNotMatch(action, /reassignTask|createTask|updateTask|localStorage/);
const panel = readFileSync("src/modules/leads/presentation/components/LeadWorkPanel.tsx", "utf8");
assert.match(panel, /lg:w-\[350px\]/);
assert.match(panel, /LeadOwnerAssignAction lead=\{lead\}/);
const list = readFileSync("src/modules/leads/presentation/pages/LeadListPage.tsx", "utf8");
assert.match(list, /onAssigned=\{\(leadId\) => selection.toggleSelection\(leadId, false\)\}/);
assert.match(list, /refreshAfterAssign=\{serverPagination.refresh\}/);
const profile = readFileSync("src/modules/leads/presentation/components/LeadDetailModals.tsx", "utf8");
assert.match(profile, /canAssignOwner=\{false\}/);
const { configureTaskApplication } = await import("@/modules/tasks/application/composition/taskApplicationServices");
const { InMemoryTaskActivityRepository } = await import("@/modules/tasks/infrastructure/InMemoryTaskActivityRepository");
const { createTaskConnectedApiRuntime } = await import("@/modules/tasks/infrastructure/http/createTaskConnectedApiRuntime");
const taskRequests: HttpRequest[] = [];
const linkedTasks = ["OPEN", "COMPLETED", "CANCELLED"].map((status, index) => ({ id: `task_assign_${index}`, title: status, status, priority: "NORMAL", assigneeId: "member_previous", dueAt: "2099-01-01T00:00:00Z", createdAt: document.createdAt, updatedAt: document.updatedAt, recordRef: { moduleKey: "leads", recordId: document.id, label: document.displayName } }));
const taskClient: HttpClient = { async request<TResponse, TBody = unknown>(input: HttpRequest<TBody>): Promise<TResponse> {
  taskRequests.push(input);
  assert.equal(input.operationId, "listTasks", "Assign dialog only reads Tasks");
  return { items: linkedTasks, pageInfo: { hasNextPage: false } } as TResponse;
}};
configureTaskApplication({ repository: new InMemoryTaskActivityRepository({ tasks: [], activities: [] }), api: createTaskConnectedApiRuntime(taskClient) });
let releaseTasks: (() => void) | undefined;
const slowTaskClient: HttpClient = { async request<TResponse, TBody = unknown>(input: HttpRequest<TBody>): Promise<TResponse> {
  await new Promise<void>(resolve => { releaseTasks = resolve; });
  return taskClient.request<TResponse, TBody>(input);
}};
configureTaskApplication({ repository: new InMemoryTaskActivityRepository({ tasks: [], activities: [] }), api: createTaskConnectedApiRuntime(slowTaskClient) });
const taskBefore = JSON.stringify(linkedTasks);
await act(async () => { root.render(React.createElement(I18nProvider, null, React.createElement(LeadOwnerAssignDialog, { lead: mapLeadDocumentToApplication(document), onClose() {} }))); });
await act(async () => { await new Promise(resolve => setTimeout(resolve, 10)); });
await act(async () => { window.document.querySelector<HTMLButtonElement>("button[aria-haspopup=listbox]")!.click(); });
const targetOption = window.document.querySelector<HTMLButtonElement>("button[role=option]");
assert.ok(targetOption, "Assignable member candidates are rendered");
await act(async () => { targetOption.click(); });
const reasonControl = window.document.querySelector<HTMLTextAreaElement>("textarea")!;
await act(async () => {
  Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, "value")!.set!.call(reasonControl, "Coverage");
  reasonControl.dispatchEvent(new window.Event("input", { bubbles: true }));
});
assert.equal(window.document.querySelector<HTMLButtonElement>("button[type=submit]")?.disabled, true, "A completed draft cannot confirm before authoritative Task observation");
await act(async () => { releaseTasks?.(); await new Promise(resolve => setTimeout(resolve, 10)); });
assert.ok(window.document.querySelector("button[aria-haspopup=listbox]"), "Target selection rendered through shared searchable owner Select");
assert.ok(window.document.querySelector("textarea[required]"), "Reason required");
assert.equal(window.document.querySelector<HTMLButtonElement>("button[type=submit]")?.disabled, false, "Completed draft can confirm after Task observation; OPEN Tasks remain informational");
assert.match(window.document.body.textContent ?? "", /Các công việc đang mở giữ nguyên người thực hiện|Open Tasks keep their assignee/);
assert.equal(taskRequests[0].query?.recordModuleKey, "leads");
assert.equal(taskRequests[0].query?.recordId, document.id);
assert.equal(JSON.stringify(linkedTasks), taskBefore, "Task warning never mutates any status/assignee");
const { configureEffectiveRecordAccessAuthority, resetEffectiveRecordAccessAuthority } = await import("@/platform/access-control");
let holdAuthority = false;
let releaseAuthority: (() => void) | undefined;
configureEffectiveRecordAccessAuthority({ source: "backend", async evaluate(request) {
  if (holdAuthority) await new Promise<void>(resolve => { releaseAuthority = resolve; });
  return { workspaceId: request.workspaceId, resourceKey: "leads", recordId: request.recordId, canRead: true, canUpdate: false, canDelete: false, canExport: false, canApprove: false, allowedCommands: ["lead.assign-owner"], fieldAccess: { ownerId: "READ_WRITE" }, decisionReasons: [], evaluatedAt: document.updatedAt, authority: "backend" };
}});
configureTaskApplication({ repository: new InMemoryTaskActivityRepository({ tasks: [], activities: [] }), api: createTaskConnectedApiRuntime(taskClient) });
const actionLead = mapLeadDocumentToApplication(document);
const renderAction = async (lead = actionLead) => { await act(async () => { root.render(React.createElement(I18nProvider, null, React.createElement(LeadOwnerAssignAction, { lead }))); }); };
const openAction = async () => { const button = [...window.document.querySelectorAll<HTMLButtonElement>("button")].find(node => /Phân công|Assign owner/.test(node.textContent ?? "")); assert.ok(button); await act(async () => { button.click(); }); };
await renderAction();
await openAction();
await act(async () => { window.document.querySelector<HTMLButtonElement>("button[aria-haspopup=listbox]")!.click(); });
await act(async () => { window.document.querySelector<HTMLButtonElement>("button[role=option]")!.click(); });
await act(async () => {
  const textarea = window.document.querySelector<HTMLTextAreaElement>("textarea")!;
  Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype, "value")!.set!.call(textarea, "Coverage");
  textarea.dispatchEvent(new window.Event("input", { bubbles: true }));
});
mode = "NETWORK";
await act(async () => { window.document.querySelector("form")!.dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true })); });
const authorityRetry = requests.filter(input => input.operationId === "assignLeadOwner").at(-1)!;
holdAuthority = true;
await renderAction({ ...actionLead, name: "Refreshed same version" });
assert.equal(window.document.querySelector<HTMLButtonElement>("button[type=submit]")?.disabled, true, "Authority loading gates submission without unmounting the dialog");
holdAuthority = false;
await act(async () => { releaseAuthority?.(); });
const cancel = [...window.document.querySelectorAll<HTMLButtonElement>("button")].find(node => /^(Hủy|Cancel)$/.test(node.textContent ?? ""));
assert.ok(cancel);
await act(async () => { cancel.click(); });
await openAction();
await act(async () => { window.document.querySelector("form")!.dispatchEvent(new window.Event("submit", { bubbles: true, cancelable: true })); });
const actualRetry = requests.filter(input => input.operationId === "assignLeadOwner").at(-1)!;
assert.equal(actualRetry.idempotencyKey, authorityRetry.idempotencyKey, "Actual action preserves ambiguous key through authority refresh + close/reopen");
assert.equal(actualRetry.expectedVersion, authorityRetry.expectedVersion);
resetEffectiveRecordAccessAuthority();
await act(async () => { root.unmount(); });
console.log("Lead owner assign: PASS (transport, reason, pending, authoritative projection, selection/queue refresh, stable ambiguity retry, explicit 412 recovery, typed failures, task-neutral UI, future containment)");
