import type { Capability } from "./accessControl.types";

export const CAPABILITIES = {
  IDENTITY_AUTHENTICATE: "identity.authenticate",
  IDENTITY_SESSION_READ: "identity.session.read",
  IDENTITY_SESSION_REFRESH: "identity.session.refresh",
  IDENTITY_SESSION_REVOKE: "identity.session.revoke",
  IDENTITY_ACCOUNT_REGISTER: "identity.account.register",
  IDENTITY_ACCOUNT_VERIFY: "identity.account.verify",
  IDENTITY_ACCOUNT_RECOVER: "identity.account.recover",
  IDENTITY_INVITATION_ACCEPT: "identity.invitation.accept",
  WORKSPACE_MEMBERSHIP_LIST: "workspace.membership.list",
  WORKSPACE_CONTEXT_RESOLVE: "workspace.context.resolve",
  DASHBOARD_READ: "dashboard.read",
  LEADS_READ: "leads.read",
  LEADS_CREATE: "leads.create",
  LEADS_UPDATE: "leads.update",
  LEADS_DELETE: "leads.delete",
  LEADS_EXPORT: "leads.export",
  LEADS_BULK: "leads.bulk",
  LEADS_ASSIGN: "leads.assign",
  LEADS_QUALIFY: "leads.qualify",
  LEADS_CONVERT_TO_CUSTOMER: "leads.convert_to_customer",
  CONTACTS_READ: "contacts.read",
  CONTACTS_CREATE: "contacts.create",
  CONTACTS_UPDATE: "contacts.update",
  CONTACTS_DELETE: "contacts.delete",
  CONTACTS_EXPORT: "contacts.export",
  CONTACTS_BULK: "contacts.bulk",
  CONTACTS_ASSIGN: "contacts.assign",
  ORGANIZATIONS_READ: "organizations.read",
  ORGANIZATIONS_CREATE: "organizations.create",
  ORGANIZATIONS_UPDATE: "organizations.update",
  ORGANIZATIONS_DELETE: "organizations.delete",
  TASKS_READ: "tasks.read",
  TASKS_CREATE: "tasks.create",
  TASKS_UPDATE: "tasks.update",
  TASKS_ASSIGN: "tasks.assign",
  TASKS_COMPLETE: "tasks.complete",
  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_CREATE_SYSTEM: "customers.create_system",
  CUSTOMERS_ONBOARD_EXISTING: "customers.onboard_existing",
  CUSTOMERS_EDIT: "customers.edit",
  CUSTOMERS_ASSIGN: "customers.assign",
  CUSTOMERS_ARCHIVE: "customers.archive",
  DEALS_READ: "deals.read",
  DEALS_CREATE: "deals.create",
  DEALS_UPDATE: "deals.update",
  DEALS_DELETE: "deals.delete",
  DEALS_EXPORT: "deals.export",
  DEALS_BULK: "deals.bulk",
  DEALS_ASSIGN: "deals.assign",
  DEALS_CLOSE: "deals.close",
  QUOTES_READ: "quotes.read",
  QUOTES_CREATE: "quotes.create",
  QUOTES_UPDATE: "quotes.update",
  QUOTES_DELETE: "quotes.delete",
  QUOTES_EXPORT: "quotes.export",
  QUOTES_APPROVE: "quotes.approve",
  ORDERS_READ: "orders.read",
  ORDERS_CREATE: "orders.create",
  ORDERS_UPDATE: "orders.update",
  ORDERS_DELETE: "orders.delete",
  ORDERS_EXPORT: "orders.export",
  ORDERS_BULK: "orders.bulk",
  ORDERS_CONFIRM: "orders.confirm",
  ORDERS_COMPLETE: "orders.complete",
  ORDERS_CREDIT_APPROVAL_REQUEST: "orders.credit_approval.request",
  ORDERS_CREDIT_APPROVAL_DECIDE: "orders.credit_approval.decide",
  PRODUCTS_READ: "products.read",
  PRODUCTS_EDIT: "products.edit",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_EXPORT: "products.export",
  PRODUCTS_CONFIGURE: "products.configure",
  SUPPORT_READ: "support.read",
  SUPPORT_CREATE: "support.create",
  SUPPORT_UPDATE: "support.update",
  SUPPORT_DELETE: "support.delete",
  SUPPORT_EXPORT: "support.export",
  SUPPORT_ASSIGN: "support.assign",
  SUPPORT_COMPLETE: "support.complete",
  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",
  PAYMENTS_READ: "payments.read",
  PAYMENTS_RECORD: "payments.record",
  PAYMENTS_REFUND: "payments.refund",
  PAYMENTS_RECONCILE: "payments.reconcile",
  PAYMENTS_PLAN_READ: "payments.plan.read",
  PAYMENTS_PLAN_CREATE: "payments.plan.create",
  PAYMENTS_PLAN_UPDATE_DRAFT: "payments.plan.update_draft",
  PAYMENTS_PLAN_ACTIVATE: "payments.plan.activate",
  PAYMENTS_PLAN_SUPERSEDE: "payments.plan.supersede",
  PAYMENTS_INTENT_CREATE: "payments.intent.create",
  PAYMENTS_INTENT_CANCEL: "payments.intent.cancel",
  PAYMENTS_RECORD_MANUAL: "payments.record_manual",
  PAYMENTS_ALLOCATE: "payments.allocate",
  PAYMENTS_REVERSE_ALLOCATION: "payments.reverse_allocation",
  PAYMENTS_CUSTOMER_CREDIT_READ: "payments.customer_credit.read",
  PAYMENTS_CUSTOMER_CREDIT_ALLOCATE: "payments.customer_credit.allocate",
  INVOICES_READ: "invoices.read",
  INVOICES_CREATE: "invoices.create",
  INVOICES_EDIT: "invoices.edit",
  INVOICES_UPDATE_DRAFT: "invoices.update_draft",
  INVOICES_ISSUE: "invoices.issue",
  INVOICES_RETRY_ISSUE: "invoices.retry_issue",
  INVOICES_SEND: "invoices.send",
  INVOICES_CREATE_CREDIT_NOTE: "invoices.create_credit_note",
  INVOICES_DISCARD_DRAFT: "invoices.discard_draft",
  INVOICES_VOID: "invoices.void",
  RECEIVABLES_READ: "receivables.read",
  RECEIVABLES_EXPORT: "receivables.export",
  RETURNS_READ: "returns.read",
  RETURNS_CREATE: "returns.create",
  RETURNS_UPDATE: "returns.update",
  RETURNS_APPROVE: "returns.approve",
  RETURNS_RESOLVE: "returns.resolve",
  SHIPPING_READ: "shipping.read",
  SHIPPING_CREATE: "shipping.create",
  SHIPPING_RETRY: "shipping.retry",
  SHIPPING_CANCEL: "shipping.cancel",
  SHIPPING_SYNC: "shipping.sync",
  SHIPPING_MANAGE_PROVIDERS: "shipping.manageProviders",
  STUDIO_READ: "studio.read",
  STUDIO_CONFIGURE: "studio.configure",
  ACCESS_READ: "access.read",
  ACCESS_CONFIGURE: "access.configure",
  AUDIT_READ: "audit.read",
  AUDIT_CONFIGURE: "audit.configure",
} as const satisfies Record<string, Capability>;

export const ALL_CAPABILITIES: Capability[] = Object.values(CAPABILITIES);

// Backend-authoritative projection of Workspace-scoped capabilities consumed by operations that
// are currently production-contract ready. ALL_CAPABILITIES remains the UI vocabulary catalog;
// it must never be used as a role grant.
export const SERVER_ADMITTED_WORKSPACE_CAPABILITIES: readonly Capability[] = [
  CAPABILITIES.ACCESS_CONFIGURE, CAPABILITIES.ACCESS_READ,
  CAPABILITIES.CONTACTS_CREATE, CAPABILITIES.CONTACTS_DELETE, CAPABILITIES.CONTACTS_READ, CAPABILITIES.CONTACTS_UPDATE, CAPABILITIES.CUSTOMERS_VIEW,
  CAPABILITIES.DEALS_ASSIGN, CAPABILITIES.DEALS_BULK, CAPABILITIES.DEALS_CLOSE, CAPABILITIES.DEALS_CREATE, CAPABILITIES.DEALS_DELETE, CAPABILITIES.DEALS_READ, CAPABILITIES.DEALS_UPDATE,
  CAPABILITIES.INVOICES_CREATE, CAPABILITIES.INVOICES_CREATE_CREDIT_NOTE, CAPABILITIES.INVOICES_EDIT, CAPABILITIES.INVOICES_ISSUE, CAPABILITIES.INVOICES_READ, CAPABILITIES.INVOICES_SEND, CAPABILITIES.INVOICES_UPDATE_DRAFT, CAPABILITIES.INVOICES_VOID,
  CAPABILITIES.LEADS_ASSIGN, CAPABILITIES.LEADS_BULK, CAPABILITIES.LEADS_CREATE, CAPABILITIES.LEADS_DELETE, CAPABILITIES.LEADS_EXPORT, CAPABILITIES.LEADS_QUALIFY, CAPABILITIES.LEADS_READ, CAPABILITIES.LEADS_UPDATE,
  CAPABILITIES.ORDERS_COMPLETE, CAPABILITIES.ORDERS_CONFIRM, CAPABILITIES.ORDERS_CREATE, CAPABILITIES.ORDERS_CREDIT_APPROVAL_DECIDE, CAPABILITIES.ORDERS_CREDIT_APPROVAL_REQUEST, CAPABILITIES.ORDERS_DELETE, CAPABILITIES.ORDERS_READ, CAPABILITIES.ORDERS_UPDATE,
  CAPABILITIES.ORGANIZATIONS_READ,
  CAPABILITIES.PAYMENTS_ALLOCATE, CAPABILITIES.PAYMENTS_INTENT_CANCEL, CAPABILITIES.PAYMENTS_INTENT_CREATE, CAPABILITIES.PAYMENTS_PLAN_ACTIVATE, CAPABILITIES.PAYMENTS_PLAN_READ, CAPABILITIES.PAYMENTS_PLAN_SUPERSEDE, CAPABILITIES.PAYMENTS_PLAN_UPDATE_DRAFT, CAPABILITIES.PAYMENTS_READ, CAPABILITIES.PAYMENTS_RECONCILE, CAPABILITIES.PAYMENTS_RECORD_MANUAL, CAPABILITIES.PAYMENTS_REFUND, CAPABILITIES.PAYMENTS_REVERSE_ALLOCATION,
  CAPABILITIES.PRODUCTS_CREATE, CAPABILITIES.PRODUCTS_DELETE, CAPABILITIES.PRODUCTS_EDIT, CAPABILITIES.PRODUCTS_READ,
  CAPABILITIES.QUOTES_APPROVE, CAPABILITIES.QUOTES_CREATE, CAPABILITIES.QUOTES_DELETE, CAPABILITIES.QUOTES_READ, CAPABILITIES.QUOTES_UPDATE,
  CAPABILITIES.RECEIVABLES_READ,
  CAPABILITIES.RETURNS_READ, CAPABILITIES.RETURNS_RESOLVE, CAPABILITIES.RETURNS_UPDATE,
  CAPABILITIES.SHIPPING_CREATE, CAPABILITIES.SHIPPING_READ,
  CAPABILITIES.STUDIO_CONFIGURE, CAPABILITIES.STUDIO_READ,
  CAPABILITIES.SUPPORT_ASSIGN, CAPABILITIES.SUPPORT_CREATE, CAPABILITIES.SUPPORT_READ, CAPABILITIES.SUPPORT_UPDATE,
  CAPABILITIES.TASKS_ASSIGN, CAPABILITIES.TASKS_COMPLETE, CAPABILITIES.TASKS_CREATE, CAPABILITIES.TASKS_READ, CAPABILITIES.TASKS_UPDATE,
  CAPABILITIES.WORKSPACE_CONTEXT_RESOLVE,
];

const READ_CAPABILITY_BY_MODULE: Record<string, Capability> = {
  dashboard: CAPABILITIES.DASHBOARD_READ,
  leads: CAPABILITIES.LEADS_READ,
  lead: CAPABILITIES.LEADS_READ,
  contacts: CAPABILITIES.CONTACTS_READ,
  organizations: CAPABILITIES.ORGANIZATIONS_READ,
  organizationAccounts: CAPABILITIES.ORGANIZATIONS_READ,
  tasks: CAPABILITIES.TASKS_READ,
  customers: CAPABILITIES.CUSTOMERS_VIEW,
  customer: CAPABILITIES.CUSTOMERS_VIEW,
  deals: CAPABILITIES.DEALS_READ,
  deal: CAPABILITIES.DEALS_READ,
  quotes: CAPABILITIES.QUOTES_READ,
  quote: CAPABILITIES.QUOTES_READ,
  orders: CAPABILITIES.ORDERS_READ,
  order: CAPABILITIES.ORDERS_READ,
  products: CAPABILITIES.PRODUCTS_READ,
  catalog: CAPABILITIES.PRODUCTS_READ,
  support: CAPABILITIES.SUPPORT_READ,
  reports: CAPABILITIES.REPORTS_READ,
  payments: CAPABILITIES.PAYMENTS_READ,
  invoices: CAPABILITIES.INVOICES_READ,
  receivables: CAPABILITIES.RECEIVABLES_READ,
  returns: CAPABILITIES.RETURNS_READ,
  shipping: CAPABILITIES.SHIPPING_READ,
  systemConfiguration: CAPABILITIES.STUDIO_READ,
  businessWorkflows: CAPABILITIES.STUDIO_READ,
  fieldsLayouts: CAPABILITIES.STUDIO_READ,
  productConfiguration: CAPABILITIES.STUDIO_READ,
  templatesNumbering: CAPABILITIES.STUDIO_READ,
  automationNotifications: CAPABILITIES.STUDIO_READ,
  usersPermissions: CAPABILITIES.ACCESS_READ,
  auditLogs: CAPABILITIES.AUDIT_READ,
};

const ACTION_ALIASES: Record<string, string> = {
  view: "read",
  edit: "update",
  configure: "configure",
  approve: "approve",
  complete: "complete",
  assign: "assign",
  export: "export",
  bulk: "bulk",
  create: "create",
  delete: "delete",
  qualify: "qualify",
  close: "close",
  confirm: "confirm",
};

const RESOURCE_PREFIX: Record<string, string> = {
  lead: "leads", leads: "leads",
  contact: "contacts", contacts: "contacts",
  organization: "organizations", organizations: "organizations", organizationAccounts: "organizations",
  task: "tasks", tasks: "tasks",
  customer: "customers", customers: "customers",
  deal: "deals", deals: "deals",
  quote: "quotes", quotes: "quotes",
  order: "orders", orders: "orders",
  product: "products", products: "products", catalog: "products",
  support: "support",
  report: "reports", reports: "reports",
  payments: "payments", payment: "payments",
  invoice: "invoices", invoices: "invoices",
  receivable: "receivables", receivables: "receivables",
  return: "returns", returns: "returns",
  shipping: "shipping",
  systemConfiguration: "studio", businessWorkflows: "studio", fieldsLayouts: "studio", productConfiguration: "studio", templatesNumbering: "studio", automationNotifications: "studio", settings: "studio",
  usersPermissions: "access", access: "access",
  auditLogs: "audit", audit: "audit",
  dashboard: "dashboard",
};

export function readCapabilityForModule(moduleKey: string): Capability | undefined {
  return READ_CAPABILITY_BY_MODULE[moduleKey];
}

export function capabilityForAction(moduleKey: string, action: string): Capability | undefined {
  const prefix = RESOURCE_PREFIX[moduleKey] || moduleKey;
  const suffix = ACTION_ALIASES[action] || action;
  return `${prefix}.${suffix}`;
}
