import { CAPABILITIES, SERVER_ADMITTED_WORKSPACE_CAPABILITIES } from "./capabilityCatalog";
import type { Capability, RoleTemplate } from "./accessControl.types";

const CRM_READ: Capability[] = [
  CAPABILITIES.DASHBOARD_READ,
  CAPABILITIES.LEADS_READ,
  CAPABILITIES.CONTACTS_READ,
  CAPABILITIES.ORGANIZATIONS_READ,
  CAPABILITIES.TASKS_READ,
  CAPABILITIES.CUSTOMERS_VIEW,
  CAPABILITIES.DEALS_READ,
  CAPABILITIES.QUOTES_READ,
  CAPABILITIES.ORDERS_READ,
  CAPABILITIES.PRODUCTS_READ,
  CAPABILITIES.SUPPORT_READ,
  CAPABILITIES.REPORTS_READ,
  CAPABILITIES.PAYMENTS_READ,
  CAPABILITIES.INVOICES_READ,
  CAPABILITIES.RECEIVABLES_READ,
  CAPABILITIES.RETURNS_READ,
  CAPABILITIES.SHIPPING_READ,
];

const SALES_MANAGER_CAPABILITIES: Capability[] = [
  ...CRM_READ,
  CAPABILITIES.LEADS_CREATE, CAPABILITIES.LEADS_UPDATE, CAPABILITIES.LEADS_DELETE, CAPABILITIES.LEADS_EXPORT, CAPABILITIES.LEADS_BULK, CAPABILITIES.LEADS_ASSIGN, CAPABILITIES.LEADS_QUALIFY,
  CAPABILITIES.CONTACTS_CREATE, CAPABILITIES.CONTACTS_UPDATE, CAPABILITIES.CONTACTS_EXPORT, CAPABILITIES.CONTACTS_BULK, CAPABILITIES.CONTACTS_ASSIGN,
  CAPABILITIES.ORGANIZATIONS_CREATE, CAPABILITIES.ORGANIZATIONS_UPDATE,
  CAPABILITIES.TASKS_CREATE, CAPABILITIES.TASKS_UPDATE, CAPABILITIES.TASKS_ASSIGN, CAPABILITIES.TASKS_COMPLETE,
  CAPABILITIES.CUSTOMERS_ONBOARD_EXISTING, CAPABILITIES.CUSTOMERS_EDIT, CAPABILITIES.CUSTOMERS_ASSIGN, CAPABILITIES.CUSTOMERS_ARCHIVE,
  CAPABILITIES.DEALS_CREATE, CAPABILITIES.DEALS_UPDATE, CAPABILITIES.DEALS_EXPORT, CAPABILITIES.DEALS_BULK, CAPABILITIES.DEALS_ASSIGN, CAPABILITIES.DEALS_CLOSE,
  CAPABILITIES.QUOTES_CREATE, CAPABILITIES.QUOTES_UPDATE, CAPABILITIES.QUOTES_EXPORT, CAPABILITIES.QUOTES_APPROVE,
  CAPABILITIES.ORDERS_CREATE, CAPABILITIES.ORDERS_UPDATE, CAPABILITIES.ORDERS_EXPORT, CAPABILITIES.ORDERS_BULK, CAPABILITIES.ORDERS_CONFIRM, CAPABILITIES.ORDERS_COMPLETE, CAPABILITIES.ORDERS_CREDIT_APPROVAL_REQUEST,
  CAPABILITIES.PAYMENTS_RECORD, CAPABILITIES.PAYMENTS_REFUND, CAPABILITIES.PAYMENTS_RECONCILE,
  CAPABILITIES.PAYMENTS_PLAN_CREATE, CAPABILITIES.PAYMENTS_PLAN_UPDATE_DRAFT, CAPABILITIES.PAYMENTS_PLAN_ACTIVATE, CAPABILITIES.PAYMENTS_PLAN_SUPERSEDE,
  CAPABILITIES.PAYMENTS_INTENT_CREATE, CAPABILITIES.PAYMENTS_RECORD_MANUAL, CAPABILITIES.PAYMENTS_ALLOCATE,
  CAPABILITIES.INVOICES_CREATE, CAPABILITIES.INVOICES_UPDATE_DRAFT,
  CAPABILITIES.SHIPPING_CREATE, CAPABILITIES.SHIPPING_RETRY, CAPABILITIES.SHIPPING_CANCEL, CAPABILITIES.SHIPPING_SYNC,
  CAPABILITIES.RETURNS_CREATE, CAPABILITIES.RETURNS_UPDATE, CAPABILITIES.RETURNS_APPROVE, CAPABILITIES.RETURNS_RESOLVE,
  CAPABILITIES.REPORTS_EXPORT,
];

const SALES_REP_CAPABILITIES: Capability[] = [
  ...CRM_READ,
  CAPABILITIES.LEADS_CREATE, CAPABILITIES.LEADS_UPDATE, CAPABILITIES.LEADS_DELETE, CAPABILITIES.LEADS_QUALIFY,
  CAPABILITIES.CONTACTS_CREATE, CAPABILITIES.CONTACTS_UPDATE,
  CAPABILITIES.ORGANIZATIONS_CREATE, CAPABILITIES.ORGANIZATIONS_UPDATE,
  CAPABILITIES.TASKS_CREATE, CAPABILITIES.TASKS_UPDATE, CAPABILITIES.TASKS_ASSIGN, CAPABILITIES.TASKS_COMPLETE,
  CAPABILITIES.CUSTOMERS_EDIT,
  CAPABILITIES.DEALS_CREATE, CAPABILITIES.DEALS_UPDATE, CAPABILITIES.DEALS_CLOSE,
  CAPABILITIES.QUOTES_CREATE, CAPABILITIES.QUOTES_UPDATE,
  CAPABILITIES.ORDERS_CREATE, CAPABILITIES.ORDERS_UPDATE, CAPABILITIES.ORDERS_CONFIRM, CAPABILITIES.ORDERS_CREDIT_APPROVAL_REQUEST,
];

const CUSTOMER_SUCCESS_CAPABILITIES: Capability[] = [
  CAPABILITIES.DASHBOARD_READ, CAPABILITIES.CONTACTS_READ, CAPABILITIES.CONTACTS_UPDATE,
  CAPABILITIES.ORGANIZATIONS_READ, CAPABILITIES.CUSTOMERS_VIEW, CAPABILITIES.CUSTOMERS_ONBOARD_EXISTING, CAPABILITIES.CUSTOMERS_EDIT, CAPABILITIES.CUSTOMERS_ASSIGN, CAPABILITIES.CUSTOMERS_ARCHIVE,
  CAPABILITIES.DEALS_READ, CAPABILITIES.QUOTES_READ, CAPABILITIES.ORDERS_READ,
  CAPABILITIES.PRODUCTS_READ, CAPABILITIES.SUPPORT_READ, CAPABILITIES.SUPPORT_CREATE, CAPABILITIES.SUPPORT_UPDATE,
  CAPABILITIES.TASKS_READ, CAPABILITIES.TASKS_CREATE, CAPABILITIES.TASKS_UPDATE, CAPABILITIES.TASKS_COMPLETE,
  CAPABILITIES.PAYMENTS_READ, CAPABILITIES.INVOICES_READ, CAPABILITIES.RECEIVABLES_READ, CAPABILITIES.SHIPPING_READ,
  CAPABILITIES.RETURNS_READ, CAPABILITIES.RETURNS_CREATE, CAPABILITIES.RETURNS_UPDATE, CAPABILITIES.RETURNS_APPROVE, CAPABILITIES.RETURNS_RESOLVE,
  CAPABILITIES.REPORTS_READ,
];


const FINANCE_CAPABILITIES: Capability[] = [
  CAPABILITIES.DASHBOARD_READ,
  CAPABILITIES.CONTACTS_READ, CAPABILITIES.ORGANIZATIONS_READ, CAPABILITIES.CUSTOMERS_VIEW,
  CAPABILITIES.DEALS_READ, CAPABILITIES.QUOTES_READ, CAPABILITIES.ORDERS_READ, CAPABILITIES.ORDERS_CREDIT_APPROVAL_DECIDE, CAPABILITIES.PRODUCTS_READ,
  CAPABILITIES.PAYMENTS_READ, CAPABILITIES.PAYMENTS_RECORD, CAPABILITIES.PAYMENTS_REFUND, CAPABILITIES.PAYMENTS_RECONCILE,
  CAPABILITIES.PAYMENTS_PLAN_READ, CAPABILITIES.PAYMENTS_PLAN_CREATE, CAPABILITIES.PAYMENTS_PLAN_UPDATE_DRAFT, CAPABILITIES.PAYMENTS_PLAN_ACTIVATE, CAPABILITIES.PAYMENTS_PLAN_SUPERSEDE,
  CAPABILITIES.PAYMENTS_INTENT_CREATE, CAPABILITIES.PAYMENTS_INTENT_CANCEL, CAPABILITIES.PAYMENTS_RECORD_MANUAL, CAPABILITIES.PAYMENTS_ALLOCATE, CAPABILITIES.PAYMENTS_REVERSE_ALLOCATION,
  CAPABILITIES.PAYMENTS_CUSTOMER_CREDIT_READ, CAPABILITIES.PAYMENTS_CUSTOMER_CREDIT_ALLOCATE,
  CAPABILITIES.INVOICES_READ, CAPABILITIES.INVOICES_CREATE, CAPABILITIES.INVOICES_UPDATE_DRAFT, CAPABILITIES.INVOICES_ISSUE, CAPABILITIES.INVOICES_RETRY_ISSUE, CAPABILITIES.INVOICES_SEND, CAPABILITIES.INVOICES_CREATE_CREDIT_NOTE, CAPABILITIES.INVOICES_DISCARD_DRAFT, CAPABILITIES.INVOICES_VOID,
  CAPABILITIES.RECEIVABLES_READ, CAPABILITIES.RECEIVABLES_EXPORT,
  CAPABILITIES.SHIPPING_READ, CAPABILITIES.RETURNS_READ,
  CAPABILITIES.TASKS_READ, CAPABILITIES.TASKS_CREATE, CAPABILITIES.TASKS_UPDATE, CAPABILITIES.TASKS_COMPLETE,
  CAPABILITIES.REPORTS_READ, CAPABILITIES.REPORTS_EXPORT,
];

const OPERATIONS_CAPABILITIES: Capability[] = [
  CAPABILITIES.DASHBOARD_READ,
  CAPABILITIES.CONTACTS_READ, CAPABILITIES.ORGANIZATIONS_READ, CAPABILITIES.CUSTOMERS_VIEW,
  CAPABILITIES.ORDERS_READ, CAPABILITIES.ORDERS_UPDATE, CAPABILITIES.ORDERS_CONFIRM, CAPABILITIES.ORDERS_COMPLETE, CAPABILITIES.ORDERS_CREDIT_APPROVAL_REQUEST, CAPABILITIES.PRODUCTS_READ,
  CAPABILITIES.PAYMENTS_READ, CAPABILITIES.INVOICES_READ, CAPABILITIES.RECEIVABLES_READ,
  CAPABILITIES.SHIPPING_READ, CAPABILITIES.SHIPPING_CREATE, CAPABILITIES.SHIPPING_RETRY, CAPABILITIES.SHIPPING_CANCEL, CAPABILITIES.SHIPPING_SYNC,
  CAPABILITIES.RETURNS_READ, CAPABILITIES.RETURNS_CREATE, CAPABILITIES.RETURNS_UPDATE, CAPABILITIES.RETURNS_APPROVE, CAPABILITIES.RETURNS_RESOLVE,
  CAPABILITIES.SUPPORT_READ,
  CAPABILITIES.TASKS_READ, CAPABILITIES.TASKS_CREATE, CAPABILITIES.TASKS_UPDATE, CAPABILITIES.TASKS_ASSIGN, CAPABILITIES.TASKS_COMPLETE,
  CAPABILITIES.REPORTS_READ,
];

const SUPPORT_CAPABILITIES: Capability[] = [
  CAPABILITIES.DASHBOARD_READ, CAPABILITIES.CONTACTS_READ, CAPABILITIES.ORGANIZATIONS_READ,
  CAPABILITIES.CUSTOMERS_VIEW, CAPABILITIES.ORDERS_READ, CAPABILITIES.PRODUCTS_READ,
  CAPABILITIES.SUPPORT_READ, CAPABILITIES.SUPPORT_CREATE, CAPABILITIES.SUPPORT_UPDATE, CAPABILITIES.SUPPORT_ASSIGN, CAPABILITIES.SUPPORT_COMPLETE,
  CAPABILITIES.TASKS_READ, CAPABILITIES.TASKS_CREATE, CAPABILITIES.TASKS_UPDATE, CAPABILITIES.TASKS_COMPLETE,
  CAPABILITIES.RETURNS_READ, CAPABILITIES.RETURNS_CREATE, CAPABILITIES.RETURNS_UPDATE,
];

const SERVER_ADMITTED_CAPABILITY_SET = new Set<Capability>(SERVER_ADMITTED_WORKSPACE_CAPABILITIES);
const admitted = (capabilities: readonly Capability[]): Capability[] =>
  [...new Set(capabilities.filter((capability) => SERVER_ADMITTED_CAPABILITY_SET.has(capability)))];

export const ROLE_TEMPLATES: readonly RoleTemplate[] = [
  { templateId: "workspace-administrator", name: "Workspace Administrator", description: "Full workspace administration. Keep at least one active assignment with access.configure.", capabilities: [...SERVER_ADMITTED_WORKSPACE_CAPABILITIES], defaultScope: "WORKSPACE" },
  { templateId: "sales-manager", name: "Sales Manager", description: "Manage a sales team, pipeline, quotes, orders, and reporting.", capabilities: admitted(SALES_MANAGER_CAPABILITIES), defaultScope: "TEAM" },
  { templateId: "sales-representative", name: "Sales Representative", description: "Work assigned leads, contacts, deals, quotes, and orders.", capabilities: admitted(SALES_REP_CAPABILITIES), defaultScope: "OWN" },
  { templateId: "finance", name: "Finance", description: "Manage payment records, reconciliation, refunds, and financial reporting.", capabilities: admitted(FINANCE_CAPABILITIES), defaultScope: "WORKSPACE" },
  { templateId: "operations", name: "Operations", description: "Manage confirmed orders, shipping, delivery exceptions, and returns.", capabilities: admitted(OPERATIONS_CAPABILITIES), defaultScope: "TEAM" },
  { templateId: "customer-success", name: "Customer Success", description: "Manage customer relationships, care cases, tasks, and returns.", capabilities: admitted(CUSTOMER_SUCCESS_CAPABILITIES), defaultScope: "TEAM" },
  { templateId: "support", name: "Support", description: "Handle care cases, tasks, and return intake.", capabilities: admitted(SUPPORT_CAPABILITIES), defaultScope: "TEAM" },
  { templateId: "viewer", name: "Viewer", description: "Read-only CRM access. Narrow data scope before assigning broadly.", capabilities: admitted(CRM_READ), defaultScope: "OWN" },
] as const;

export function getRoleTemplate(templateId: string): RoleTemplate | undefined {
  return ROLE_TEMPLATES.find((template) => template.templateId === templateId);
}
