import { runBackendProjection, createMutationMetadata, executeMutationCommand as executeSharedMutationCommand, readMutationVersion, MutationCommandError, type BackendMutationCommand, type LocalMutationExecutor, type MutationCommandMetadata, type MutationOutcome } from "@/shared/application";
import { relationshipRefKey } from "@/platform/identity";
import type { CustomerOrder } from "../domain/model/order.types";
import { OrderState } from "../domain/model/order.types";
import type { OrderStateDefinition } from "../domain/rules/orderLifecycle";
import type { OrderCollection } from "../application/ports/OrderRepository";
import type { DirectOrderDraftAuthorityResult, OrderMutationEvidence } from "../application/ports/OrderApiRuntime";
import { archiveOrder, archiveOrders, updateOrderCollection, type OrderCollectionUpdater, saveOrder } from "../application/commands/orderRepositoryCommands";
import { cancelOrderCommand, completeOrderCommand, confirmOrderCommand, recordOrderDelivery, transitionOrderState } from "../application/commands/orderCommands";
import { getOrderApiRuntime, isOrderConnectedApiRuntime, orderPreferences, orderRepository } from "../application/composition/orderApplicationServices";

export function getOrdersSnapshot(): OrderCollection { return orderRepository.snapshot(); }
export function getOrderListSnapshot(): CustomerOrder[] { return orderRepository.list(); }
export function getOrderSnapshot(orderId: string): CustomerOrder | undefined { return orderRepository.getById(orderId); }
export function replaceOrders(orders: OrderCollection): void { orderRepository.replace(orders); }
export function replaceOrderList(orders: readonly CustomerOrder[]): void { const next: OrderCollection = {}; for (const order of orders) { const key = relationshipRefKey(order.buyerRef); next[key] = [...(next[key] ?? []), structuredClone(order)]; } orderRepository.replace(next); }
export function updateOrders(updater: OrderCollectionUpdater): OrderCollection { return updateOrderCollection(orderRepository, updater); }
export function saveOrderSnapshot(order: CustomerOrder): CustomerOrder { assertDemoOrderMutationAllowed("saveOrderSnapshot"); return saveOrder(orderRepository, order); }
export type OrderLifecycleMutationMetadata = Partial<MutationCommandMetadata>;
export function isOrderConnectedMode(): boolean { return isOrderConnectedApiRuntime(); }

export async function createDirectOrderDraftCommandBoundary(order: CustomerOrder, metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<DirectOrderDraftAuthorityResult>> { const commandMetadata = createMutationMetadata(`order.create:${order.id || order.orderNumber}`, metadata); const result = await getOrderApiRuntime().commands.createDraft(order, commandOptions(commandMetadata)); projectAuthoritativeOrderResult(result.order); return { ...orderOutcome("order.create", commandMetadata, result.order, result.evidence), data: result }; }
export async function saveOrderDraftCommand(order: CustomerOrder, metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { const current = getOrderSnapshot(order.id); const commandType = current ? "order.update-draft" : "order.create"; const commandMetadata = createMutationMetadata(`${commandType}:${order.id || order.orderNumber}`, metadata); const result = current ? await getOrderApiRuntime().commands.replaceDraft(current.id, order, versionedOptions(current.id, commandMetadata, "update-draft")) : await getOrderApiRuntime().commands.createDraft(order, commandOptions(commandMetadata)); projectAuthoritativeOrderResult(result.order); return orderOutcome(commandType, commandMetadata, result.order, result.evidence); }
export async function repriceOrderDraftCommand(orderId: string, metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { const commandMetadata = createMutationMetadata(`order.reprice-draft:${orderId}`, metadata); const result = await getOrderApiRuntime().commands.repriceDraft(orderId, versionedOptions(orderId, commandMetadata, "reprice-draft")); projectAuthoritativeOrderResult(result.order); return orderOutcome("order.reprice-draft", commandMetadata, result.order, result.evidence); }
export async function duplicateOrderDraftCommand(orderId: string, title?: string, metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { const commandMetadata = createMutationMetadata(`order.duplicate-draft:${orderId}`, metadata); const result = await getOrderApiRuntime().commands.duplicateDraft(orderId, title, versionedOptions(orderId, commandMetadata, "duplicate-draft")); projectAuthoritativeOrderResult(result.order); return orderOutcome("order.duplicate-draft", commandMetadata, result.order, result.evidence); }

export async function archiveOrderCommandBoundary(orderId: string, input: Parameters<typeof archiveOrder>[2], metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { const commandMetadata = createMutationMetadata(`order.archive:${orderId}`, { ...metadata, actor: metadata.actor ?? { id: input.actorId, name: input.actorName } }); const result = await getOrderApiRuntime().commands.archive(orderId, input.reason, versionedOptions(orderId, commandMetadata, "archive")); projectAuthoritativeOrderResult(result.order); return orderOutcome("order.archive", commandMetadata, result.order, result.evidence); }
export async function archiveOrdersCommandBoundary(orderIds: readonly string[], input: Parameters<typeof archiveOrders>[2], metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder[]>> { const aggregateId = [...orderIds].sort().join(","); const commandMetadata = createMutationMetadata(`order.archive-many:${aggregateId}`, { ...metadata, actor: metadata.actor ?? { id: input.actorId, name: input.actorName } }); const items = orderIds.map((orderId) => ({ orderId, expectedVersion: requireOrderVersion(orderId, "archive-many") })); const result = await getOrderApiRuntime().commands.archiveBatch(items, input.reason, commandOptions(commandMetadata)); projectAuthoritativeOrderResult([...result.orders]); return orderBatchOutcome("order.archive-many", commandMetadata, result.orders, result.evidence); }

export function changeOrderStateCommand(orderId: string, state: OrderState, definitions?: readonly OrderStateDefinition[], now?: string, metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { return executeOrderMutation({ commandType: "order.change-state", aggregateType: "order", aggregateId: orderId, payload: { state, now } }, createMutationMetadata(`order.change-state:${orderId}`, withOrderVersion(orderId, metadata)), () => { const result = transitionOrderState(orderRepository, orderId, state, definitions, now); if (!result.success) throw new Error(result.message || "ORDER_TRANSITION_FAILED"); return requireOrderResult(orderId); }); }
export function confirmOrderCommandBoundary(orderId: string, now?: string, metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { return executeOrderMutation({ commandType: "order.confirm", aggregateType: "order", aggregateId: orderId, payload: { now } }, createMutationMetadata(`order.confirm:${orderId}`, withOrderVersion(orderId, metadata)), () => { const result = confirmOrderCommand(orderRepository, orderId, now); if (!result.success || !result.order) throw new Error(result.message || "ORDER_CONFIRMATION_FAILED"); return result.order; }); }
export function cancelOrderCommandBoundary(orderId: string, input: Parameters<typeof cancelOrderCommand>[2], now?: string, metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { return executeOrderMutation({ commandType: "order.cancel", aggregateType: "order", aggregateId: orderId, payload: { ...input, now } }, createMutationMetadata(`order.cancel:${orderId}`, { ...withOrderVersion(orderId, metadata), actor: metadata.actor ?? { id: input.actorId, name: input.actorName } }), () => { const result = cancelOrderCommand(orderRepository, orderId, input, now); if (!result.success) throw new Error(result.message || "ORDER_CANCELLATION_FAILED"); return requireOrderResult(orderId); }); }
export async function recordOrderDeliveryCommandBoundary(orderId: string, input: Parameters<typeof recordOrderDelivery>[2], metadata: OrderLifecycleMutationMetadata = {}): Promise<MutationOutcome<CustomerOrder>> { const commandMetadata = createMutationMetadata(`order.send:${orderId}`, { ...metadata, actor: metadata.actor ?? { id: input.sentBy } }); const result = await getOrderApiRuntime().commands.recordSendEvidence(orderId, { ...input }, versionedOptions(orderId, commandMetadata, "send")); projectAuthoritativeOrderResult(result.order); return orderOutcome("order.send", commandMetadata, result.order, result.evidence); }

export function changeOrderState(orderId: string, state: OrderState, definitions?: readonly OrderStateDefinition[], now?: string) { assertDemoOrderMutationAllowed("changeOrderState"); return transitionOrderState(orderRepository, orderId, state, definitions, now); }
export function confirmOrderSnapshot(orderId: string, now?: string) { assertDemoOrderMutationAllowed("confirmOrderSnapshot"); return confirmOrderCommand(orderRepository, orderId, now); }
export function completeOrderFromClosing(orderId: string, completion: Parameters<typeof completeOrderCommand>[2]) { assertDemoOrderMutationAllowed("completeOrderFromClosing"); return completeOrderCommand(orderRepository, orderId, completion); }
export function cancelOrder(orderId: string, input: Parameters<typeof cancelOrderCommand>[2], now?: string) { assertDemoOrderMutationAllowed("cancelOrder"); return cancelOrderCommand(orderRepository, orderId, input, now); }
export function subscribeToOrders(listener: (orders: OrderCollection) => void): () => void { return orderRepository.subscribe(listener); }
export function subscribeToOrderList(listener: (orders: CustomerOrder[]) => void): () => void { return orderRepository.subscribe(() => listener(orderRepository.list())); }
export function getOrderPreference<T>(key: string, fallback: T): T { return orderPreferences.get(key, fallback); }
export function setOrderPreference<T>(key: string, value: T): void { orderPreferences.set(key, value); }
export function removeOrderPreference(key: string): void { orderPreferences.remove(key); }

function projectAuthoritativeOrderResult(result: CustomerOrder | CustomerOrder[]): void { const records = Array.isArray(result) ? result : [result]; runBackendProjection("orders", () => { const next = structuredClone(orderRepository.snapshot()); for (const record of records) { for (const partitionKey of Object.keys(next)) next[partitionKey] = (next[partitionKey] ?? []).filter((item) => item.id !== record.id); const partitionKey = relationshipRefKey(record.buyerRef); next[partitionKey] = [structuredClone(record), ...(next[partitionKey] ?? [])]; } orderRepository.replace(next); }); }
function executeOrderMutation<TPayload, TResult extends CustomerOrder | CustomerOrder[]>(command: BackendMutationCommand<TPayload>, metadata: MutationCommandMetadata, localExecutor?: LocalMutationExecutor<TResult>): Promise<MutationOutcome<TResult>> { return executeSharedMutationCommand(command, metadata, localExecutor).then((outcome) => { projectAuthoritativeOrderResult(outcome.data); return outcome; }); }
function withOrderVersion(orderId: string, metadata: OrderLifecycleMutationMetadata): OrderLifecycleMutationMetadata { return { ...metadata, expectedVersion: metadata.expectedVersion ?? readMutationVersion(orderRepository.getById(orderId)) }; }
function requireOrderResult(orderId: string): CustomerOrder { const order = orderRepository.getById(orderId); if (!order) throw new Error(`ORDER_NOT_FOUND:${orderId}`); return order; }
function requireOrderVersion(orderId: string, operation: string): number { const value = getOrderSnapshot(orderId)?.resourceVersion; if (typeof value === "number" && value > 0) return value; if (!isOrderConnectedApiRuntime()) return 1; throw new MutationCommandError({ code: "ORDER_RESOURCE_VERSION_REQUIRED", message: `Order ${orderId} requires an authoritative resource version for ${operation}.`, category: "CONFLICT", retryable: false }); }
function commandOptions(metadata: MutationCommandMetadata) { return { idempotencyKey: metadata.idempotencyKey, correlationId: metadata.correlationId, signal: metadata.signal }; }
function versionedOptions(orderId: string, metadata: MutationCommandMetadata, operation: string) { return { ...commandOptions(metadata), expectedVersion: requireOrderVersion(orderId, operation) }; }
function orderOutcome(commandType: string, metadata: MutationCommandMetadata, order: CustomerOrder, evidence: OrderMutationEvidence): MutationOutcome<CustomerOrder> { return { data: order, commandId: evidence.commandId, commandType, aggregateType: evidence.aggregateType, aggregateId: evidence.aggregateId, idempotencyKey: metadata.idempotencyKey, correlationId: evidence.correlationId, occurredAt: evidence.occurredAt, version: evidence.version, outcome: evidence.outcome, warnings: [...evidence.warnings], emittedEvents: [...evidence.emittedEventIds], audit: { authority: evidence.authority === "backend" ? "backend" : "demo", evidenceIds: [...evidence.auditEvidenceIds] } }; }
function orderBatchOutcome(commandType: string, metadata: MutationCommandMetadata, orders: readonly CustomerOrder[], evidence: OrderMutationEvidence): MutationOutcome<CustomerOrder[]> { return { ...orderOutcome(commandType, metadata, orders[0] ?? ({ id: evidence.aggregateId } as CustomerOrder), evidence), data: [...orders], aggregateType: "order-batch" }; }
function assertDemoOrderMutationAllowed(operation: string): void { if (!isOrderConnectedApiRuntime()) return; throw new MutationCommandError({ code: "ORDER_CONNECTED_MUTATION_REQUIRES_API", message: `Connected Order mutation ${operation} requires the dedicated Order API or workflow runtime.`, category: "INFRASTRUCTURE", retryable: false, details: { operation } }); }
