import { CAPABILITIES } from "@/platform/access-control";
import type { MetricDefinition } from "./metric.types";

export const CRM_METRIC_IDS = {
  MONTHLY_COMPLETED_REVENUE: "crm.revenue.completed.current-period",
  ACTIVE_LEADS: "crm.leads.active.snapshot",
  OPEN_PIPELINE_VALUE: "crm.deals.open-pipeline.snapshot",
  OPEN_SUPPORT_CASES: "crm.support.open.snapshot",
  LEAD_QUALIFICATION_RATE: "crm.leads.qualification-rate.period",
  QUOTE_ACCEPTANCE_RATE: "crm.quotes.acceptance-rate.period",
  COMPLETED_ORDERS: "crm.orders.completed.period",
  CUSTOMER_TOTAL: "crm.customers.total.snapshot",
} as const;

export type CrmMetricId = typeof CRM_METRIC_IDS[keyof typeof CRM_METRIC_IDS];

export const CRM_METRIC_CATALOG: Record<CrmMetricId, MetricDefinition> = {
  [CRM_METRIC_IDS.MONTHLY_COMPLETED_REVENUE]: {
    id: CRM_METRIC_IDS.MONTHLY_COMPLETED_REVENUE,
    title: { vi: "Doanh thu đơn hàng hoàn tất", en: "Completed order revenue" },
    description: { vi: "Tổng giá trị đơn hàng đã hoàn tất trong kỳ đang chọn.", en: "Total value of orders completed in the selected period." },
    formula: { vi: "Tổng grandTotal của đơn hàng có trạng thái Hoàn thành và ngày hoàn tất nằm trong kỳ.", en: "Sum grandTotal for orders in Completed state whose completion date is inside the period." },
    sourceModules: ["orders"],
    includedStates: [{ vi: "Đơn hàng: Hoàn thành", en: "Orders: Completed" }],
    dateField: { vi: "Ngày hoàn tất đơn hàng", en: "Order completion date" },
    valueKind: "currency",
    requiredCapabilities: [CAPABILITIES.REPORTS_READ, CAPABILITIES.ORDERS_READ],
    periodMode: "PERIOD",
    owner: "CRM Analytics",
    version: 1,
  },
  [CRM_METRIC_IDS.ACTIVE_LEADS]: {
    id: CRM_METRIC_IDS.ACTIVE_LEADS,
    title: { vi: "Khách hàng tiềm năng đang hoạt động", en: "Active leads" },
    description: { vi: "Số Lead chưa đóng tại thời điểm xem.", en: "Number of leads that are not closed at view time." },
    formula: { vi: "Đếm Lead có trạng thái công việc khác Đã đóng.", en: "Count leads whose work state is not Closed." },
    sourceModules: ["leads"],
    includedStates: [{ vi: "Mọi trạng thái trừ Đã đóng", en: "All states except Closed" }],
    dateField: { vi: "Ảnh chụp hiện tại, không lọc theo ngày", en: "Current snapshot; no date filter" },
    valueKind: "count",
    requiredCapabilities: [CAPABILITIES.DASHBOARD_READ, CAPABILITIES.LEADS_READ],
    periodMode: "SNAPSHOT",
    owner: "CRM Analytics",
    version: 1,
  },
  [CRM_METRIC_IDS.OPEN_PIPELINE_VALUE]: {
    id: CRM_METRIC_IDS.OPEN_PIPELINE_VALUE,
    title: { vi: "Giá trị pipeline đang mở", en: "Open pipeline value" },
    description: { vi: "Tổng giá trị các cơ hội chưa Thắng hoặc Thua.", en: "Total value of deals not yet Won or Lost." },
    formula: { vi: "Tổng amount của Deal có stage khác Thắng và Thua.", en: "Sum amount for Deals whose stage is neither Won nor Lost." },
    sourceModules: ["deals"],
    includedStates: [{ vi: "Các giai đoạn đang mở", en: "Open stages" }],
    dateField: { vi: "Ảnh chụp hiện tại, không lọc theo ngày", en: "Current snapshot; no date filter" },
    valueKind: "currency",
    requiredCapabilities: [CAPABILITIES.DASHBOARD_READ, CAPABILITIES.DEALS_READ],
    periodMode: "SNAPSHOT",
    owner: "CRM Analytics",
    version: 1,
  },
  [CRM_METRIC_IDS.OPEN_SUPPORT_CASES]: {
    id: CRM_METRIC_IDS.OPEN_SUPPORT_CASES,
    title: { vi: "Phiếu hỗ trợ đang mở", en: "Open support tickets" },
    description: { vi: "Số phiếu chưa Đã xử lý, Đã đóng hoặc Đã hủy.", en: "Number of tickets not Resolved, Closed, or Cancelled." },
    formula: { vi: "Đếm Support Ticket ngoài ba trạng thái kết thúc.", en: "Count Support Tickets outside the three terminal states." },
    sourceModules: ["support"],
    includedStates: [{ vi: "Trạng thái chưa kết thúc", en: "Non-terminal states" }],
    dateField: { vi: "Ảnh chụp hiện tại, không lọc theo ngày", en: "Current snapshot; no date filter" },
    valueKind: "count",
    requiredCapabilities: [CAPABILITIES.DASHBOARD_READ, CAPABILITIES.SUPPORT_READ],
    periodMode: "SNAPSHOT",
    owner: "CRM Analytics",
    version: 1,
  },
  [CRM_METRIC_IDS.LEAD_QUALIFICATION_RATE]: {
    id: CRM_METRIC_IDS.LEAD_QUALIFICATION_RATE,
    title: { vi: "Tỷ lệ Lead đạt điều kiện", en: "Lead qualification rate" },
    description: { vi: "Tỷ lệ Lead tạo trong kỳ có kết quả đánh giá tích cực.", en: "Share of leads created in the period with a positive qualification outcome." },
    formula: { vi: "Lead đạt điều kiện trong kỳ / Tổng Lead tạo trong kỳ × 100.", en: "Qualified leads in period / Total leads created in period × 100." },
    sourceModules: ["leads"],
    includedStates: [{ vi: "Kết quả đánh giá tích cực", en: "Positive qualification outcomes" }],
    dateField: { vi: "Ngày tạo Lead", en: "Lead created date" },
    valueKind: "percentage",
    requiredCapabilities: [CAPABILITIES.REPORTS_READ, CAPABILITIES.LEADS_READ],
    periodMode: "PERIOD",
    owner: "CRM Analytics",
    version: 1,
  },
  [CRM_METRIC_IDS.QUOTE_ACCEPTANCE_RATE]: {
    id: CRM_METRIC_IDS.QUOTE_ACCEPTANCE_RATE,
    title: { vi: "Tỷ lệ báo giá được chấp nhận", en: "Quote acceptance rate" },
    description: { vi: "Tỷ lệ báo giá tạo trong kỳ đã được khách hàng chấp nhận.", en: "Share of quotes created in the period that were accepted." },
    formula: { vi: "Báo giá Đã chấp nhận tạo trong kỳ / Tổng báo giá tạo trong kỳ × 100.", en: "Accepted quotes created in period / Total quotes created in period × 100." },
    sourceModules: ["quotes"],
    includedStates: [{ vi: "Báo giá: Đã chấp nhận", en: "Quotes: Accepted" }],
    dateField: { vi: "Ngày tạo báo giá", en: "Quote created date" },
    valueKind: "percentage",
    requiredCapabilities: [CAPABILITIES.REPORTS_READ, CAPABILITIES.QUOTES_READ],
    periodMode: "PERIOD",
    owner: "CRM Analytics",
    version: 1,
  },
  [CRM_METRIC_IDS.COMPLETED_ORDERS]: {
    id: CRM_METRIC_IDS.COMPLETED_ORDERS,
    title: { vi: "Đơn hàng hoàn tất", en: "Completed orders" },
    description: { vi: "Số đơn hàng hoàn tất trong kỳ.", en: "Number of orders completed in the selected period." },
    formula: { vi: "Đếm đơn hàng Hoàn thành có ngày hoàn tất nằm trong kỳ.", en: "Count Completed orders whose completion date is inside the period." },
    sourceModules: ["orders"],
    includedStates: [{ vi: "Đơn hàng: Hoàn thành", en: "Orders: Completed" }],
    dateField: { vi: "Ngày hoàn tất đơn hàng", en: "Order completion date" },
    valueKind: "count",
    requiredCapabilities: [CAPABILITIES.REPORTS_READ, CAPABILITIES.ORDERS_READ],
    periodMode: "PERIOD",
    owner: "CRM Analytics",
    version: 1,
  },
  [CRM_METRIC_IDS.CUSTOMER_TOTAL]: {
    id: CRM_METRIC_IDS.CUSTOMER_TOTAL,
    title: { vi: "Tổng khách hàng", en: "Total customers" },
    description: { vi: "Số Customer profile dùng quan hệ khách hàng chuẩn tại thời điểm xem.", en: "Number of canonical Customer profiles at view time." },
    formula: { vi: "Đếm Customer profile duy nhất theo relationshipRef.", en: "Count unique Customer profiles by relationshipRef." },
    sourceModules: ["customers"],
    includedStates: [{ vi: "Mọi trạng thái khách hàng", en: "All customer states" }],
    dateField: { vi: "Ảnh chụp hiện tại, không lọc theo ngày", en: "Current snapshot; no date filter" },
    valueKind: "count",
    requiredCapabilities: [CAPABILITIES.REPORTS_READ, CAPABILITIES.CUSTOMERS_VIEW],
    periodMode: "SNAPSHOT",
    owner: "CRM Analytics",
    version: 1,
  },
};

export function getCrmMetricDefinition(metricId: string): MetricDefinition | undefined {
  return CRM_METRIC_CATALOG[metricId as CrmMetricId];
}
