import { CAPABILITIES } from "@/platform/access-control/domain/capabilityCatalog";
import type { GuidanceLocaleText, GuidanceTask, ScreenGuidance } from "@/guidance/domain/guidance.types";
import { createScreenGuidance } from "@/guidance/content/shared/createScreenGuidance";

const text = (vi: string, en: string): GuidanceLocaleText => ({ vi, en });
const task = (id: string, vi: string, en: string, requiredCapabilities?: string[], route?: string): GuidanceTask => ({
  id,
  text: text(vi, en),
  requiredCapabilities,
  route,
});

export const CRM_EXTENDED_SCREEN_GUIDANCE: ScreenGuidance[] = [
  createScreenGuidance({
    id: "crm.my-work.overview",
    routeKey: "MY_WORK",
    productSpace: "crm",
    title: text("Công việc của tôi", "My work"),
    purpose: text("Tập trung các công việc, lần hẹn và bản ghi cần bạn xử lý theo mức độ ưu tiên.", "Bring together tasks, follow-ups, and records that need your attention by priority."),
    primaryTasks: [
      task("review", "Rà soát việc quá hạn, đến hạn hôm nay và sắp đến hạn.", "Review overdue, due-today, and upcoming work."),
      task("open-task", "Mở công việc để xem ngữ cảnh, người liên quan và hạn xử lý.", "Open a task to review context, related records, and due time.", [CAPABILITIES.TASKS_READ], "tasks"),
      task("complete", "Cập nhật kết quả khi hành động thực tế đã hoàn thành.", "Record the outcome only after the real action is complete.", [CAPABILITIES.TASKS_COMPLETE]),
    ],
    commonMistakes: [text("Không đánh dấu hoàn thành chỉ để làm sạch danh sách; hãy ghi kết quả hoặc bước tiếp theo.", "Do not mark work complete merely to clear the list; record the outcome or next step.")],
    relatedWorkflowIds: ["workflow.support-to-task", "workflow.task-execution"],
    keywords: text("công việc của tôi ưu tiên quá hạn hôm nay lần hẹn", "my work priority overdue today follow-up"),
  }),
  createScreenGuidance({
    id: "crm.calendar.overview",
    routeKey: "CALENDAR",
    productSpace: "crm",
    title: text("Lịch công việc", "Work calendar"),
    purpose: text("Xem công việc và lịch hẹn theo ngày, tuần hoặc khoảng thời gian để cân đối nguồn lực.", "Review tasks and appointments by day, week, or time range to balance workload."),
    primaryTasks: [
      task("navigate", "Chuyển ngày hoặc tuần để xem khối lượng công việc.", "Move across days or weeks to review workload."),
      task("open", "Mở mục lịch để xem bản ghi và hành động cần thực hiện.", "Open a calendar item to inspect the source record and required action.", [CAPABILITIES.TASKS_READ]),
      task("reschedule", "Điều chỉnh hạn xử lý khi kế hoạch thay đổi và ghi rõ lý do.", "Reschedule work when plans change and record the reason.", [CAPABILITIES.TASKS_UPDATE]),
    ],
    commonMistakes: [text("Lịch chỉ là cách nhìn theo thời gian; dữ liệu gốc vẫn nằm trong Công việc hoặc bản ghi liên quan.", "The calendar is a time-based view; the source data remains in Tasks or the related record.")],
    relatedWorkflowIds: ["workflow.task-execution"],
    keywords: text("lịch ngày tuần hạn xử lý cuộc hẹn công việc", "calendar day week due date appointment task"),
  }),
  createScreenGuidance({
    id: "crm.notifications.center",
    routeKey: "NOTIFICATIONS",
    productSpace: "crm",
    title: text("Thông báo", "Notifications"),
    version: 2,
    reviewedAt: "2026-07-13",
    purpose: text("Theo dõi các thay đổi và yêu cầu cần chú ý, sau đó mở đúng bản ghi để xử lý.", "Track changes and attention items, then open the correct record to take action."),
    primaryTasks: [
      task("review", "Đọc thông báo mới theo thời gian và mức độ liên quan.", "Review new notifications by time and relevance."),
      task("open", "Mở bản ghi nguồn thay vì xử lý chỉ từ nội dung thông báo.", "Open the source record instead of acting only from the notification text."),
      task("mark", "Đánh dấu đã đọc sau khi đã hiểu hoặc xử lý nội dung.", "Mark as read after understanding or handling the item."),
    ],
    commonMistakes: [
      text("Đánh dấu đã đọc không đồng nghĩa công việc hoặc yêu cầu nghiệp vụ đã hoàn thành.", "Marking a notification as read does not complete the underlying work or business request."),
      text("Popup thông báo tự đóng khi bạn bấm ra ngoài, nhấn Escape hoặc chuyển màn hình; nó không khóa thao tác CRM phía sau.", "The notification popover closes on outside click, Escape, or navigation and does not lock the CRM workspace behind it."),
    ],
    keywords: text("thông báo chưa đọc thay đổi nhắc việc", "notification unread change reminder"),
  }),
  createScreenGuidance({
    id: "crm.tasks.list",
    routeKey: "TASKS",
    productSpace: "crm",
    title: text("Công việc", "Tasks"),
    purpose: text("Tạo, phân công và theo dõi các hành động cụ thể có người phụ trách và thời hạn rõ ràng.", "Create, assign, and track concrete actions with a clear owner and due time."),
    primaryTasks: [
      task("create", "Tạo công việc với hành động, người phụ trách và hạn xử lý rõ ràng.", "Create a task with a clear action, owner, and due time.", [CAPABILITIES.TASKS_CREATE]),
      task("prioritize", "Lọc theo trạng thái, người phụ trách hoặc hạn để ưu tiên xử lý.", "Filter by status, owner, or due time to prioritize work."),
      task("complete", "Chỉ hoàn thành sau khi có kết quả thực tế.", "Complete the task only after a real outcome exists.", [CAPABILITIES.TASKS_COMPLETE]),
    ],
    relatedWorkflowIds: ["workflow.support-to-task", "workflow.task-execution"],
    requiredCapabilities: [CAPABILITIES.TASKS_READ],
    keywords: text("công việc nhiệm vụ giao việc hạn xử lý hoàn thành", "task assignment due date complete"),
  }),
  createScreenGuidance({
    id: "crm.tasks.detail",
    routeKey: "TASK_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết công việc", "Task detail"),
    purpose: text("Xem đầy đủ ngữ cảnh, thời hạn, người phụ trách và kết quả của một công việc.", "Review the full context, due time, owner, and outcome of a task."),
    primaryTasks: [
      task("review", "Đọc mô tả, bản ghi liên quan và lịch sử cập nhật trước khi xử lý.", "Read the description, related records, and history before acting."),
      task("update", "Cập nhật người phụ trách, hạn hoặc trạng thái khi kế hoạch thay đổi.", "Update owner, due time, or status when the plan changes.", [CAPABILITIES.TASKS_UPDATE]),
      task("finish", "Ghi kết quả và hoàn thành công việc khi hành động đã xong.", "Record the outcome and complete the task when the action is done.", [CAPABILITIES.TASKS_COMPLETE]),
    ],
    relatedWorkflowIds: ["workflow.task-execution"],
    requiredCapabilities: [CAPABILITIES.TASKS_READ],
    commonMistakes: [text("Không thay đổi người phụ trách hoặc hạn mà không để lại ngữ cảnh cho người tiếp nhận.", "Do not change the owner or due time without leaving context for the next person.")],
    keywords: text("chi tiết công việc người phụ trách hạn kết quả", "task detail assignee due outcome"),
  }),
  createScreenGuidance({
    id: "crm.leads.queue",
    routeKey: "LEADS_QUEUE",
    productSpace: "crm",
    title: text("Hàng đợi khách hàng tiềm năng", "Lead queue"),
    purpose: text("Ưu tiên khách hàng tiềm năng cần tiếp nhận, phân công hoặc theo dõi tiếp.", "Prioritize leads that need intake, assignment, or follow-up."),
    primaryTasks: [
      task("triage", "Rà soát nguồn, thời gian tiếp nhận và mức độ đầy đủ của dữ liệu.", "Review source, intake time, and data completeness."),
      task("assign", "Phân công đúng người phụ trách theo phạm vi dữ liệu.", "Assign the correct owner within the permitted data scope.", [CAPABILITIES.LEADS_ASSIGN]),
      task("open", "Mở chi tiết để xác minh nhu cầu trước khi chốt kết quả.", "Open the detail to verify need before resolving the outcome.", [CAPABILITIES.LEADS_READ], "leads"),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.LEADS_READ],
    commonMistakes: [text("Không xác minh hoặc chuyển đổi chỉ dựa trên thông tin ngắn trong hàng đợi.", "Do not qualify or convert based only on the queue summary.")],
    keywords: text("hàng đợi lead tiếp nhận phân công ưu tiên", "lead queue intake assignment priority"),
  }),
  createScreenGuidance({
    id: "crm.leads.detail",
    routeKey: "LEAD_DETAIL",
    productSpace: "crm",
    version: 2,
    title: text("Chi tiết khách hàng tiềm năng", "Lead detail"),
    purpose: text("Tập hợp thông tin nhận diện, nhu cầu, tương tác và tiến trình xử lý của một khách hàng tiềm năng.", "Bring together identity, need, interactions, and work progress for a lead."),
    primaryTasks: [
      task("verify", "Kiểm tra thông tin liên hệ, nguồn, nhu cầu và người phụ trách.", "Verify contact details, source, need, and owner."),
      task("update", "Cập nhật tiến trình làm việc và lần hẹn tiếp theo.", "Update work progress and the next follow-up.", [CAPABILITIES.LEADS_UPDATE]),
      task("qualify", "Bắt đầu xác minh khi dữ liệu đã đủ để quyết định bước tiếp theo.", "Start qualification when enough data exists to decide the next path.", [CAPABILITIES.LEADS_QUALIFY]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.LEADS_READ],
    commonMistakes: [text("Không trộn tiến trình làm việc với kết quả xác minh cuối cùng.", "Do not confuse work progress with the final qualification outcome.")],
    keywords: text("chi tiết lead nhu cầu tương tác xác minh lần hẹn", "lead detail need interaction qualification follow-up"),
  }),
  createScreenGuidance({
    id: "crm.leads.qualify",
    routeKey: "LEAD_QUALIFY",
    productSpace: "crm",
    version: 2,
    title: text("Xác minh khách hàng tiềm năng", "Qualify lead"),
    purpose: text("Đánh giá dữ liệu và chọn kết quả khả dụng: chăm sóc thêm với Contact, tạo Contact và cơ hội, hoặc không tiếp tục.", "Assess the evidence and choose an available outcome: nurture with a Contact, create a Contact and opportunity, or stop."),
    primaryTasks: [
      task("review", "Rà soát dữ liệu bắt buộc và các dấu hiệu nhu cầu thực tế.", "Review required data and evidence of real need."),
      task("choose", "Chọn kết quả phù hợp với quy trình bán hàng đã cấu hình.", "Choose the outcome supported by the configured sales process.", [CAPABILITIES.LEADS_QUALIFY]),
      task("confirm", "Xác nhận rồi mở Lead, Contact, công việc hoặc cơ hội từ kết quả authoritative.", "Confirm, then open the Lead, Contact, task, or Deal from the authoritative result.", [CAPABILITIES.LEADS_QUALIFY]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.LEADS_QUALIFY],
    commonMistakes: [text("Không chọn kết quả chỉ để vượt qua bước xác minh; kết quả quyết định các bản ghi và luồng tiếp theo.", "Do not choose an outcome merely to pass the step; it determines the records and downstream flow.")],
    keywords: text("xác minh lead kết quả contact cơ hội", "qualify lead outcome contact opportunity"),
  }),
  createScreenGuidance({
    id: "crm.leads.sell-now",
    routeKey: "LEAD_SELL_NOW",
    productSpace: "crm",
    title: text("Bán trực tiếp từ khách hàng tiềm năng", "Sell now from lead"),
    purpose: text("Tạo cam kết mua trực tiếp khi workspace cho phép bỏ qua cơ hội hoặc báo giá.", "Create a purchase commitment directly when the workspace permits bypassing an opportunity or quote."),
    primaryTasks: [
      task("buyer", "Xác nhận người mua và thông tin liên hệ chính xác.", "Confirm the buyer and accurate contact details."),
      task("items", "Chọn sản phẩm, số lượng và điều kiện bán.", "Choose products, quantities, and selling conditions."),
      task("create", "Kiểm tra người nhận, giao hàng và thanh toán trước khi tạo đơn.", "Review recipient, delivery, and payment details before creating the order.", [CAPABILITIES.ORDERS_CREATE]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.LEADS_QUALIFY, CAPABILITIES.ORDERS_CREATE],
    commonMistakes: [text("Không dùng bán trực tiếp khi quy trình yêu cầu cơ hội, phê duyệt giá hoặc báo giá được chấp nhận.", "Do not use direct sale when the process requires an opportunity, price approval, or an accepted quote.")],
    keywords: text("bán trực tiếp từ lead tạo đơn nhanh", "sell now lead direct order"),
  }),
  createScreenGuidance({
    id: "crm.products.list",
    routeKey: "CATALOG",
    productSpace: "crm",
    title: text("Sản phẩm", "Products"),
    purpose: text("Quản lý danh mục sản phẩm và dịch vụ được dùng trong báo giá và đơn hàng.", "Manage the product and service catalog used in quotes and orders."),
    primaryTasks: [
      task("search", "Tìm và lọc sản phẩm theo trạng thái hoặc loại.", "Search and filter products by status or type."),
      task("create", "Tạo sản phẩm với mã, đơn vị, giá và chính sách phù hợp.", "Create a product with the right code, unit, price, and policy.", [CAPABILITIES.PRODUCTS_CREATE]),
      task("review", "Mở chi tiết để kiểm tra thông tin trước khi dùng trong giao dịch.", "Open details to verify information before using the product in a transaction.", [CAPABILITIES.PRODUCTS_READ]),
    ],
    requiredCapabilities: [CAPABILITIES.PRODUCTS_READ],
    relatedWorkflowIds: ["workflow.product-to-sale"],
    commonMistakes: [text("Không xóa hoặc thay đổi ý nghĩa sản phẩm đã được dùng trong giao dịch lịch sử.", "Do not delete or repurpose a product that already appears in historical transactions.")],
    keywords: text("sản phẩm dịch vụ danh mục giá đơn vị mã", "product service catalog price unit code"),
  }),
  createScreenGuidance({
    id: "crm.products.detail",
    routeKey: "PRODUCT_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết sản phẩm", "Product detail"),
    purpose: text("Xem thông tin thương mại, trạng thái và cách sản phẩm được sử dụng trong bán hàng.", "Review commercial information, status, and how a product is used in sales."),
    primaryTasks: [
      task("review", "Kiểm tra mã, tên, loại, đơn vị và giá hiện hành.", "Review code, name, type, unit, and current price."),
      task("update", "Cập nhật thông tin cho các giao dịch mới mà không làm sai lịch sử.", "Update information for new transactions without distorting history.", [CAPABILITIES.PRODUCTS_EDIT]),
      task("availability", "Kiểm tra trạng thái trước khi thêm vào báo giá hoặc đơn hàng.", "Check availability before adding the product to a quote or order."),
    ],
    requiredCapabilities: [CAPABILITIES.PRODUCTS_READ],
    relatedWorkflowIds: ["workflow.product-to-sale"],
    commonMistakes: [text("Giá trên sản phẩm không tự thay đổi giá đã chốt trên báo giá hoặc đơn hàng cũ.", "Changing the product price does not rewrite pricing already committed on historical quotes or orders.")],
    keywords: text("chi tiết sản phẩm giá trạng thái sử dụng", "product detail price status usage"),
  }),
  createScreenGuidance({
    id: "crm.deals.detail",
    routeKey: "DEAL_DETAIL",
    productSpace: "crm",
    version: 3,
    reviewedAt: "2026-07-13",
    title: text("Chi tiết cơ hội", "Opportunity detail"),
    purpose: text("Theo dõi người mua, giá trị, giai đoạn, xác suất và các bước cần thực hiện để chốt cơ hội.", "Track buyer, value, stage, probability, and actions needed to close an opportunity."),
    primaryTasks: [
      task("review", "Kiểm tra người mua, giá trị dự kiến, giai đoạn và bước tiếp theo.", "Review buyer, expected value, stage, and next step."),
      task("update", "Cập nhật giai đoạn khi có bằng chứng tiến triển thực tế.", "Update the stage when real progress evidence exists.", [CAPABILITIES.DEALS_UPDATE]),
      task("close", "Ghi lý do và kết quả khi thắng hoặc thua.", "Record the reason and outcome when won or lost.", [CAPABILITIES.DEALS_CLOSE]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.DEALS_READ],
    commonMistakes: [
      text("Không tăng xác suất hoặc chuyển giai đoạn chỉ để làm đẹp pipeline.", "Do not raise probability or advance the stage merely to improve the pipeline view."),
      text("Không thay đổi ngày đóng hoặc xác suất mà không có lý do kinh doanh; lịch sử dự báo sẽ giữ lại thay đổi.", "Do not change close date or probability without business evidence; forecast history retains the change."),
      text("Trước khi có giao dịch hoàn tất, thẻ quan hệ chỉ thể hiện bên mua đang theo đuổi; không coi đó là hồ sơ Customer 360.", "Before a completed purchase, the relationship card only identifies the buyer being pursued; do not treat it as Customer 360."),
    ],
    additionalSteps: [
      { id: "forecast-history", targetId: "deals.detail.forecast-history", title: text("Đối chiếu lịch sử dự báo", "Review forecast history"), body: text("Xem ai đã thay đổi ngày đóng, xác suất hoặc forecast category và giá trị trước/sau.", "Review who changed close date, probability, or forecast category and inspect before/after values."), placement: "top", expectedAction: "view" },
    ],
    keywords: text("chi tiết cơ hội giai đoạn xác suất bước tiếp theo forecast lịch sử thắng thua", "opportunity detail stage probability next step forecast history won lost"),
  }),
  createScreenGuidance({
    id: "crm.quotes.create",
    routeKey: "QUOTE_NEW",
    productSpace: "crm",
    version: 2,
    title: text("Tạo báo giá", "Create quote"),
    purpose: text("Soạn đề xuất thương mại gồm người mua, sản phẩm, giá, thuế, chiết khấu và điều khoản.", "Prepare a commercial proposal with buyer, products, pricing, tax, discount, and terms."),
    primaryTasks: [
      task("buyer", "Chọn đúng người mua và cơ hội liên quan nếu có.", "Choose the correct buyer and related opportunity when applicable."),
      task("pricing", "Thêm sản phẩm, số lượng, giá, thuế và chiết khấu.", "Add products, quantities, prices, tax, and discounts."),
      task("save", "Kiểm tra thời hạn và điều khoản trước khi lưu hoặc gửi phê duyệt.", "Review validity and terms before saving or requesting approval.", [CAPABILITIES.QUOTES_CREATE]),
      task("deliver", "Sau khi gửi thực tế, xác nhận đúng kênh Gmail, Zalo, ứng dụng chat, SMS hoặc email khác.", "After actual delivery, confirm the correct Gmail, Zalo, chat app, SMS, or other email channel.", [CAPABILITIES.QUOTES_UPDATE]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.QUOTES_CREATE],
    commonMistakes: [
      text("Không xác nhận đã gửi nếu mới chỉ tải PDF hoặc mở màn hình soạn Gmail.", "Do not confirm delivery merely because the PDF was downloaded or Gmail compose was opened."),
      text("Không coi báo giá nháp là cam kết mua hoặc bằng chứng đã được khách hàng chấp nhận.", "Do not treat a draft quote as a purchase commitment or evidence of customer acceptance."),
    ],
    additionalSteps: [
      { id: "delivery", targetId: "quotes.delivery.open-confirmation", title: text("Ghi nhận đúng kênh đã gửi", "Record the actual delivery channel"), body: text("Chọn Xác nhận đã gửi sau khi khách đã nhận Báo giá qua Gmail, Zalo, ứng dụng chat, SMS hoặc kênh khác.", "Choose Confirm sent after the customer receives the quote through Gmail, Zalo, a chat app, SMS, or another channel."), placement: "top", expectedAction: "view" },
    ],
    keywords: text("tạo báo giá sản phẩm giá thuế chiết khấu điều khoản", "create quote product price tax discount terms"),
  }),
  createScreenGuidance({
    id: "crm.quotes.detail",
    routeKey: "QUOTE_DETAIL",
    productSpace: "crm",
    version: 2,
    title: text("Chi tiết báo giá", "Quote detail"),
    purpose: text("Xem nội dung thương mại, trạng thái phê duyệt, phát hành và chấp nhận của báo giá.", "Review commercial content and the quote's approval, issuance, and acceptance state."),
    primaryTasks: [
      task("review", "Kiểm tra người mua, dòng hàng, tổng tiền và điều khoản.", "Review buyer, line items, totals, and terms."),
      task("approve", "Phê duyệt khi chính sách yêu cầu và bạn có thẩm quyền.", "Approve when policy requires it and you are authorized.", [CAPABILITIES.QUOTES_APPROVE]),
      task("delivery", "Kiểm tra hoặc ghi nhận kênh đã gửi thực tế trước khi theo dõi phản hồi.", "Review or record the actual delivery channel before following up.", [CAPABILITIES.QUOTES_UPDATE]),
      task("order", "Chỉ tạo đơn khi báo giá đã đạt điều kiện được chấp nhận.", "Create an order only when the quote satisfies acceptance conditions.", [CAPABILITIES.ORDERS_CREATE]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.QUOTES_READ],
    commonMistakes: [text("Phê duyệt nội bộ, phát hành và khách hàng chấp nhận là các bằng chứng khác nhau.", "Team approval, issuance, and customer acceptance are different forms of evidence.")],
    keywords: text("chi tiết báo giá phê duyệt phát hành chấp nhận tạo đơn", "quote detail approval issue acceptance order"),
  }),
  createScreenGuidance({
    id: "crm.quotes.edit",
    routeKey: "QUOTE_EDIT",
    productSpace: "crm",
    version: 2,
    title: text("Chỉnh sửa báo giá", "Edit quote"),
    purpose: text("Điều chỉnh nội dung thương mại của báo giá khi trạng thái và quyền hiện tại cho phép.", "Adjust quote commercial content when the current state and permissions allow it."),
    primaryTasks: [
      task("review", "Xem trạng thái hiện tại và lý do cần thay đổi.", "Review the current state and reason for the change."),
      task("update", "Cập nhật dòng hàng, giá hoặc điều khoản được phép.", "Update allowed line items, pricing, or terms.", [CAPABILITIES.QUOTES_UPDATE]),
      task("save", "Kiểm tra lại tổng tiền và tác động đến phê duyệt trước khi lưu.", "Recheck totals and approval impact before saving.", [CAPABILITIES.QUOTES_UPDATE]),
      task("delivery", "Dùng Gmail hoặc xác nhận kênh gửi khác sau khi Báo giá đã thực sự được chuyển tới khách.", "Use Gmail or confirm another channel after the quote was actually delivered to the customer.", [CAPABILITIES.QUOTES_UPDATE]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.QUOTES_UPDATE],
    commonMistakes: [text("Không sửa báo giá đã phát hành hoặc chấp nhận mà bỏ qua quy tắc phiên bản và phê duyệt.", "Do not alter an issued or accepted quote while bypassing version and approval rules.")],
    keywords: text("chỉnh sửa báo giá dòng hàng điều khoản tổng tiền", "edit quote line items terms total"),
  }),
  createScreenGuidance({
    id: "crm.orders.detail",
    routeKey: "ORDER_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết đơn hàng", "Order detail"),
    purpose: text("Theo dõi cam kết mua, điều kiện vận hành và bằng chứng liên quan từ Thanh toán, Vận đơn và Đổi/Trả.", "Track the purchase commitment, operational readiness, and evidence from Payments, Shipping, and Returns."),
    primaryTasks: [
      task("review", "Kiểm tra người mua, người nhận, sản phẩm, tổng tiền và kế hoạch thanh toán.", "Review buyer, recipient, products, totals, and payment plan."),
      task("confirm", "Xác nhận đơn khi dữ liệu bắt buộc và điều kiện vận hành đã đầy đủ.", "Confirm the order when required data and operational conditions are complete.", [CAPABILITIES.ORDERS_COMPLETE]),
      task("evidence", "Mở Thanh toán, Vận đơn hoặc Đổi/Trả để xử lý dữ liệu thuộc khu vực đó.", "Open Payments, Shipping, or Returns to work on evidence owned by those areas."),
    ],
    relatedWorkflowIds: ["workflow.order-to-shipping", "workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.ORDERS_READ],
    commonMistakes: [text("Không cập nhật trạng thái thanh toán hoặc giao hàng trực tiếp trên đơn hàng.", "Do not write payment or delivery status directly on the order.")],
    keywords: text("chi tiết đơn hàng xác nhận thanh toán vận đơn đổi trả", "order detail confirm payment shipping return"),
  }),
  createScreenGuidance({
    id: "crm.orders.edit",
    routeKey: "ORDER_EDIT",
    productSpace: "crm",
    title: text("Chỉnh sửa đơn hàng", "Edit order"),
    purpose: text("Điều chỉnh dữ liệu đơn hàng khi trạng thái hiện tại vẫn cho phép thay đổi cam kết mua.", "Adjust order data while the current state still permits changes to the purchase commitment."),
    primaryTasks: [
      task("review", "Kiểm tra trạng thái và các bằng chứng đã phát sinh trước khi sửa.", "Review the state and any existing evidence before editing."),
      task("update", "Cập nhật người nhận, dòng hàng hoặc kế hoạch thanh toán được phép.", "Update allowed recipient, line-item, or payment-plan information.", [CAPABILITIES.ORDERS_UPDATE]),
      task("save", "Xác nhận tổng tiền và điều kiện vận hành sau thay đổi.", "Confirm totals and operational readiness after the change.", [CAPABILITIES.ORDERS_UPDATE]),
    ],
    relatedWorkflowIds: ["workflow.order-to-shipping"],
    requiredCapabilities: [CAPABILITIES.ORDERS_UPDATE],
    commonMistakes: [text("Không sửa dữ liệu làm mất nhất quán với giao dịch thanh toán hoặc vận đơn đã tạo.", "Do not make edits that conflict with recorded payments or existing shipping bookings.")],
    keywords: text("chỉnh sửa đơn hàng người nhận sản phẩm kế hoạch thanh toán", "edit order recipient products payment plan"),
  }),
  createScreenGuidance({
    id: "crm.payments.detail",
    routeKey: "PAYMENT_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết thanh toán", "Payment detail"),
    purpose: text("Xem giao dịch thu hoặc hoàn tiền, bằng chứng, đối soát và liên kết với đơn hàng.", "Review a collection or refund transaction, its evidence, reconciliation, and order linkage."),
    primaryTasks: [
      task("review", "Kiểm tra số tiền, phương thức, thời điểm và tham chiếu giao dịch.", "Review amount, method, time, and transaction reference."),
      task("reconcile", "Đối soát với chứng từ hoặc nguồn thanh toán khi cần.", "Reconcile against evidence or the payment source when needed.", [CAPABILITIES.PAYMENTS_RECONCILE]),
      task("refund", "Chỉ tạo hoàn tiền theo quyền và điều kiện nghiệp vụ.", "Create a refund only with the required permission and business conditions.", [CAPABILITIES.PAYMENTS_REFUND]),
    ],
    relatedWorkflowIds: ["workflow.order-to-shipping", "workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.PAYMENTS_READ],
    commonMistakes: [text("Không sửa đơn hàng để thay thế một giao dịch thanh toán hoặc hoàn tiền thực tế.", "Do not edit the order as a substitute for a real payment or refund transaction.")],
    keywords: text("chi tiết thanh toán giao dịch đối soát hoàn tiền chứng từ", "payment detail transaction reconcile refund evidence"),
  }),
  createScreenGuidance({
    id: "crm.invoices.list",
    routeKey: "INVOICES",
    productSpace: "crm",
    title: text("Hóa đơn", "Invoices"),
    purpose: text("Quản lý hóa đơn nháp, trạng thái phát hành, gửi chứng từ và các điều chỉnh bằng Credit Note.", "Manage invoice drafts, issuance, document delivery, and Credit Note adjustments."),
    primaryTasks: [
      task("review", "Rà soát hóa đơn theo lifecycle, bên mua, ngày phát hành và số tiền.", "Review invoices by lifecycle, buyer, issue date, and amount."),
      task("create", "Tạo hóa đơn nháp từ Order hoặc nguồn nghiệp vụ hợp lệ.", "Create a draft invoice from an Order or another supported source.", [CAPABILITIES.INVOICES_CREATE]),
      task("open", "Mở chứng từ để kiểm tra readiness, phát hành, gửi hoặc điều chỉnh.", "Open a document to review readiness, issue, send, or adjust it.", [CAPABILITIES.INVOICES_READ]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order", "workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.INVOICES_READ],
    commonMistakes: [text("Không dùng Payment Plan như hóa đơn và không sửa nội dung chính sau khi hóa đơn đã phát hành.", "Do not treat a Payment Plan as an invoice or edit core content after issue.")],
    keywords: text("hóa đơn nháp phát hành gửi credit note", "invoice draft issue send credit note"),
  }),
  createScreenGuidance({
    id: "crm.invoices.create",
    routeKey: "INVOICE_NEW",
    productSpace: "crm",
    title: text("Tạo hóa đơn nháp", "Create invoice draft"),
    purpose: text("Tạo chứng từ nháp từ dữ liệu bên bán, bên mua, dòng hàng và nguồn Order trước khi phát hành.", "Create a draft document from seller, buyer, line, and Order source data before issue."),
    primaryTasks: [
      task("source", "Chọn đúng Order và kiểm tra snapshot bên mua, tiền tệ và dòng hàng.", "Choose the correct Order and verify buyer, currency, and line snapshots."),
      task("dates", "Nhập ngày dự kiến phát hành, ngày đến hạn và chính sách thuế phù hợp.", "Enter the intended issue date, due date, and applicable tax policy."),
      task("save", "Lưu nháp để kiểm tra readiness; thao tác lưu không đồng nghĩa đã phát hành.", "Save the draft for readiness review; saving does not issue the invoice.", [CAPABILITIES.INVOICES_CREATE]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.INVOICES_CREATE],
    commonMistakes: [text("Không tự tạo số hóa đơn hoặc thông báo phát hành thành công từ trình duyệt.", "Do not manufacture invoice numbers or issuance success in the browser.")],
    keywords: text("tạo hóa đơn nháp order bên mua dòng hàng", "create invoice draft order buyer lines"),
  }),
  createScreenGuidance({
    id: "crm.invoices.detail",
    routeKey: "INVOICE_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết hóa đơn", "Invoice detail"),
    purpose: text("Kiểm tra nội dung chứng từ, readiness, lifecycle, trạng thái gửi, Credit Note và số dư công nợ liên quan.", "Review document content, readiness, lifecycle, delivery, Credit Notes, and related receivable balance."),
    primaryTasks: [
      task("review", "Đối chiếu bên bán, bên mua, dòng hàng, tổng tiền và nguồn Order.", "Reconcile seller, buyer, lines, totals, and Order sources."),
      task("issue", "Chỉ phát hành khi readiness không còn blocker.", "Issue only when readiness has no blockers.", [CAPABILITIES.INVOICES_ISSUE]),
      task("adjust", "Dùng Credit Note cho điều chỉnh sau phát hành thay vì sửa hóa đơn.", "Use a Credit Note for post-issue adjustments instead of editing the invoice.", [CAPABILITIES.INVOICES_CREATE_CREDIT_NOTE]),
    ],
    relatedWorkflowIds: ["workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.INVOICES_READ],
    commonMistakes: [text("Trạng thái gửi không thay đổi nội dung hoặc settlement của hóa đơn.", "Delivery state does not change invoice content or settlement.")],
    keywords: text("chi tiết hóa đơn readiness phát hành credit note công nợ", "invoice detail readiness issue credit note receivable"),
  }),
  createScreenGuidance({
    id: "crm.invoices.edit",
    routeKey: "INVOICE_EDIT",
    productSpace: "crm",
    title: text("Chỉnh sửa hóa đơn nháp", "Edit invoice draft"),
    purpose: text("Hiệu chỉnh dữ liệu chứng từ khi hóa đơn còn ở trạng thái nháp và chưa bị khóa bởi phát hành.", "Adjust document data while the invoice remains a draft and is not locked by issue."),
    primaryTasks: [
      task("review", "Kiểm tra phiên bản hiện tại và dữ liệu nguồn trước khi thay đổi.", "Review the current version and source data before changing it."),
      task("edit", "Cập nhật dòng, ngày và snapshot được phép nhưng giữ nguyên ownership của Order và Payment.", "Update allowed lines, dates, and snapshots while preserving Order and Payment ownership.", [CAPABILITIES.INVOICES_UPDATE_DRAFT]),
      task("save", "Lưu nháp rồi quay lại chi tiết để kiểm tra readiness.", "Save the draft and return to detail to review readiness.", [CAPABILITIES.INVOICES_UPDATE_DRAFT]),
    ],
    requiredCapabilities: [CAPABILITIES.INVOICES_UPDATE_DRAFT],
    commonMistakes: [text("Không chỉnh sửa hóa đơn đã phát hành; dùng Credit Note hoặc void có kiểm soát.", "Do not edit an issued invoice; use a Credit Note or controlled void.")],
    keywords: text("chỉnh sửa hóa đơn nháp dòng hàng ngày đến hạn", "edit invoice draft lines due date"),
  }),
  createScreenGuidance({
    id: "crm.receivables.list",
    routeKey: "RECEIVABLES",
    productSpace: "crm",
    title: text("Công nợ phải thu", "Receivables"),
    purpose: text("Theo dõi số dư chứng từ, quá hạn và aging từ Invoice, Allocation và Credit Note authoritative.", "Track document balances, overdue status, and aging from authoritative Invoices, Allocations, and Credit Notes."),
    primaryTasks: [
      task("review", "Lọc công nợ mở, quá hạn hoặc theo nhóm aging.", "Filter open, overdue, or aging-bucket receivables."),
      task("open", "Mở từng khoản để xem hóa đơn và ledger phân bổ.", "Open an item to inspect the invoice and allocation ledger.", [CAPABILITIES.RECEIVABLES_READ]),
      task("export", "Xuất dữ liệu theo quyền khi cần đối soát ngoài hệ thống.", "Export scoped data when external reconciliation is required.", [CAPABILITIES.RECEIVABLES_EXPORT]),
    ],
    relatedWorkflowIds: ["workflow.lead-to-order", "workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.RECEIVABLES_READ],
    commonMistakes: [text("Không sửa trực tiếp số dư công nợ; hãy sửa chứng từ nguồn, allocation hoặc Credit Note theo đúng owner.", "Do not edit receivable balances directly; correct the source document, allocation, or Credit Note through its owner.")],
    keywords: text("công nợ phải thu quá hạn aging số dư", "receivables overdue aging balance"),
  }),
  createScreenGuidance({
    id: "crm.receivables.detail",
    routeKey: "RECEIVABLE_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết công nợ", "Receivable detail"),
    purpose: text("Đối chiếu hóa đơn, allocation, Credit Note và số tiền còn phải thu của một chứng từ.", "Reconcile an invoice, its allocations, Credit Notes, and remaining outstanding amount."),
    primaryTasks: [
      task("reconcile", "Kiểm tra công thức số dư và từng dòng ledger tạo ra số tiền còn phải thu.", "Review the balance formula and each ledger item producing the outstanding amount."),
      task("allocate", "Phân bổ Payment hoặc Customer Credit khả dụng vào hóa đơn.", "Allocate available Payment or Customer Credit to the invoice.", [CAPABILITIES.PAYMENTS_ALLOCATE]),
      task("source", "Mở hóa đơn để kiểm tra nội dung chứng từ và trạng thái phát hành.", "Open the invoice to review document content and issue state.", [CAPABILITIES.INVOICES_READ]),
    ],
    relatedWorkflowIds: ["workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.RECEIVABLES_READ],
    commonMistakes: [text("Không phân bổ vượt số dư chứng từ hoặc số tiền còn khả dụng của nguồn Payment.", "Do not allocate beyond the invoice outstanding amount or the Payment source's available amount.")],
    keywords: text("chi tiết công nợ allocation hóa đơn credit note", "receivable detail allocation invoice credit note"),
  }),
  createScreenGuidance({
    id: "crm.receivables.statement",
    routeKey: "ACCOUNT_STATEMENT",
    productSpace: "crm",
    title: text("Sao kê công nợ", "Account statement"),
    purpose: text("Xem dòng thời gian Invoice, Allocation, Credit Note và số dư chạy theo một bên mua.", "Review the timeline of Invoices, Allocations, Credit Notes, and running balance for a buyer."),
    primaryTasks: [
      task("buyer", "Xác nhận đúng Contact hoặc Organization Account trước khi đọc sao kê.", "Confirm the correct Contact or Organization Account before reviewing the statement."),
      task("period", "Đối chiếu chứng từ và biến động theo kỳ kế toán.", "Reconcile documents and movements by accounting period."),
      task("trace", "Mở bản ghi nguồn khi một dòng sao kê cần giải thích.", "Open the source record when a statement line needs explanation.", [CAPABILITIES.RECEIVABLES_READ]),
    ],
    relatedWorkflowIds: ["workflow.relationship-management", "workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.RECEIVABLES_READ],
    commonMistakes: [text("Sao kê là read model; không dùng màn hình này để tạo hoặc sửa số dư.", "The statement is a read model; do not create or edit balances from this screen.")],
    keywords: text("sao kê công nợ khách hàng invoice allocation credit note", "account statement customer invoice allocation credit note"),
  }),
  createScreenGuidance({
    id: "crm.shipping.create",
    routeKey: "SHIPPING_NEW",
    productSpace: "crm",
    version: 2,
    title: text("Tạo vận đơn", "Create shipping booking"),
    purpose: text("Tạo yêu cầu giao nhận từ một đơn hàng đủ điều kiện với nhà vận chuyển và điểm lấy hàng phù hợp.", "Create a delivery request from an eligible order using the right provider and pickup location."),
    primaryTasks: [
      task("order", "Chọn đơn có hàng vật lý đã xác nhận và kiểm tra dữ liệu giao nhận chuẩn trên Order.", "Choose a confirmed order with physical lines and verify canonical delivery data on the Order."),
      task("provider", "Chọn nhà vận chuyển, điểm lấy hàng và dịch vụ phù hợp.", "Choose the provider, pickup location, and service."),
      task("create", "Kiểm tra COD, phí và thông tin người nhận trước khi gửi yêu cầu.", "Review COD, fees, and recipient information before submitting.", [CAPABILITIES.SHIPPING_CREATE]),
    ],
    relatedWorkflowIds: ["workflow.order-to-shipping"],
    requiredCapabilities: [CAPABILITIES.SHIPPING_CREATE],
    commonMistakes: [text("Không dùng snapshot vận đơn để sửa dữ liệu giao nhận còn thiếu trên Order; hãy cập nhật Order trước khi booking.", "Do not use the shipment snapshot to repair missing delivery data on the Order; update the Order before booking.")],
    keywords: text("tạo vận đơn nhà vận chuyển điểm lấy hàng COD", "create shipping booking provider pickup COD"),
  }),
  createScreenGuidance({
    id: "crm.shipping.detail",
    routeKey: "SHIPPING_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết vận đơn", "Shipping detail"),
    purpose: text("Theo dõi yêu cầu nội bộ, trạng thái nhà vận chuyển, lịch sử đồng bộ và bằng chứng giao hàng.", "Track the workspace request, provider status, synchronization history, and delivery evidence."),
    primaryTasks: [
      task("status", "Phân biệt trạng thái yêu cầu nội bộ và trạng thái bên nhà vận chuyển.", "Distinguish workspace request status from provider status."),
      task("sync", "Đồng bộ trạng thái khi cần bằng chứng mới từ nhà vận chuyển.", "Synchronize when fresh provider evidence is needed.", [CAPABILITIES.SHIPPING_CREATE]),
      task("retry", "Thử lại hoặc đổi nhà vận chuyển theo lịch sử và điều kiện cho phép.", "Retry or change provider according to history and allowed conditions.", [CAPABILITIES.SHIPPING_CREATE]),
    ],
    relatedWorkflowIds: ["workflow.order-to-shipping", "workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.SHIPPING_READ],
    commonMistakes: [text("Không coi trạng thái giao thành công là đủ nếu thiếu thời điểm và bằng chứng giao hàng.", "Do not treat delivered status as sufficient without delivery time and evidence.")],
    keywords: text("chi tiết vận đơn đồng bộ thử lại trạng thái giao hàng", "shipping detail sync retry provider status delivery"),
  }),
  createScreenGuidance({
    id: "crm.returns.create",
    routeKey: "RETURN_NEW",
    productSpace: "crm",
    version: 2,
    title: text("Tạo yêu cầu đổi / trả", "Create return request"),
    purpose: text("Ghi nhận sản phẩm, số lượng, lý do và phương án mong muốn cho một yêu cầu đổi hoặc trả hàng.", "Capture products, quantities, reason, and requested resolution for a return or exchange."),
    primaryTasks: [
      task("order", "Chọn đúng Order có hàng vật lý và các dòng hàng liên quan.", "Choose the correct Order with physical goods and its relevant line items."),
      task("quantity", "Nhập số lượng theo từng dòng và lý do yêu cầu.", "Enter quantities by line and the request reason."),
      task("evidence", "Dùng bằng chứng giao từ Shipping; nếu nhập thủ công phải đủ thời điểm, lý do và mã chứng từ.", "Use Shipping delivery evidence; manual evidence must include time, reason, and a reference."),
      task("resolution", "Chọn hoàn tiền, đổi hàng hoặc phương án khác được phép.", "Choose refund, replacement, or another allowed resolution.", [CAPABILITIES.RETURNS_UPDATE]),
    ],
    relatedWorkflowIds: ["workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.RETURNS_UPDATE],
    commonMistakes: [text("Không dùng luồng trả hàng vật lý cho Order chỉ có dịch vụ/sản phẩm số, và không biến thời điểm giao nhập tay thành bằng chứng trần.", "Do not use the physical-return flow for service/digital-only Orders or treat a manually entered delivery time as standalone evidence.")],
    keywords: text("tạo đổi trả dòng hàng số lượng lý do hoàn tiền đổi hàng", "create return line quantity reason refund replacement"),
  }),
  createScreenGuidance({
    id: "crm.returns.detail",
    routeKey: "RETURN_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết đổi / trả", "Return detail"),
    purpose: text("Theo dõi điều kiện, quyết định, nhận hàng và bằng chứng hoàn tất phương án xử lý.", "Track eligibility, decision, receipt, and evidence that completes the resolution."),
    primaryTasks: [
      task("eligibility", "Xem kết quả kiểm tra điều kiện trước khi quyết định.", "Review eligibility before making a decision."),
      task("receive", "Ghi số lượng thực nhận, chấp nhận và từ chối.", "Record received, accepted, and rejected quantities.", [CAPABILITIES.RETURNS_UPDATE]),
      task("resolve", "Hoàn tất sau khi có bằng chứng hoàn tiền hoặc giao hàng thay thế.", "Resolve only after refund or replacement-delivery evidence exists.", [CAPABILITIES.RETURNS_RESOLVE]),
    ],
    relatedWorkflowIds: ["workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.RETURNS_READ],
    commonMistakes: [text("Đủ điều kiện không tự động đồng nghĩa được phê duyệt; phê duyệt cũng không đồng nghĩa đã hoàn tất.", "Eligibility does not automatically mean approval, and approval does not mean completion.")],
    keywords: text("chi tiết đổi trả điều kiện phê duyệt nhận hàng xử lý", "return detail eligibility approval receipt resolution"),
  }),
  createScreenGuidance({
    id: "crm.contacts.list",
    routeKey: "CONTACTS",
    productSpace: "crm",
    version: 2,
    title: text("Liên hệ", "Contacts"),
    purpose: text("Quản lý hồ sơ cá nhân, thông tin liên lạc, quan hệ tổ chức và lịch sử tương tác.", "Manage individual profiles, contact details, organization relationships, and interaction history."),
    primaryTasks: [
      task("search", "Tìm và lọc liên hệ trước khi tạo mới để tránh trùng lặp.", "Search and filter before creating a contact to avoid duplicates."),
      task("create", "Tạo liên hệ với thông tin nhận diện và kênh liên lạc chính xác.", "Create a contact with accurate identity and communication details.", [CAPABILITIES.CONTACTS_CREATE]),
      task("assign", "Phân công người phụ trách theo phạm vi dữ liệu.", "Assign an owner within the permitted data scope.", [CAPABILITIES.CONTACTS_ASSIGN]),
    ],
    relatedWorkflowIds: ["workflow.relationship-management"],
    requiredCapabilities: [CAPABILITIES.CONTACTS_READ],
    commonMistakes: [
      text("Không tạo hồ sơ mới khi cùng một người đã tồn tại với email hoặc số điện thoại khác định dạng.", "Do not create a new record when the same person already exists with differently formatted email or phone data."),
      text("Không yêu cầu người dùng điền toàn bộ hồ sơ trước khi có lần chăm sóc đầu tiên.", "Do not require the complete profile before the first follow-up can be scheduled."),
    ],
    additionalSteps: [
      { id: "quick-create", targetId: "contacts.form.progressive-profile", title: text("Tạo liên hệ nhanh", "Quick-create a contact"), body: text("Bắt đầu bằng tên, kênh liên hệ, tổ chức nếu có, lịch chăm sóc và người phụ trách; bổ sung dữ liệu nâng cao sau.", "Start with name, contact channel, organization when known, follow-up time, and owner; enrich advanced data later."), placement: "top", expectedAction: "view", optional: true, requiredCapabilities: [CAPABILITIES.CONTACTS_CREATE] },
    ],
    keywords: text("liên hệ cá nhân email điện thoại tổ chức người phụ trách tạo nhanh", "contact person email phone organization owner quick create"),
  }),
  createScreenGuidance({
    id: "crm.contacts.detail",
    routeKey: "CONTACT_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết liên hệ", "Contact detail"),
    purpose: text("Xem hồ sơ cá nhân, quan hệ, hoạt động và các bản ghi thương mại hoặc hỗ trợ liên quan.", "Review the person's profile, relationships, activities, and related commercial or support records."),
    primaryTasks: [
      task("identity", "Kiểm tra thông tin nhận diện và kênh liên lạc ưu tiên.", "Verify identity and preferred communication channels."),
      task("relationship", "Xem hoặc cập nhật quan hệ với tổ chức khi phù hợp.", "Review or update the organization relationship when appropriate.", [CAPABILITIES.CONTACTS_UPDATE]),
      task("history", "Dùng lịch sử để hiểu ngữ cảnh trước khi liên hệ hoặc cập nhật.", "Use history to understand context before contacting or updating.")
    ],
    relatedWorkflowIds: ["workflow.relationship-management"],
    requiredCapabilities: [CAPABILITIES.CONTACTS_READ],
    commonMistakes: [text("Không dùng liên hệ thay cho tổ chức hoặc khách hàng khi nghiệp vụ cần một đối tượng khác.", "Do not use a contact as a substitute for an organization or customer when the process requires another record type.")],
    keywords: text("chi tiết liên hệ quan hệ hoạt động lịch sử", "contact detail relationship activity history"),
  }),
  createScreenGuidance({
    id: "crm.organizations.list",
    routeKey: "ORGANIZATIONS",
    productSpace: "crm",
    title: text("Tổ chức", "Organizations"),
    purpose: text("Quản lý doanh nghiệp, đơn vị hoặc tài khoản B2B cùng người đại diện và quan hệ thương mại.", "Manage companies, units, or B2B accounts with representatives and commercial relationships."),
    primaryTasks: [
      task("search", "Tìm theo tên, mã hoặc thông tin nhận diện trước khi tạo mới.", "Search by name, code, or identity before creating a record."),
      task("create", "Tạo tổ chức với thông tin pháp lý và thương mại cần thiết.", "Create an organization with required legal and commercial information.", [CAPABILITIES.ORGANIZATIONS_CREATE]),
      task("representatives", "Liên kết người đại diện và vai trò phù hợp.", "Link representatives with the appropriate relationship roles.", [CAPABILITIES.ORGANIZATIONS_UPDATE]),
    ],
    relatedWorkflowIds: ["workflow.relationship-management"],
    requiredCapabilities: [CAPABILITIES.ORGANIZATIONS_READ],
    commonMistakes: [text("Không gộp các pháp nhân hoặc chi nhánh khác nhau chỉ vì tên thương hiệu giống nhau.", "Do not merge distinct legal entities or branches merely because they share a brand name.")],
    keywords: text("tổ chức doanh nghiệp B2B người đại diện pháp nhân", "organization company B2B representative legal organization"),
  }),
  createScreenGuidance({
    id: "crm.organizations.detail",
    routeKey: "ORGANIZATION_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết tổ chức", "Organization detail"),
    purpose: text("Xem hồ sơ doanh nghiệp, người đại diện, cơ hội, giao dịch và hoạt động liên quan.", "Review the company profile, representatives, opportunities, transactions, and related activity."),
    primaryTasks: [
      task("profile", "Kiểm tra thông tin nhận diện, địa chỉ và trạng thái hoạt động.", "Verify identity, address, and operating status."),
      task("people", "Rà soát người đại diện và vai trò của từng liên hệ.", "Review representatives and each contact's role."),
      task("commercial", "Mở cơ hội, báo giá, đơn hàng hoặc hóa đơn để xử lý giao dịch.", "Open opportunities, quotes, orders, or invoices to work on transactions."),
      task("activity", "Ghi nhận cuộc gọi, lịch hẹn, ghi chú và công việc ngay trên bảng tương tác mà không làm mất ngữ cảnh hồ sơ.", "Log calls, meetings, notes, and tasks from the interaction panel without losing record context."),
      task("attachments", "Lưu tài liệu pháp lý, hợp đồng và tài liệu quan hệ trong khu vực Tài liệu đính kèm.", "Keep legal documents, contracts, and relationship files in Attachments.")
    ],
    relatedWorkflowIds: ["workflow.relationship-management", "workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.ORGANIZATIONS_READ],
    commonMistakes: [text("Không cập nhật dữ liệu giao dịch trực tiếp trong hồ sơ tổ chức khi bản ghi nguồn có khu vực sở hữu riêng.", "Do not edit transaction evidence from the organization profile when the source record has its own operating area.")],
    keywords: text("chi tiết tổ chức người đại diện giao dịch hoạt động", "organization detail representatives transactions activity"),
  }),
  createScreenGuidance({
    id: "crm.customers.list",
    routeKey: "CUSTOMERS",
    productSpace: "crm",
    title: text("Khách hàng", "Customers"),
    purpose: text("Theo dõi quan hệ khách hàng đã hình thành từ cá nhân hoặc tổ chức cùng lịch sử mua và chăm sóc.", "Track established customer relationships from people or organizations with purchase and care history."),
    primaryTasks: [
      task("search", "Tìm khách hàng theo tên, người phụ trách hoặc trạng thái quan hệ.", "Search customers by name, owner, or relationship state."),
      task("review", "Mở hồ sơ để xem sức khỏe quan hệ, giao dịch và hỗ trợ.", "Open a profile to review relationship health, transactions, and support."),
      task("assign", "Điều chỉnh người phụ trách khi trách nhiệm chăm sóc thay đổi.", "Change the owner when relationship responsibility changes.", [CAPABILITIES.CUSTOMERS_ASSIGN]),
    ],
    relatedWorkflowIds: ["workflow.relationship-management"],
    requiredCapabilities: [CAPABILITIES.CUSTOMERS_VIEW],
    commonMistakes: [text("Khách hàng là quan hệ nghiệp vụ, không phải bản sao của Liên hệ hoặc Tổ chức.", "A customer is a business relationship, not a duplicate of a Contact or Organization.")],
    keywords: text("khách hàng quan hệ người phụ trách giao dịch chăm sóc", "customer relationship owner transaction care"),
  }),
  createScreenGuidance({
    id: "crm.customers.detail",
    routeKey: "CUSTOMER_DETAIL",
    productSpace: "crm",
    title: text("Hồ sơ khách hàng", "Customer profile"),
    purpose: text("Tổng hợp sức khỏe quan hệ, lịch sử thương mại, hỗ trợ và tín hiệu cần hành động của khách hàng.", "Bring together relationship health, commercial history, support, and signals that need action."),
    primaryTasks: [
      task("overview", "Đọc tổng quan quan hệ và các cảnh báo trước khi xử lý.", "Review relationship overview and alerts before acting."),
      task("integrity", "Kiểm tra trạng thái nhất quán để biết Contact/Organization và giao dịch có cùng một quan hệ chuẩn hay không.", "Check relationship integrity to confirm Contact/Organization and transactions resolve to one canonical relationship."),
      task("history", "Mở bản ghi nguồn để kiểm tra giao dịch hoặc phiếu hỗ trợ.", "Open source records to inspect transactions or support tickets."),
      task("update", "Cập nhật thông tin quan hệ thuộc phạm vi được phép.", "Update relationship information within your access scope.", [CAPABILITIES.CUSTOMERS_EDIT]),
    ],
    additionalSteps: [{
      id: "relationship-integrity",
      targetId: "customers.detail.relationship-integrity",
      title: text("Kiểm tra tính nhất quán quan hệ", "Review relationship integrity"),
      body: text("Trạng thái này phát hiện liên kết mồ côi, sai Customer và ứng viên trùng có thể làm thiếu lịch sử trên Customer 360.", "This status detects orphan links, Customer mismatches, and duplicate candidates that may make Customer 360 incomplete."),
      placement: "bottom",
      expectedAction: "view",
    }],
    relatedWorkflowIds: ["workflow.relationship-management", "workflow.support-to-task"],
    requiredCapabilities: [CAPABILITIES.CUSTOMERS_VIEW],
    commonMistakes: [text("Không suy diễn trạng thái khách hàng chỉ từ một chỉ số hoặc một giao dịch đơn lẻ.", "Do not infer customer state from a single metric or transaction.")],
    keywords: text("hồ sơ khách hàng 360 sức khỏe giao dịch hỗ trợ tín hiệu", "customer profile 360 health transaction support signal"),
  }),
  createScreenGuidance({
    id: "crm.customers.segments",
    routeKey: "CUSTOMER_SEGMENTS",
    productSpace: "crm",
    title: text("Phân khúc khách hàng", "Customer segments"),
    purpose: text("Nhóm khách hàng theo tiêu chí để ưu tiên chăm sóc, phân tích hoặc vận hành.", "Group customers by criteria for care prioritization, analysis, or operations."),
    primaryTasks: [
      task("review", "Đọc tiêu chí và số lượng khách hàng trong từng phân khúc.", "Review criteria and customer counts for each segment."),
      task("inspect", "Mở danh sách thành viên để kiểm tra kết quả phân nhóm.", "Open segment membership to inspect grouping results."),
      task("apply", "Dùng phân khúc làm đầu vào tham khảo, không thay thế kiểm tra hồ sơ.", "Use segments as a planning input, not a replacement for profile review.")
    ],
    relatedWorkflowIds: ["workflow.relationship-management"],
    requiredCapabilities: [CAPABILITIES.CUSTOMERS_VIEW],
    commonMistakes: [text("Không coi phân khúc là nhãn cố định nếu tiêu chí hoặc dữ liệu khách hàng có thể thay đổi.", "Do not treat a segment as permanent when criteria or customer data can change.")],
    keywords: text("phân khúc khách hàng nhóm tiêu chí ưu tiên", "customer segment group criteria priority"),
  }),
  createScreenGuidance({
    id: "crm.customers.health",
    routeKey: "CUSTOMER_HEALTH",
    productSpace: "crm",
    title: text("Sức khỏe khách hàng", "Customer health"),
    purpose: text("Theo dõi tín hiệu quan hệ và mức độ cần chú ý để ưu tiên hành động chăm sóc.", "Track relationship signals and attention level to prioritize customer-care actions."),
    primaryTasks: [
      task("review", "Đọc chỉ số và yếu tố tạo nên mức sức khỏe.", "Review the score and factors behind the health level."),
      task("prioritize", "Ưu tiên khách hàng có rủi ro hoặc tín hiệu mới.", "Prioritize customers with risk or fresh signals."),
      task("open", "Mở hồ sơ và bản ghi nguồn trước khi quyết định hành động.", "Open the profile and source records before deciding an action.")
    ],
    relatedWorkflowIds: ["workflow.relationship-management", "workflow.support-to-task"],
    requiredCapabilities: [CAPABILITIES.CUSTOMERS_VIEW],
    commonMistakes: [text("Chỉ số sức khỏe là tín hiệu hỗ trợ, không phải kết luận tuyệt đối về quan hệ.", "Customer health is a decision signal, not an absolute conclusion about the relationship.")],
    keywords: text("sức khỏe khách hàng rủi ro tín hiệu ưu tiên", "customer health risk signal priority"),
  }),
  createScreenGuidance({
    id: "crm.support.create",
    routeKey: "SUPPORT_CASE_NEW",
    productSpace: "crm",
    title: text("Tạo phiếu hỗ trợ", "Create support ticket"),
    purpose: text("Ghi nhận yêu cầu, khách hàng, mức ưu tiên, người phụ trách và lần theo dõi tiếp theo.", "Capture the request, customer, priority, owner, and next follow-up."),
    primaryTasks: [
      task("context", "Chọn đúng khách hàng hoặc liên hệ và mô tả vấn đề rõ ràng.", "Choose the correct customer or contact and describe the issue clearly."),
      task("priority", "Đặt loại yêu cầu, mức ưu tiên và người phụ trách.", "Set request type, priority, and owner."),
      task("save", "Đặt lần hẹn tiếp theo trước khi lưu khi cần theo dõi.", "Set the next follow-up before saving when further work is needed.", [CAPABILITIES.SUPPORT_CREATE]),
    ],
    relatedWorkflowIds: ["workflow.support-to-task"],
    requiredCapabilities: [CAPABILITIES.SUPPORT_CREATE],
    commonMistakes: [text("Không dùng phiếu hỗ trợ để thay cho công việc cụ thể cần giao cho một người với hạn xử lý.", "Do not use a support ticket as a substitute for a concrete assigned task with a due time.")],
    keywords: text("tạo phiếu hỗ trợ khách hàng ưu tiên người phụ trách hẹn tiếp", "create support ticket customer priority owner follow-up"),
  }),
  createScreenGuidance({
    id: "crm.support.detail",
    routeKey: "SUPPORT_CASE_DETAIL",
    productSpace: "crm",
    title: text("Chi tiết phiếu hỗ trợ", "Support ticket detail"),
    purpose: text("Theo dõi ngữ cảnh khách hàng, tiến trình xử lý, người phụ trách và kết quả của yêu cầu hỗ trợ.", "Track customer context, progress, owner, and resolution of a support request."),
    primaryTasks: [
      task("review", "Đọc yêu cầu, lịch sử và lần hẹn tiếp theo.", "Review the request, history, and next follow-up."),
      task("update", "Cập nhật tiến trình, người phụ trách và ghi chú xử lý.", "Update progress, owner, and handling notes.", [CAPABILITIES.SUPPORT_UPDATE]),
      task("complete", "Chỉ đóng khi kết quả đã được ghi nhận rõ ràng.", "Close only when the outcome is clearly recorded.", [CAPABILITIES.SUPPORT_COMPLETE]),
    ],
    relatedWorkflowIds: ["workflow.support-to-task"],
    requiredCapabilities: [CAPABILITIES.SUPPORT_READ],
    commonMistakes: [text("Không đóng phiếu chỉ vì đã tạo một công việc; phiếu cần phản ánh kết quả hỗ trợ cuối cùng.", "Do not close a ticket merely because a task was created; the ticket must reflect the final support outcome.")],
    keywords: text("chi tiết phiếu hỗ trợ tiến trình xử lý kết quả", "support ticket detail progress resolution"),
  }),
  createScreenGuidance({
    id: "crm.support.edit",
    routeKey: "SUPPORT_CASE_EDIT",
    productSpace: "crm",
    title: text("Chỉnh sửa phiếu hỗ trợ", "Edit support ticket"),
    purpose: text("Điều chỉnh thông tin yêu cầu, mức ưu tiên, người phụ trách và kế hoạch theo dõi.", "Adjust request details, priority, owner, and follow-up plan."),
    primaryTasks: [
      task("review", "Kiểm tra lịch sử trước khi thay đổi thông tin quan trọng.", "Review history before changing important information."),
      task("update", "Cập nhật trường cần thiết và giữ nguyên bằng chứng đã ghi nhận.", "Update necessary fields while preserving recorded evidence.", [CAPABILITIES.SUPPORT_UPDATE]),
      task("save", "Xác nhận người phụ trách và lần hẹn tiếp theo trước khi lưu.", "Confirm the owner and next follow-up before saving.", [CAPABILITIES.SUPPORT_UPDATE]),
    ],
    relatedWorkflowIds: ["workflow.support-to-task"],
    requiredCapabilities: [CAPABILITIES.SUPPORT_UPDATE],
    commonMistakes: [text("Không ghi đè nội dung cũ làm mất ngữ cảnh; dùng lịch sử hoặc ghi chú xử lý khi phù hợp.", "Do not overwrite prior context; use history or handling notes when appropriate.")],
    keywords: text("chỉnh sửa phiếu hỗ trợ ưu tiên người phụ trách hẹn tiếp", "edit support ticket priority owner follow-up"),
  }),
];
