import { CAPABILITIES } from "@/platform/access-control/domain/capabilityCatalog";
import type { ScreenGuidance } from "@/guidance/domain/guidance.types";

const reviewedAt = "2026-07-12";
const owner = "Product Enablement";

export const CRM_SCREEN_GUIDANCE: ScreenGuidance[] = [
  {
    id: "crm.dashboard.overview",
    routeKey: "DASHBOARD",
    productSpace: "crm",
    version: 4,
    title: { vi: "Tổng quan CRM", en: "CRM overview" },
    purpose: { vi: "Theo dõi nhanh khối lượng công việc, khách hàng tiềm năng, cơ hội, doanh thu và các yêu cầu đang cần xử lý.", en: "Review workload, leads, opportunities, revenue, and customer requests that need attention." },
    audience: { vi: "Nhân viên bán hàng, vận hành, chăm sóc khách hàng và quản lý.", en: "Sales, operations, customer care, and managers." },
    prerequisites: [{ vi: "Bạn cần quyền xem Tổng quan.", en: "You need permission to view the Dashboard." }],
    primaryTasks: [
      { id: "review-metrics", text: { vi: "Mở từng KPI để xem công thức, kỳ tính, thời điểm cập nhật và bản ghi nguồn.", en: "Open each KPI to inspect its formula, period, freshness, and source records." } },
      { id: "open-leads", text: { vi: "Mở khách hàng tiềm năng cần theo dõi.", en: "Open leads that need follow-up." }, route: "leads", requiredCapabilities: [CAPABILITIES.LEADS_READ] },
      { id: "open-tasks", text: { vi: "Mở công việc được giao và ưu tiên việc quá hạn.", en: "Open assigned tasks and prioritize overdue work." }, route: "tasks", requiredCapabilities: [CAPABILITIES.TASKS_READ] },
    ],
    commonMistakes: [
      { vi: "Không suy diễn tăng trưởng khi kỳ trước bằng 0; hệ thống sẽ ghi rõ khi không thể tính phần trăm so sánh.", en: "Do not infer growth when the previous period is zero; the system explicitly marks the comparison as unavailable." },
      { vi: "Tìm kiếm toàn cục chỉ trả về bản ghi trong phạm vi quyền hiện tại; trạng thái rỗng không xác nhận sự tồn tại của bản ghi bị ẩn.", en: "Global search only returns records in the current access scope; its empty state does not confirm whether hidden records exist." },
    ],
    relatedWorkflowIds: ["workflow.lead-to-order", "workflow.support-to-task"],
    steps: [
      { id: "screen", targetId: "dashboard.overview.screen", title: { vi: "Tổng quan trong ngày", en: "Today at a glance" }, body: { vi: "Bắt đầu từ chỉ số và các hàng đợi đang cần hành động, sau đó mở bản ghi gốc để xử lý.", en: "Start with metrics and action queues, then open the source record to work on it." }, placement: "bottom", expectedAction: "view" },
      { id: "metric", targetId: "dashboard.metric.completed-revenue", title: { vi: "KPI có thể kiểm chứng", en: "Verifiable KPI" }, body: { vi: "Chọn thẻ để xem công thức, kỳ tính, múi giờ và các đơn hàng nguồn. Khi kỳ trước bằng 0, hệ thống không hiển thị tỷ lệ tăng trưởng giả.", en: "Select the card to inspect formula, period, timezone, and source orders. When the previous period is zero, no fabricated growth rate is shown." }, placement: "bottom", expectedAction: "click", requiredCapabilities: [CAPABILITIES.REPORTS_READ, CAPABILITIES.ORDERS_READ] },
      { id: "role-navigation", targetId: "shell.navigation.profile", title: { vi: "Không gian theo vai trò", en: "Role-focused workspace" }, body: { vi: "Sidebar ưu tiên các khu vực phù hợp với trách nhiệm hiện tại. Màn hình liên quan ở bộ phận khác vẫn có thể mở ở chế độ chỉ xem khi quyền cho phép.", en: "The sidebar prioritizes areas relevant to your current responsibility. Related cross-team screens can still open read-only when access permits." }, placement: "right", expectedAction: "view" },
      { id: "spaces", targetId: "shell.product-space.crm", title: { vi: "Chuyển khu vực làm việc", en: "Switch work areas" }, body: { vi: "Dùng thanh này để chuyển giữa CRM, Thiết lập và Người dùng & Quyền khi bạn có quyền truy cập.", en: "Use this navigation to move between CRM, Settings, and Users & Access when permitted." }, placement: "bottom", expectedAction: "view" },
    ],
    requiredCapabilities: [CAPABILITIES.DASHBOARD_READ],
    keywords: { vi: "tổng quan chỉ số doanh thu công việc hôm nay", en: "dashboard metrics revenue tasks today" },
    owner,
    reviewedAt: "2026-07-13",
  },
  {
    id: "crm.leads.list",
    routeKey: "LEADS",
    productSpace: "crm",
    version: 4,
    title: { vi: "Khách hàng tiềm năng", en: "Leads" },
    purpose: { vi: "Tiếp nhận, phân công, xác minh nhu cầu và quyết định bước bán hàng tiếp theo cho khách hàng tiềm năng.", en: "Capture, assign, verify, and determine the next selling outcome for leads." },
    prerequisites: [{ vi: "Có quyền xem khách hàng tiềm năng; quyền tạo, sửa, giao hoặc chốt kết quả được kiểm tra riêng.", en: "Lead read permission is required; create, update, assign, and qualification permissions are checked separately." }],
    primaryTasks: [
      { id: "create", text: { vi: "Dùng Tạo nhanh để lưu tên và ít nhất một kênh liên hệ; bổ sung nguồn, giá trị dự kiến và lịch chăm sóc khi đã biết.", en: "Use Quick Create to save a name and at least one contact channel; add source, estimated value, and follow-up when known." }, requiredCapabilities: [CAPABILITIES.LEADS_CREATE] },
      { id: "qualify", text: { vi: "Xác minh và chốt kết quả phù hợp: tạo quan hệ, tạo cơ hội hoặc bán trực tiếp.", en: "Verify and resolve the appropriate outcome: relationship, opportunity, or direct sale." }, requiredCapabilities: [CAPABILITIES.LEADS_QUALIFY] },
      { id: "assign", text: { vi: "Phân công người phụ trách theo phạm vi dữ liệu được phép.", en: "Assign an owner within the permitted data scope." }, requiredCapabilities: [CAPABILITIES.LEADS_ASSIGN] },
    ],
    commonMistakes: [
      { vi: "Không dùng một trạng thái gộp để suy diễn cả tiến độ làm việc và kết quả xác minh.", en: "Do not treat work progress and qualification outcome as one combined status." },
      { vi: "Không nhập dữ liệu đối phó vào trường nâng cao; yêu cầu bổ sung sẽ xuất hiện khi Lead chuyển lifecycle.", en: "Do not enter placeholder data in advanced fields; additional requirements appear as the Lead advances through its lifecycle." },
      { vi: "Nội dung biểu mẫu có thể cuộn, nhưng thanh Hủy/Lưu luôn nằm ngoài vùng cuộn ở cuối cửa sổ.", en: "The form body may scroll, while Cancel and Save remain outside the scroll area at the bottom of the dialog." },
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    steps: [
      { id: "saved-view", targetId: "leads.list.saved-view", title: { vi: "Chọn giao diện Lead", en: "Choose a Lead view" }, body: { vi: "Dùng Tất cả tiềm năng, Lead của tôi, Lead của đội hoặc giao diện đã lưu để áp dụng phạm vi và bộ lọc phù hợp mà không cần thêm một cụm chọn trùng lặp trên thanh công cụ.", en: "Use All Leads, My Leads, Team Leads, or a saved view to apply the appropriate scope and filters without a duplicate scope control in the toolbar." }, placement: "bottom", expectedAction: "select" },
      { id: "create", targetId: "leads.list.create", title: { vi: "Tạo Lead đúng owner", en: "Create with the correct owner" }, body: { vi: "Lead mới mặc định giao cho bạn. Chỉ người có quyền phân công mới được chọn người khác; sau khi lưu có thể mở bản ghi ngay.", en: "A new Lead is assigned to you by default. Only an authorized assigner can choose someone else, and the saved record can be opened immediately." }, placement: "left", expectedAction: "click", requiredCapabilities: [CAPABILITIES.LEADS_CREATE] },
      { id: "quick-profile", targetId: "leads.form.progressive-profile", title: { vi: "Nhập vừa đủ để tiếp nhận", en: "Capture only what intake needs" }, body: { vi: "Chỉ cần tên và một kênh liên hệ để tạo Lead. Hệ thống tự giao cho thành viên hiện tại; mở phần nâng cao khi đã có nguồn, giá trị hoặc lịch chăm sóc.", en: "A name and one contact channel are enough to create a Lead. The system assigns the current member; open advanced details when source, value, or follow-up is known." }, placement: "top", expectedAction: "view", optional: true, requiredCapabilities: [CAPABILITIES.LEADS_CREATE] },
    ],
    requiredCapabilities: [CAPABILITIES.LEADS_READ],
    keywords: { vi: "lead khách hàng tiềm năng phân công xác minh chuyển đổi", en: "lead assign verify qualify convert" },
    owner,
    reviewedAt: "2026-07-13",
  },
  {
    id: "crm.deals.pipeline",
    routeKey: "DEALS",
    productSpace: "crm",
    version: 4,
    title: { vi: "Cơ hội bán hàng", en: "Sales opportunities" },
    purpose: { vi: "Theo dõi cơ hội theo giai đoạn, giá trị, người phụ trách và bước tiếp theo cho đến khi thắng hoặc thua.", en: "Track opportunities by stage, value, owner, and next step until won or lost." },
    prerequisites: [{ vi: "Cơ hội chỉ xuất hiện khi workspace bật quy trình cơ hội và bạn có quyền xem.", en: "Opportunities appear only when the workspace enables the opportunity path and you have read access." }],
    primaryTasks: [
      { id: "create", text: { vi: "Tạo cơ hội khi nhu cầu đã đủ rõ để theo dõi pipeline.", en: "Create an opportunity when the need is clear enough for pipeline tracking." }, requiredCapabilities: [CAPABILITIES.DEALS_CREATE] },
      { id: "progress", text: { vi: "Ưu tiên cơ hội thiếu hoặc quá hạn bước tiếp theo, ở stage quá lâu hoặc không có tương tác gần đây.", en: "Prioritize opportunities with a missing or overdue next step, excessive time in stage, or stale activity." }, requiredCapabilities: [CAPABILITIES.DEALS_UPDATE] },
      { id: "close", text: { vi: "Chốt thắng hoặc thua bằng hành động kết thúc chuyên biệt.", en: "Close as won or lost through the dedicated closing action." }, requiredCapabilities: [CAPABILITIES.DEALS_CLOSE] },
    ],
    commonMistakes: [
      { vi: "Không kéo cơ hội sang trạng thái kết thúc chỉ để làm sạch pipeline; cần ghi nhận bằng chứng và lý do.", en: "Do not close an opportunity merely to clean the pipeline; record evidence and reason." },
      { vi: "Bên mua của cơ hội chưa phải Customer 360; hồ sơ Customer chỉ xuất hiện sau bằng chứng mua hàng hoàn tất.", en: "An opportunity buyer is not yet a Customer 360 record; the Customer appears only after completed-purchase evidence." },
      { vi: "Bộ chọn sản phẩm chỉ hiển thị danh mục đang bán của workspace, không phụ thuộc người sở hữu cơ hội.", en: "The product picker shows the workspace sellable catalog and does not depend on opportunity ownership." },
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    steps: [
      { id: "scope", targetId: "deals.pipeline.scope", title: { vi: "Phạm vi pipeline", en: "Pipeline scope" }, body: { vi: "Chuyển giữa cơ hội của bạn, của đội và toàn bộ cơ hội được phép xem mà không thay đổi quyền dữ liệu.", en: "Switch between your opportunities, your team's opportunities, and all allowed opportunities without changing data permissions." }, placement: "bottom", expectedAction: "select" },
      { id: "owner", targetId: "deals.form.owner", title: { vi: "Người phụ trách cơ hội", en: "Opportunity owner" }, body: { vi: "Cơ hội mới mặc định thuộc người tạo. Bàn giao cho người khác chỉ khả dụng theo quyền và luôn yêu cầu lý do.", en: "A new opportunity belongs to its creator by default. Handover is permission-controlled and always requires a reason." }, placement: "right", expectedAction: "view", requiredCapabilities: [CAPABILITIES.DEALS_CREATE] },
      { id: "health", targetId: "deals.pipeline.health-indicators", title: { vi: "Nhận biết cơ hội cần hành động", en: "Spot opportunities that need action" }, body: { vi: "Các nhãn cho biết số ngày ở stage, thời gian từ tương tác gần nhất, bước tiếp theo thiếu/quá hạn, độ stale và forecast category.", en: "Indicators show days in stage, time since last activity, missing or overdue next steps, staleness, and forecast category." }, placement: "bottom", expectedAction: "view" },
      { id: "quick-create", targetId: "deals.form.progressive-profile", title: { vi: "Tạo cơ hội theo từng mức dữ liệu", en: "Create opportunities progressively" }, body: { vi: "Lưu nhanh người mua, giá trị, ngày đóng và bước tiếp theo; chỉ mở dữ liệu nâng cao khi cần cập nhật stage, xác suất hoặc nhóm dự báo.", en: "Quickly capture buyer, value, close date, and next step; open advanced data only for stage, probability, or forecast updates." }, placement: "top", expectedAction: "view", optional: true, requiredCapabilities: [CAPABILITIES.DEALS_CREATE] },
    ],
    requiredCapabilities: [CAPABILITIES.DEALS_READ],
    owner,
    reviewedAt: "2026-07-13",
  },
  {
    id: "crm.quotes.list",
    routeKey: "QUOTES",
    productSpace: "crm",
    version: 2,
    title: { vi: "Báo giá", en: "Quotes" },
    purpose: { vi: "Lập đề xuất thương mại, kiểm soát phiên bản và phê duyệt trước khi khách hàng chấp nhận.", en: "Prepare commercial proposals, control revisions, and approve them before customer acceptance." },
    prerequisites: [{ vi: "Báo giá có thể bắt nguồn từ cơ hội hoặc luồng bán trực tiếp, tùy cấu hình workspace.", en: "A quote may start from an opportunity or direct sale, depending on workspace configuration." }],
    primaryTasks: [
      { id: "create", text: { vi: "Tạo báo giá và chọn sản phẩm, giá, thuế và điều khoản.", en: "Create a quote with products, pricing, tax, and terms." }, requiredCapabilities: [CAPABILITIES.QUOTES_CREATE] },
      { id: "approve", text: { vi: "Phê duyệt báo giá trước khi phát hành khi chính sách yêu cầu.", en: "Approve a quote before issuance when policy requires it." }, requiredCapabilities: [CAPABILITIES.QUOTES_APPROVE] },
      { id: "deliver", text: { vi: "Gửi qua Gmail hoặc xác nhận kênh đã gửi như Zalo, ứng dụng chat, SMS và email khác.", en: "Send with Gmail or confirm delivery through Zalo, a chat app, SMS, or another email channel." }, requiredCapabilities: [CAPABILITIES.QUOTES_UPDATE] },
      { id: "order", text: { vi: "Tạo đơn hàng từ báo giá đã được chấp nhận.", en: "Create an order from an accepted quote." }, requiredCapabilities: [CAPABILITIES.ORDERS_CREATE] },
    ],
    commonMistakes: [
      { vi: "Không xác nhận đã gửi trước khi Báo giá thực sự đến kênh liên hệ của khách.", en: "Do not confirm delivery before the quote actually reaches the customer's contact channel." },
      { vi: "Không sửa trực tiếp bằng chứng báo giá đã phát hành; hãy tạo phiên bản tiếp theo khi cần thay đổi.", en: "Do not overwrite issued quote evidence; create the next revision when changes are needed." },
    ],
    relatedWorkflowIds: ["workflow.lead-to-order"],
    requiredCapabilities: [CAPABILITIES.QUOTES_READ],
    owner,
    reviewedAt,
  },
  {
    id: "crm.orders.list",
    routeKey: "ORDERS",
    productSpace: "crm",
    version: 3,
    title: { vi: "Đơn hàng", en: "Orders" },
    purpose: { vi: "Quản lý cam kết mua đã xác nhận và theo dõi bằng chứng Thanh toán, Vận đơn và Đổi/Trả liên quan.", en: "Manage confirmed purchase commitments and follow the related Payment, Shipping, and Return evidence." },
    prerequisites: [{ vi: "Bạn cần quyền xem đơn hàng. Tạo đơn yêu cầu thông tin người mua, người nhận, sản phẩm và điều kiện vận hành hợp lệ.", en: "Order read access is required. Creating an order requires valid buyer, recipient, product, and operational information." }],
    primaryTasks: [
      { id: "create", text: { vi: "Tạo đơn hàng mới hoặc tạo từ báo giá đã chấp nhận.", en: "Create a new order or create one from an accepted quote." }, route: "orders/new", requiredCapabilities: [CAPABILITIES.ORDERS_CREATE] },
      { id: "payment", text: { vi: "Mở Thanh toán để ghi nhận khoản thu; không cập nhật trạng thái thanh toán trực tiếp trên đơn.", en: "Open Payments to record collections; do not change payment state directly on the order." }, route: "payments", requiredCapabilities: [CAPABILITIES.PAYMENTS_READ] },
      { id: "shipping", text: { vi: "Tạo vận đơn khi đơn đã xác nhận và có đủ thông tin giao nhận.", en: "Create a shipping booking after confirmation and when delivery information is complete." }, route: "shipping", requiredCapabilities: [CAPABILITIES.SHIPPING_READ] },
    ],
    commonMistakes: [
      { vi: "Thanh toán và Vận đơn là dữ liệu do khu vực riêng sở hữu; Đơn hàng chỉ tổng hợp bằng chứng liên quan.", en: "Payment and Shipping are owned separately; the Order only summarizes related evidence." },
      { vi: "Không lưu trữ đơn hàng chỉ để sửa sai dữ liệu; ưu tiên hiệu chỉnh hoặc hủy theo điều kiện nghiệp vụ.", en: "Do not archive an order merely to correct data; edit or cancel according to business rules." },
    ],
    relatedWorkflowIds: ["workflow.order-to-shipping", "workflow.order-return-resolution"],
    steps: [
      { id: "screen", targetId: "orders.list.screen", title: { vi: "Hàng đợi đơn hàng", en: "Order work queue" }, body: { vi: "Dùng tìm kiếm, chế độ xem và bộ lọc để tìm đơn cần xử lý. Mở chi tiết trước khi thực hiện hành động trạng thái.", en: "Use search, views, and filters to find orders that need work. Open details before changing state." }, placement: "bottom", expectedAction: "view" },
      { id: "create", targetId: "orders.list.create", title: { vi: "Tạo đơn hàng", en: "Create an order" }, body: { vi: "Hành động này chỉ khả dụng khi vai trò có quyền tạo đơn hàng.", en: "This action is available only when your role can create orders." }, placement: "left", expectedAction: "click", route: "orders/new", requiredCapabilities: [CAPABILITIES.ORDERS_CREATE] },
      { id: "read-only", targetId: "access.read-only.notice", title: { vi: "Theo dõi xuyên bộ phận", en: "Cross-team visibility" }, body: { vi: "Khi chỉ có quyền xem, bạn vẫn theo dõi được trạng thái đơn hàng nhưng các hành động cập nhật thuộc đội chịu trách nhiệm sẽ không xuất hiện.", en: "With read access only, you can still follow order status while update actions owned by the responsible team remain unavailable." }, placement: "bottom", expectedAction: "view", optional: true },
    ],
    requiredCapabilities: [CAPABILITIES.ORDERS_READ],
    keywords: { vi: "đơn hàng tạo đơn xác nhận thanh toán vận đơn", en: "orders create confirm payment shipping" },
    owner,
    reviewedAt,
  },
  {
    id: "crm.orders.create",
    routeKey: "ORDER_NEW",
    productSpace: "crm",
    version: 3,
    title: { vi: "Tạo đơn hàng", en: "Create order" },
    purpose: { vi: "Ghi nhận một cam kết mua hợp lệ với người mua, người nhận, sản phẩm, kế hoạch thanh toán và thông tin giao hàng.", en: "Record a valid purchase commitment with buyer, recipient, products, payment plan, and delivery information." },
    audience: { vi: "Nhân viên bán hàng hoặc vận hành có quyền tạo đơn.", en: "Sales or operations users with order create access." },
    prerequisites: [
      { vi: "Buyer phải là Contact hoặc Organization hợp lệ; đơn có hàng vật lý cần tên, số điện thoại và địa chỉ giao hàng hợp lệ.", en: "The buyer must be a valid Contact or Organization; physical or mixed orders need a valid recipient name, phone, and delivery address." },
      { vi: "Đơn hàng cần ít nhất một dòng sản phẩm hợp lệ.", en: "The order needs at least one valid product line." },
    ],
    primaryTasks: [
      { id: "buyer", text: { vi: "Chọn Buyer; chỉ điền giao nhận bắt buộc khi đơn có hàng vật lý.", en: "Select the buyer; delivery details are mandatory only for orders with physical lines." } },
      { id: "products", text: { vi: "Thêm sản phẩm, số lượng và giá áp dụng.", en: "Add products, quantities, and applicable prices." } },
      { id: "payment-plan", text: { vi: "Khai báo kế hoạch thanh toán; việc thu tiền thực tế được ghi nhận trong Thanh toán.", en: "Define the payment plan; actual collections are recorded in Payments." } },
      { id: "save", text: { vi: "Kiểm tra tổng kết và lưu đơn hàng.", en: "Review the summary and save the order." } },
    ],
    commonMistakes: [{ vi: "Kế hoạch thanh toán không phải là bằng chứng đã thu tiền.", en: "A payment plan is not evidence that money was collected." }],
    relatedWorkflowIds: ["workflow.lead-to-order", "workflow.order-to-shipping"],
    steps: [
      { id: "customer", targetId: "orders.form.customer-recipient", title: { vi: "Buyer, người phụ trách và giao nhận", en: "Buyer, owner, and delivery" }, body: { vi: "Buyer lấy từ Contact hoặc Organization. Owner lấy từ thành viên workspace; dữ liệu giao nhận chỉ bắt buộc khi có dòng hàng vật lý.", en: "The buyer comes from a Contact or Organization. The owner comes from the workspace directory; delivery data is required only for physical lines." }, placement: "right", expectedAction: "view" },
      { id: "products", targetId: "orders.form.products", title: { vi: "Dòng sản phẩm", en: "Product lines" }, body: { vi: "Thêm ít nhất một sản phẩm và kiểm tra số lượng, đơn giá, thuế và chiết khấu.", en: "Add at least one product and verify quantity, unit price, tax, and discount." }, placement: "right", expectedAction: "view" },
      { id: "payment", targetId: "orders.form.payment-plan", title: { vi: "Kế hoạch thanh toán", en: "Payment plan" }, body: { vi: "Khai báo các đợt dự kiến. Sau khi tạo đơn, mỗi khoản thu thực tế vẫn phải được ghi nhận trong Thanh toán.", en: "Define expected installments. After order creation, each actual collection must still be recorded in Payments." }, placement: "right", expectedAction: "view" },
      { id: "save", targetId: "orders.form.save", title: { vi: "Lưu đơn hàng", en: "Save the order" }, body: { vi: "Lưu khi các trường bắt buộc và tổng kết đã chính xác. Đơn hợp lệ được tạo ở trạng thái Đã xác nhận.", en: "Save after required fields and totals are correct. A valid order is created as Confirmed." }, placement: "top", expectedAction: "click" },
    ],
    requiredCapabilities: [CAPABILITIES.ORDERS_CREATE],
    owner,
    reviewedAt,
  },
  {
    id: "crm.payments.list",
    routeKey: "PAYMENTS",
    productSpace: "crm",
    version: 3,
    title: { vi: "Thanh toán", en: "Payments" },
    purpose: { vi: "Theo dõi khoản cần thu, gửi yêu cầu thanh toán, ghi nhận tiền thực nhận và phân bổ vào hóa đơn.", en: "Track amounts due, send payment requests, record collected funds, and allocate them to invoices." },
    prerequisites: [
      { vi: "Kiểm tra đúng đơn hàng, khách hàng và số tiền trước khi ghi nhận.", en: "Verify the order, customer, and amount before recording funds." },
      { vi: "Khoản thu chỉ làm giảm công nợ sau khi được phân bổ vào đúng hóa đơn.", en: "Collected funds reduce receivables only after allocation to the correct invoice." },
    ],
    primaryTasks: [
      { id: "review-due", text: { vi: "Mở Cần thu để xem các khoản đến hạn theo đơn hàng.", en: "Open Collection queue to review amounts due by order." }, requiredCapabilities: [CAPABILITIES.PAYMENTS_READ] },
      { id: "request", text: { vi: "Gửi yêu cầu thanh toán khi khách cần liên kết hoặc hướng dẫn thanh toán.", en: "Send a payment request when the customer needs a checkout link or payment instructions." }, requiredCapabilities: [CAPABILITIES.PAYMENTS_INTENT_CREATE] },
      { id: "record", text: { vi: "Ghi nhận tiền đã thu bằng đúng phương thức và chứng từ đối chiếu.", en: "Record collected funds with the correct method and reconciliation evidence." }, requiredCapabilities: [CAPABILITIES.PAYMENTS_RECORD] },
      { id: "reconcile", text: { vi: "Đối soát và phân bổ khoản thu vào hóa đơn phù hợp.", en: "Reconcile and allocate collected funds to the appropriate invoice." }, requiredCapabilities: [CAPABILITIES.PAYMENTS_RECONCILE] },
      { id: "refund", text: { vi: "Thực hiện hoàn tiền khi kết quả đổi hoặc trả hàng đã đủ điều kiện.", en: "Issue a refund when an eligible return resolution requires it." }, requiredCapabilities: [CAPABILITIES.PAYMENTS_REFUND] },
    ],
    commonMistakes: [
      { vi: "Không coi lịch thu trong đơn hàng là bằng chứng tiền đã về.", en: "Do not treat an order collection schedule as proof that funds were received." },
      { vi: "Không ghi nhận cùng một khoản thu hai lần khi vừa có yêu cầu thanh toán vừa có chứng từ chuyển tiền.", en: "Do not record the same funds twice when both a payment request and transfer evidence exist." },
      { vi: "Khi mở từ đơn hàng, hãy kiểm tra lại khoản cần thu đang được chọn trước khi lưu.", en: "When opening from an order, verify the selected collection item before saving." },
    ],
    relatedWorkflowIds: ["workflow.order-to-shipping", "workflow.order-return-resolution"],
    steps: [
      { id: "screen", targetId: "payment.operations.screen", title: { vi: "Không gian thu tiền", en: "Collections workspace" }, body: { vi: "Mỗi thẻ quy trình tương ứng một giai đoạn: cần thu, yêu cầu gửi khách, tiền đã ghi nhận, đối soát và tín dụng khách hàng.", en: "Each workflow tab represents a stage: amounts due, customer requests, recorded funds, reconciliation, and customer credits." }, placement: "bottom", expectedAction: "view" },
      { id: "workflow", targetId: "payment.operations.workflow", title: { vi: "Chọn đúng giai đoạn", en: "Choose the right stage" }, body: { vi: "Bắt đầu ở Cần thu, sau đó chuyển sang Tiền đã ghi nhận hoặc Đối soát khi có chứng từ thực tế.", en: "Start in Collection queue, then move to Recorded payments or Reconciliation when actual evidence is available." }, placement: "bottom", expectedAction: "select" },
      { id: "search", targetId: "payment.operations.search", title: { vi: "Tìm theo chứng từ liên quan", en: "Search by related evidence" }, body: { vi: "Có thể tìm theo đơn hàng, khách hàng, mã chứng từ hoặc yêu cầu thanh toán.", en: "Search by order, customer, evidence reference, or payment request." }, placement: "bottom", expectedAction: "input" },
    ],
    requiredCapabilities: [CAPABILITIES.PAYMENTS_READ],
    keywords: { vi: "thu tiền thanh toán công nợ đối soát phân bổ hoàn tiền", en: "collections payments receivables reconcile allocate refund" },
    owner,
    reviewedAt: "2026-07-23",
  },
  {
    id: "crm.shipping.list",
    routeKey: "SHIPPING",
    productSpace: "crm",
    version: 2,
    title: { vi: "Vận đơn", en: "Shipping bookings" },
    purpose: { vi: "Tạo và theo dõi yêu cầu giao nhận độc lập với trạng thái đơn hàng, bao gồm nhà vận chuyển và trạng thái bên ngoài.", en: "Create and track delivery requests independently from order state, including provider and external status." },
    prerequisites: [{ vi: "Đơn hàng phải Đã xác nhận và có đủ người nhận, số điện thoại, địa chỉ cùng điểm lấy hàng khi chính sách yêu cầu.", en: "The order must be Confirmed and include recipient, phone, address, and pickup location when required." }],
    primaryTasks: [
      { id: "create", text: { vi: "Tạo vận đơn từ đơn hàng đủ điều kiện.", en: "Create a shipping booking from an eligible order." }, route: "shipping/new", requiredCapabilities: [CAPABILITIES.SHIPPING_CREATE] },
      { id: "sync", text: { vi: "Đồng bộ trạng thái từ nhà vận chuyển.", en: "Synchronize status from the shipping provider." }, requiredCapabilities: [CAPABILITIES.SHIPPING_SYNC] },
      { id: "retry", text: { vi: "Thử lại hoặc đổi nhà vận chuyển khi tạo vận đơn thất bại.", en: "Retry or change provider when booking creation fails." }, requiredCapabilities: [CAPABILITIES.SHIPPING_RETRY] },
    ],
    commonMistakes: [{ vi: "Không suy diễn đã giao hàng chỉ từ trạng thái nội bộ; cần bằng chứng giao thành công và thời điểm giao.", en: "Do not infer delivery from the booking status alone; successful delivery evidence and delivery time are required." }],
    relatedWorkflowIds: ["workflow.order-to-shipping", "workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.SHIPPING_READ],
    owner,
    reviewedAt,
  },
  {
    id: "crm.returns.list",
    routeKey: "RETURNS",
    productSpace: "crm",
    version: 1,
    title: { vi: "Đổi / Trả hàng", en: "Returns" },
    purpose: { vi: "Tiếp nhận yêu cầu theo từng dòng hàng, kiểm tra điều kiện, phê duyệt, nhận hàng và hoàn tất phương án xử lý.", en: "Receive line-level requests, evaluate eligibility, approve, receive items, and complete the resolution." },
    prerequisites: [{ vi: "Yêu cầu phải liên kết đơn hàng và số lượng đã mua; điều kiện hợp lệ và quyết định phê duyệt là hai bước riêng.", en: "The request must link to an order and purchased quantities; eligibility and approval are separate decisions." }],
    primaryTasks: [
      { id: "create", text: { vi: "Tạo yêu cầu đổi/trả theo từng sản phẩm và số lượng.", en: "Create a return request by product line and quantity." }, route: "returns/new", requiredCapabilities: [CAPABILITIES.RETURNS_CREATE] },
      { id: "approve", text: { vi: "Phê duyệt hoặc từ chối sau khi xem kết quả kiểm tra điều kiện.", en: "Approve or reject after reviewing eligibility." }, requiredCapabilities: [CAPABILITIES.RETURNS_APPROVE] },
      { id: "receive", text: { vi: "Xác nhận hàng thực nhận và kết quả kiểm tra.", en: "Confirm actual receipt and inspection results." }, requiredCapabilities: [CAPABILITIES.RETURNS_UPDATE] },
      { id: "resolve", text: { vi: "Hoàn tất bằng hoàn tiền hoặc gửi hàng thay thế khi bằng chứng liên quan đã thành công.", en: "Resolve by refund or replacement shipment after the required evidence succeeds." }, requiredCapabilities: [CAPABILITIES.RETURNS_RESOLVE] },
    ],
    commonMistakes: [{ vi: "Không đánh dấu hoàn tất hoàn tiền hoặc đổi hàng trước khi Payment hoặc Shipping xác nhận thành công.", en: "Do not complete a refund or replacement before Payment or Shipping confirms success." }],
    relatedWorkflowIds: ["workflow.order-return-resolution"],
    requiredCapabilities: [CAPABILITIES.RETURNS_READ],
    owner,
    reviewedAt,
  },
  {
    id: "crm.support.list",
    routeKey: "SUPPORT_CASES",
    productSpace: "crm",
    version: 1,
    title: { vi: "Phiếu hỗ trợ", en: "Support tickets" },
    purpose: { vi: "Theo dõi yêu cầu, tư vấn, khiếu nại và các hoạt động chăm sóc cần xử lý theo người phụ trách và lần hẹn tiếp theo.", en: "Track requests, consultations, complaints, and care activities by owner and next follow-up." },
    prerequisites: [{ vi: "Liên kết đúng khách hàng hoặc người liên hệ để giữ lịch sử quan hệ đầy đủ.", en: "Link the correct customer or contact to preserve relationship history." }],
    primaryTasks: [
      { id: "create", text: { vi: "Tạo phiếu khi có một nhu cầu chăm sóc cần theo dõi.", en: "Create a ticket for a care need that requires tracking." }, route: "support/cases/new", requiredCapabilities: [CAPABILITIES.SUPPORT_CREATE] },
      { id: "assign", text: { vi: "Giao người phụ trách và đặt lần hẹn tiếp theo.", en: "Assign an owner and set the next follow-up." }, requiredCapabilities: [CAPABILITIES.SUPPORT_ASSIGN] },
      { id: "task", text: { vi: "Tạo công việc chỉ khi có hành động cụ thể cần giao.", en: "Create a task only for a concrete action that must be assigned." }, route: "tasks", requiredCapabilities: [CAPABILITIES.TASKS_CREATE] },
    ],
    commonMistakes: [{ vi: "Không tạo công việc chỉ để sao chép nội dung phiếu; công việc phải có hành động, người thực hiện và hạn xử lý rõ ràng.", en: "Do not create a task merely to duplicate a ticket; a task needs a clear action, assignee, and due time." }],
    relatedWorkflowIds: ["workflow.support-to-task"],
    requiredCapabilities: [CAPABILITIES.SUPPORT_READ],
    owner,
    reviewedAt,
  },
  {
    id: "crm.reports.overview",
    routeKey: "REPORTS",
    productSpace: "crm",
    version: 4,
    title: { vi: "Báo cáo", en: "Reports" },
    purpose: { vi: "Đọc KPI có công thức rõ ràng, kiểm tra bản ghi nguồn và phân biệt funnel cohort với các ảnh chụp dữ liệu độc lập.", en: "Review formula-backed KPIs, inspect source records, and distinguish cohort funnels from independent data snapshots." },
    prerequisites: [{ vi: "Bạn cần quyền xem báo cáo và quyền đọc domain nguồn; xuất CSV yêu cầu quyền xuất riêng.", en: "Report access and source-domain read permission are required; CSV export needs a separate permission." }],
    primaryTasks: [
      { id: "period", text: { vi: "Chọn kỳ báo cáo và xác nhận múi giờ đang áp dụng.", en: "Choose a reporting period and confirm the applied timezone." } },
      { id: "drilldown", text: { vi: "Chọn KPI để xem công thức, trạng thái được tính và bản ghi nguồn.", en: "Select a KPI to inspect formula, included states, and source records." } },
      { id: "cohort", text: { vi: "Dùng funnel cohort để theo cùng một nhóm Lead qua chuỗi giao dịch.", en: "Use the cohort funnel to follow one lead group through the commercial chain." } },
      { id: "export", text: { vi: "Xuất CSV khi cần phân tích ngoài hệ thống.", en: "Export CSV for analysis outside the system." }, requiredCapabilities: [CAPABILITIES.REPORTS_EXPORT] },
      { id: "forecast", text: { vi: "Chụp forecast snapshot và theo dõi độ chính xác Commit theo kỳ.", en: "Capture forecast snapshots and monitor Commit accuracy by period." } },
      { id: "order-to-cash", text: { vi: "Theo dõi chu kỳ thu tiền đơn hàng, giao hàng, COD, hoàn tiền và tuổi nợ Receivables; DSO kế toán chờ dữ liệu backend bền vững và quy tắc kỳ báo cáo.", en: "Monitor Order collection, delivery, COD, refunds, and Receivables aging; accounting DSO requires durable backend data and reporting-period rules." } },
    ],
    commonMistakes: [{ vi: "Không coi biểu đồ trạng thái độc lập là funnel chuyển đổi; chúng là ảnh chụp của các tập dữ liệu khác nhau.", en: "Do not interpret independent status charts as a conversion funnel; they are snapshots of different datasets." }],
    steps: [
      { id: "period", targetId: "reports.period.selector", title: { vi: "Chọn kỳ tính", en: "Choose the period" }, body: { vi: "Các KPI theo kỳ dùng ngày nghiệp vụ và múi giờ được khai báo trong Metric Catalog.", en: "Period KPIs use the business date and timezone declared in the Metric Catalog." }, placement: "bottom", expectedAction: "select" },
      { id: "metric", targetId: "reports.metric.completed-revenue", title: { vi: "Kiểm tra KPI", en: "Inspect a KPI" }, body: { vi: "Chọn thẻ để mở công thức, trạng thái được tính, thời điểm cập nhật và danh sách bản ghi nguồn.", en: "Select the card to open its formula, included states, freshness, and source-record list." }, placement: "bottom", expectedAction: "click" },
      { id: "funnel", targetId: "reports.cohort-funnel", title: { vi: "Funnel cùng cohort", en: "One-cohort funnel" }, body: { vi: "Mỗi giai đoạn chỉ gồm bản ghi truy vết từ nhóm Lead được tạo trong kỳ, không ghép các tổng độc lập.", en: "Each stage contains records traceable to the period's lead cohort rather than unrelated totals." }, placement: "top", expectedAction: "view" },
      { id: "drilldown", targetId: "reports.metric.drilldown", title: { vi: "Bản ghi nguồn", en: "Source records" }, body: { vi: "Từ đây bạn có thể mở bản ghi gốc và quay lại Dashboard mà không mất ngữ cảnh.", en: "Open a source record here and return to the Dashboard without losing context." }, placement: "left", expectedAction: "view", optional: true },
      { id: "advanced-forecast", targetId: "reports.advanced-forecast", title: { vi: "Forecast có snapshot", en: "Snapshot-based forecast" }, body: { vi: "So sánh Commit, Best Case, Pipeline, weighted value và doanh thu thắng thực tế. Chụp snapshot định kỳ để đo accuracy.", en: "Compare Commit, Best Case, Pipeline, weighted value, and actual won revenue. Capture snapshots regularly to measure accuracy." }, placement: "top", expectedAction: "view" },
      { id: "order-to-cash", targetId: "reports.order-to-cash", title: { vi: "Chất lượng Order-to-Cash", en: "Order-to-Cash quality" }, body: { vi: "Các chỉ số dùng evidence từ Order, Payment, Shipping và Return; dữ liệu thiếu được hiển thị là chưa đủ thay vì tự coi là 0.", en: "Metrics use evidence from Orders, Payments, Shipping, and Returns; missing evidence is shown as unavailable rather than assumed to be zero." }, placement: "top", expectedAction: "view" },
    ],
    requiredCapabilities: [CAPABILITIES.REPORTS_READ],
    owner,
    reviewedAt,
  },
];
