import type { OrganizationAccount } from "../domain/model/organizationAccount.types";

/**
 * Generated relationship identity migration snapshot for legacy COMPANY records.
 * The legacy aliases are migration-only route continuity fields; identity is
 * owned by Organization Account.
 */
export const ORGANIZATION_ACCOUNT_SEED: OrganizationAccount[] = [
  {
    id: "org_c1",
    workspaceId: "ws_default",
    displayName: "Công ty TNHH TechVision",
    legalName: "Công ty TNHH TechVision",
    taxCode: "0314959291",
    phone: "0365686791",
    email: "contact@techvision.vn",
    address: "Tòa nhà Keangnam, Cầu Giấy, Hà Nội",
    industry: "Hạ tầng & Giải pháp đám mây",
    sizeBand: "Enterprise",
    ownerId: "u5",
    source: "Hội thảo / Webinar",
    tags: ["VIP SLA", "Enterprise", "Active Customer"],
    status: "strategic",
    relationshipLevel: "strategic",
    primaryContactId: "con1",
    contactRefs: [
      { type: "CONTACT", id: "con1" },
      { type: "CONTACT", id: "con2" },
    ],
    legacyCustomerId: "c1",
    legacyCustomerCode: "KH0000001",
    createdAt: "2026-01-10T08:30:00Z",
  },
  {
    id: "org_c2",
    workspaceId: "ws_default",
    displayName: "Công ty TNHH TechHub",
    legalName: "Công ty TNHH TechHub",
    taxCode: "0314999111",
    phone: "0365111222",
    email: "contact@techhub.vn",
    address: "Tòa nhà Viettel, Quận 10, TP.HCM",
    industry: "Thương mại điện tử & Logistics",
    sizeBand: "Enterprise",
    ownerId: "u5",
    source: "Tư vấn trực tiếp",
    tags: ["Renewal Critical", "Enterprise"],
    status: "active",
    relationshipLevel: "strong",
    primaryContactId: "con3",
    contactRefs: [{ type: "CONTACT", id: "con3" }],
    legacyCustomerId: "c2",
    legacyCustomerCode: "KH0000002",
    createdAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "org_c4",
    workspaceId: "ws_default",
    displayName: "Tập đoàn Vận tải Viễn Đông",
    legalName: "Tập đoàn Vận tải Viễn Đông",
    phone: "0388 777 666",
    email: "tuan.pm@viendongtrans.vn",
    address: "Bình Thạnh, TP.HCM",
    sizeBand: "Enterprise",
    ownerId: "u1",
    source: "Google Ads",
    tags: ["Logistics", "Enterprise", "Active Customer"],
    status: "active",
    relationshipLevel: "strong",
    primaryContactId: "con7",
    contactRefs: [{ type: "CONTACT", id: "con7" }],
    legacyCustomerId: "c4",
    legacyCustomerCode: "KH0000004",
    createdAt: "2026-05-01T09:00:00Z",
  },
  {
    id: "org_c5",
    workspaceId: "ws_default",
    displayName: "Công ty Cổ phần Đầu tư Hoàng Gia",
    legalName: "Công ty Cổ phần Đầu tư Hoàng Gia",
    phone: "0987 654 321",
    email: "lephuong@royalinvest.com.vn",
    address: "12 Láng Hạ, Đống Đa, Hà Nội",
    sizeBand: "Key Account",
    ownerId: "u1",
    source: "Google Search",
    tags: ["Finance", "Active Customer"],
    status: "active",
    relationshipLevel: "strong",
    primaryContactId: "con5",
    contactRefs: [{ type: "CONTACT", id: "con5" }],
    legacyCustomerId: "c5",
    legacyCustomerCode: "KH0000005",
    createdAt: "2026-05-10T11:00:00Z",
  },
];
