import { QuoteStatus, type Quote } from "../domain/model/quote.types";

export const QUOTE_SEED: Quote[] = [
  {
    id: "q1",
    quoteNumber: "QT-2026-104",
    version: 1,
    rootQuoteId: "q1",
    buyerRef: { type: "ORGANIZATION_ACCOUNT", id: "org_c1" },
    sourcePath: "DEAL",
    dealId: "d1",
    sourceDealId: "d1",
    dealName: "Triển khai hệ thống ERP Phase 1",
    customerId: "c1",
    customerName: "Công ty TNHH TechVision",
    customerAddress: "Tòa nhà Keangnam, Cầu Giấy, Hà Nội",
    customerContact: "Nguyễn Văn Tuấn - +84 901 234 567",
    senderName: "Công ty Cổ phần Unicore",
    senderAddress: "123 Đường Công Nghệ, Quận 1, TP. HCM",
    senderEmail: "hello@unicore.vn",
    senderTaxId: "0101234567",
    status: QuoteStatus.DRAFT,
    title: "Báo giá hệ thống ERP Phase 1",
    currency: "VND",
    ownerId: "u1",
    ownerName: "Nguyễn Văn An",
    createdAt: "2026-06-01",
    expiryDate: "2026-07-01",
    validUntil: "2026-07-01",
    taxPercent: 10,
    discountAmountToTotal: 0,
    subtotal: 135000000,
    discountTotal: 12000000,
    taxTotal: 12000000,
    grandTotal: 135000000,
    lineItems: [
      {
        id: "qli1_1",
        productId: "prod_3",
        skuSnapshot: "CRM-ENT-SUITE",
        productNameSnapshot: "CRM Enterprise Suite",
        productTypeSnapshot: "subscription",
        quantity: 1,
        unitPriceSnapshot: 120000000,
        discountPercent: 10,
        taxRateSnapshot: 10,
        taxModeSnapshot: "exclusive",
        billingCycleSnapshot: "yearly",
        lineSubtotal: 120000000,
        lineDiscountAmount: 12000000,
        lineTaxAmount: 10800000,
        lineTotal: 118800000,
        productName: "CRM Enterprise Suite",
        unitPrice: 120000000
      },
      {
        id: "qli1_2",
        productId: "prod_4",
        skuSnapshot: "CRM-IMPL-PKG",
        productNameSnapshot: "Implementation Package",
        productTypeSnapshot: "implementation",
        quantity: 1,
        unitPriceSnapshot: 15000000,
        discountPercent: 0,
        taxRateSnapshot: 8,
        taxModeSnapshot: "exclusive",
        billingCycleSnapshot: "one_time",
        lineSubtotal: 15000000,
        lineDiscountAmount: 0,
        lineTaxAmount: 1200000,
        lineTotal: 16200000,
        productName: "Implementation Package",
        unitPrice: 15000000
      }
    ],
    termsAndNotes: "1. Thanh toán 50% ngay sau khi ký hợp đồng, 50% còn lại sau khi hoàn thành triển khai.\n2. Thuế được áp dụng theo cấu hình tại từng dòng sản phẩm.\n3. Chi phí duy trì từ năm thứ 2 là 80% giá trị license gốc.\n4. Thông tin chuyển khoản: Ngân hàng VCB - STK: 0123456789 - Chủ TK: CTCP Unicore."
  }  ,
  {
    id: "q2",
    quoteNumber: "QT-2026-105",
    version: 1,
    rootQuoteId: "q2",
    buyerRef: { type: "ORGANIZATION_ACCOUNT", id: "org_c1" },
    sourcePath: "DEAL",
    dealId: "d1",
    sourceDealId: "d1",
    dealName: "Triển khai hệ thống ERP Phase 1",
    customerId: "c1",
    customerName: "Công ty TNHH TechVision",
    customerAddress: "Tòa nhà Keangnam, Cầu Giấy, Hà Nội",
    customerContact: "Nguyễn Văn Tuấn - +84 901 234 567",
    senderName: "Công ty Cổ phần Unicore",
    senderAddress: "123 Đường Công Nghệ, Quận 1, TP. HCM",
    senderEmail: "hello@unicore.vn",
    senderTaxId: "0101234567",
    status: QuoteStatus.ACCEPTED,
    title: "Báo giá gói đào tạo quản lý vận hành nâng cao",
    currency: "VND",
    ownerId: "u5",
    ownerName: "Phạm Minh Thư",
    createdAt: "2026-06-01",
    updatedAt: "2026-06-04T16:00:00Z",
    expiryDate: "2026-06-30",
    validUntil: "2026-06-30",
    acceptedAt: "2026-06-04T15:30:00Z",
    approvalStatus: undefined,
    taxPercent: 10,
    discountAmountToTotal: 0,
    subtotal: 15000000,
    discountTotal: 0,
    taxTotal: 1500000,
    grandTotal: 16500000,
    lineItems: [
      {
        id: "qli2_1",
        productId: "prod_4",
        skuSnapshot: "CRM-IMPL-PKG",
        productNameSnapshot: "Gói đào tạo quản lý vận hành nâng cao",
        productTypeSnapshot: "implementation",
        quantity: 1,
        unitPriceSnapshot: 15000000,
        discountPercent: 0,
        taxRateSnapshot: 10,
        taxModeSnapshot: "exclusive",
        billingCycleSnapshot: "one_time",
        lineSubtotal: 15000000,
        lineDiscountAmount: 0,
        lineTaxAmount: 1500000,
        lineTotal: 16500000,
        productName: "Gói đào tạo quản lý vận hành nâng cao",
        unitPrice: 15000000
      }
    ],
    termsAndNotes: "Thanh toán theo thỏa thuận trong báo giá đã được chấp nhận."
  }

];
