import { ROUTE_KEYS } from "@/platform/navigation";

export interface RouteMeta {
  path: string;
  moduleKey?: "leads" | "contacts" | "organizations" | "customers" | "tasks" | "deals" | "quotes" | "subscriptions" | "support" | "orders" | "payments" | "invoices" | "receivables" | "shipping" | "returns" | "reports";
  labelKey: string;
  guidanceId: string;
}

export const ROUTE_METADATA: Record<string, RouteMeta> = {
  MY_WORK: { path: ROUTE_KEYS.MY_WORK, labelKey: "myWork.title", guidanceId: "crm.my-work.overview" },
  CALENDAR: { path: ROUTE_KEYS.CALENDAR, labelKey: "calendar.title", guidanceId: "crm.calendar.overview" },
  NOTIFICATIONS: { path: ROUTE_KEYS.NOTIFICATIONS, labelKey: "notifications.title", guidanceId: "crm.notifications.center" },
  TASKS: { path: ROUTE_KEYS.TASKS, moduleKey: "tasks", labelKey: "tasks.title", guidanceId: "crm.tasks.list" },
  TASK_DETAIL: { path: ROUTE_KEYS.TASK_DETAIL, moduleKey: "tasks", labelKey: "tasks.detail", guidanceId: "crm.tasks.detail" },
  REPORTS: { path: ROUTE_KEYS.REPORTS, moduleKey: "reports", labelKey: "reports.title", guidanceId: "crm.reports.overview" },
  DASHBOARD: { path: ROUTE_KEYS.DASHBOARD, labelKey: "dashboard.title", guidanceId: "crm.dashboard.overview" },
  LEADS: { path: ROUTE_KEYS.LEADS, moduleKey: "leads", labelKey: "leadList.title", guidanceId: "crm.leads.list" },
  LEADS_QUEUE: { path: ROUTE_KEYS.LEADS_QUEUE, moduleKey: "leads", labelKey: "leadQueue.title", guidanceId: "crm.leads.queue" },
  LEAD_DETAIL: { path: ROUTE_KEYS.LEAD_DETAIL, moduleKey: "leads", labelKey: "leadDetail.title", guidanceId: "crm.leads.detail" },
  LEAD_QUALIFY: { path: ROUTE_KEYS.LEAD_QUALIFY, moduleKey: "leads", labelKey: "leadQualification.title", guidanceId: "crm.leads.qualify" },
  LEAD_SELL_NOW: { path: ROUTE_KEYS.LEAD_SELL_NOW, moduleKey: "leads", labelKey: "leadSellNow.title", guidanceId: "crm.leads.sell-now" },
  LEAD_CONVERT: { path: ROUTE_KEYS.LEAD_CONVERT, moduleKey: "leads", labelKey: "leadQualification.title", guidanceId: "crm.leads.qualify" },
  CATALOG: { path: ROUTE_KEYS.CATALOG, labelKey: "catalog.title", guidanceId: "crm.products.list" },
  PRODUCT_DETAIL: { path: ROUTE_KEYS.PRODUCT_DETAIL, labelKey: "productDetail.title", guidanceId: "crm.products.detail" },
  DEALS: { path: ROUTE_KEYS.DEALS, moduleKey: "deals", labelKey: "dealPipeline.title", guidanceId: "crm.deals.pipeline" },
  DEAL_DETAIL: { path: ROUTE_KEYS.DEAL_DETAIL, moduleKey: "deals", labelKey: "dealDetail.title", guidanceId: "crm.deals.detail" },
  QUOTES: { path: ROUTE_KEYS.QUOTES, moduleKey: "quotes", labelKey: "quoteBuilder.title", guidanceId: "crm.quotes.list" },
  QUOTE_NEW: { path: ROUTE_KEYS.QUOTE_NEW, moduleKey: "quotes", labelKey: "quoteBuilder.title", guidanceId: "crm.quotes.create" },
  QUOTE_DETAIL: { path: ROUTE_KEYS.QUOTE_DETAIL, moduleKey: "quotes", labelKey: "quoteDetail.title", guidanceId: "crm.quotes.detail" },
  QUOTE_EDIT: { path: ROUTE_KEYS.QUOTE_EDIT, moduleKey: "quotes", labelKey: "quoteBuilder.title", guidanceId: "crm.quotes.edit" },
  QUOTE_BUILDER_LEGACY: { path: ROUTE_KEYS.QUOTE_BUILDER_LEGACY, moduleKey: "quotes", labelKey: "quoteBuilder.title", guidanceId: "crm.quotes.create" },
  ORDERS: { path: ROUTE_KEYS.ORDERS, moduleKey: "orders", labelKey: "orders.list.title", guidanceId: "crm.orders.list" },
  ORDER_NEW: { path: ROUTE_KEYS.ORDER_NEW, moduleKey: "orders", labelKey: "orders.actions.create", guidanceId: "crm.orders.create" },
  ORDER_DETAIL: { path: ROUTE_KEYS.ORDER_DETAIL, moduleKey: "orders", labelKey: "orders.detail.title", guidanceId: "crm.orders.detail" },
  ORDER_EDIT: { path: ROUTE_KEYS.ORDER_EDIT, moduleKey: "orders", labelKey: "orders.actions.edit", guidanceId: "crm.orders.edit" },
  PAYMENTS: { path: ROUTE_KEYS.PAYMENTS, moduleKey: "payments", labelKey: "payments.title", guidanceId: "crm.payments.list" },
  PAYMENT_DETAIL: { path: ROUTE_KEYS.PAYMENT_DETAIL, moduleKey: "payments", labelKey: "payments.detail", guidanceId: "crm.payments.detail" },
  INVOICES: { path: ROUTE_KEYS.INVOICES, moduleKey: "invoices", labelKey: "invoices.title", guidanceId: "crm.invoices.list" },
  INVOICE_NEW: { path: ROUTE_KEYS.INVOICE_NEW, moduleKey: "invoices", labelKey: "invoices.create", guidanceId: "crm.invoices.create" },
  INVOICE_DETAIL: { path: ROUTE_KEYS.INVOICE_DETAIL, moduleKey: "invoices", labelKey: "invoices.detail", guidanceId: "crm.invoices.detail" },
  INVOICE_EDIT: { path: ROUTE_KEYS.INVOICE_EDIT, moduleKey: "invoices", labelKey: "invoices.edit", guidanceId: "crm.invoices.edit" },
  RECEIVABLES: { path: ROUTE_KEYS.RECEIVABLES, moduleKey: "receivables", labelKey: "receivables.title", guidanceId: "crm.receivables.list" },
  RECEIVABLE_DETAIL: { path: ROUTE_KEYS.RECEIVABLE_DETAIL, moduleKey: "receivables", labelKey: "receivables.detail", guidanceId: "crm.receivables.detail" },
  ACCOUNT_STATEMENT: { path: ROUTE_KEYS.ACCOUNT_STATEMENT, moduleKey: "receivables", labelKey: "receivables.statement", guidanceId: "crm.receivables.statement" },
  SHIPPING: { path: ROUTE_KEYS.SHIPPING, moduleKey: "shipping", labelKey: "shipping.title", guidanceId: "crm.shipping.list" },
  SHIPPING_NEW: { path: ROUTE_KEYS.SHIPPING_NEW, moduleKey: "shipping", labelKey: "shipping.create", guidanceId: "crm.shipping.create" },
  SHIPPING_DETAIL: { path: ROUTE_KEYS.SHIPPING_DETAIL, moduleKey: "shipping", labelKey: "shipping.detail", guidanceId: "crm.shipping.detail" },
  RETURNS: { path: ROUTE_KEYS.RETURNS, moduleKey: "returns", labelKey: "returns.title", guidanceId: "crm.returns.list" },
  RETURN_NEW: { path: ROUTE_KEYS.RETURN_NEW, moduleKey: "returns", labelKey: "returns.create", guidanceId: "crm.returns.create" },
  RETURN_DETAIL: { path: ROUTE_KEYS.RETURN_DETAIL, moduleKey: "returns", labelKey: "returns.detail", guidanceId: "crm.returns.detail" },
  CONTACTS: { path: ROUTE_KEYS.CONTACTS, moduleKey: "contacts", labelKey: "contactList.title", guidanceId: "crm.contacts.list" },
  CONTACT_DETAIL: { path: ROUTE_KEYS.CONTACT_DETAIL, moduleKey: "contacts", labelKey: "contactDetail.title", guidanceId: "crm.contacts.detail" },
  ORGANIZATIONS: { path: ROUTE_KEYS.ORGANIZATIONS, moduleKey: "organizations", labelKey: "organizations.title", guidanceId: "crm.organizations.list" },
  ORGANIZATION_DETAIL: { path: ROUTE_KEYS.ORGANIZATION_DETAIL, moduleKey: "organizations", labelKey: "organizations.detail", guidanceId: "crm.organizations.detail" },
  CUSTOMERS: { path: ROUTE_KEYS.CUSTOMERS, moduleKey: "customers", labelKey: "customerList.title", guidanceId: "crm.customers.list" },
  CUSTOMER_DETAIL: { path: ROUTE_KEYS.CUSTOMER_DETAIL, moduleKey: "customers", labelKey: "customer360.title", guidanceId: "crm.customers.detail" },
  CUSTOMER_SEGMENTS: { path: ROUTE_KEYS.CUSTOMER_SEGMENTS, moduleKey: "customers", labelKey: "app.customerSegments", guidanceId: "crm.customers.segments" },
  CUSTOMER_HEALTH: { path: ROUTE_KEYS.CUSTOMER_HEALTH, moduleKey: "customers", labelKey: "app.customerHealth", guidanceId: "crm.customers.health" },
  SUPPORT_CASES: { path: ROUTE_KEYS.SUPPORT_CASES, moduleKey: "support", labelKey: "support.title", guidanceId: "crm.support.list" },
  SUPPORT_CASE_NEW: { path: ROUTE_KEYS.SUPPORT_CASE_NEW, moduleKey: "support", labelKey: "support.create", guidanceId: "crm.support.create" },
  SUPPORT_CASE_DETAIL: { path: ROUTE_KEYS.SUPPORT_CASE_DETAIL, moduleKey: "support", labelKey: "support.detail", guidanceId: "crm.support.detail" },
  SUPPORT_CASE_EDIT: { path: ROUTE_KEYS.SUPPORT_CASE_EDIT, moduleKey: "support", labelKey: "support.edit", guidanceId: "crm.support.edit" },

  SETTINGS_ROLES: { path: ROUTE_KEYS.SETTINGS_ROLES, labelKey: "settings.roles", guidanceId: "people.roles.access" },
  SETTINGS_QUICK_SETUP: { path: ROUTE_KEYS.SETTINGS_QUICK_SETUP, labelKey: "studio.quickSetup", guidanceId: "studio.quick-setup" },
  SETTINGS_BUSINESS_INFORMATION: { path: ROUTE_KEYS.SETTINGS_BUSINESS_INFORMATION, labelKey: "studio.businessInformation", guidanceId: "studio.business-information" },
  SETTINGS_LOCALE_REGION: { path: ROUTE_KEYS.SETTINGS_LOCALE_REGION, labelKey: "studio.localeRegion", guidanceId: "studio.locale-region" },
  SETTINGS_FEATURE_USAGE: { path: ROUTE_KEYS.SETTINGS_FEATURE_USAGE, labelKey: "studio.featureUsage", guidanceId: "studio.feature-usage" },
  SETTINGS_PIPELINES_STATUSES: { path: ROUTE_KEYS.SETTINGS_PIPELINES_STATUSES, labelKey: "studio.pipelinesStatuses", guidanceId: "studio.pipelines-statuses" },
  SETTINGS_PRODUCT_TYPES: { path: ROUTE_KEYS.SETTINGS_PRODUCT_TYPES, labelKey: "studio.productTypes", guidanceId: "studio.product-types" },
  SETTINGS_INFORMATION_FIELDS: { path: ROUTE_KEYS.SETTINGS_INFORMATION_FIELDS, labelKey: "studio.informationFields", guidanceId: "studio.information-fields" },
  SETTINGS_PAYMENT_INFORMATION: { path: ROUTE_KEYS.SETTINGS_PAYMENT_INFORMATION, labelKey: "studio.paymentInformation", guidanceId: "studio.payment-information" },
  SETTINGS_INVOICE_INFORMATION: { path: ROUTE_KEYS.SETTINGS_INVOICE_INFORMATION, labelKey: "studio.invoiceInformation", guidanceId: "studio.invoice-information" },
  SETTINGS_INTEGRATIONS: { path: ROUTE_KEYS.SETTINGS_INTEGRATIONS, labelKey: "studio.integrations", guidanceId: "studio.integrations" },
  SETTINGS_WEBHOOKS_API: { path: ROUTE_KEYS.SETTINGS_WEBHOOKS_API, labelKey: "studio.webhooksApi", guidanceId: "studio.webhooks-api" },
  SETTINGS_USERS_PERMISSIONS: { path: ROUTE_KEYS.SETTINGS_USERS_PERMISSIONS, labelKey: "sidebar.usersPermissions", guidanceId: "people.members.access" },
  SETTINGS_AUDIT_LOGS: { path: ROUTE_KEYS.SETTINGS_AUDIT_LOGS, labelKey: "sidebar.auditLogs", guidanceId: "people.audit.access" },
};
