import React from "react";
import { Bot, CheckCircle2, KeyRound, Play, Power, Save } from "lucide-react";
import { useI18n } from "@/i18n";
import { CAPABILITIES, useEffectiveAccess } from "@/platform/access-control";
import type { AiConfiguration, AiConfigurationDraft, AiProviderEntry, AiUsageSummary } from "../../application/AiConfigurationGateway";
import { activateAiConfiguration, disableAiConfiguration, loadAiConfiguration, loadAiProviderCatalog, loadAiUsageSummary, saveAiConfiguration, setAiCredential, testAiConfiguration } from "../../runtime/aiConfigurationRuntime";
import { StudioButton, StudioPageFrame, StudioSection } from "../components/StudioPrimitives";

export function AiConfigurationView() {
  const { locale } = useI18n(); const text = (vi: string, en: string) => locale === "vi" ? vi : en;
  const canManage = useEffectiveAccess().can(CAPABILITIES.AI_CONFIGURATION_MANAGE);
  const [catalog, setCatalog] = React.useState<AiProviderEntry[]>([]); const [configuration, setConfiguration] = React.useState<AiConfiguration>();
  const [usage, setUsage] = React.useState<AiUsageSummary>();
  const [draft, setDraft] = React.useState<AiConfigurationDraft>(); const [credential, setCredentialValue] = React.useState("");
  const [fallbackCredential, setFallbackCredential] = React.useState(""); const [busy, setBusy] = React.useState(false);
  const [message, setMessage] = React.useState(""); const [error, setError] = React.useState("");

  React.useEffect(() => { const controller = new AbortController(); void Promise.all([loadAiProviderCatalog(controller.signal), loadAiConfiguration(controller.signal), loadAiUsageSummary(controller.signal)])
    .then(([providers, value, summary]) => { setCatalog(providers); setUsage(summary); commit(value); }).catch((cause) => { if (!controller.signal.aborted) setError(safeError(cause, text)); }); return () => controller.abort(); }, []);
  const commit = (value: AiConfiguration) => { const editable = value.pendingDraft ?? value; setConfiguration(value); setDraft({ primaryProvider: editable.primaryProvider, primaryModel: editable.primaryModel,
    primaryCredentialSource: editable.primaryCredentialSource, fallbackEnabled: editable.fallbackEnabled, fallbackProvider: editable.fallbackProvider,
    fallbackModel: editable.fallbackModel, fallbackCredentialSource: editable.fallbackCredentialSource, retryRateLimited: editable.retryRateLimited }); };
  const run = async (action: () => Promise<AiConfiguration>, success: string) => { setBusy(true); setError(""); setMessage(""); try { commit(await action()); setMessage(success); } catch (cause) { setError(safeError(cause, text)); } finally { setBusy(false); } };
  if (!configuration || !draft) return <div className="p-8 text-sm text-slate-500">{error || text("Đang tải cấu hình AI…", "Loading AI configuration…")}</div>;
  const primary = catalog.find((item) => item.id === draft.primaryProvider); const fallback = catalog.find((item) => item.id === draft.fallbackProvider);
  const editableCredentialState = configuration.pendingDraft ?? configuration;
  const draftValidated = configuration.pendingDraft?.isValidated ?? (configuration.status !== "ACTIVE" && configuration.isValidated);
  const selectClass = "w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm disabled:bg-slate-50 disabled:text-slate-500";
  return <StudioPageFrame title={text("Trợ lý AI", "AI Assistant")} description={text("Cấu hình nhà cung cấp phía máy chủ. Chat không thể thay đổi nhà cung cấp, model hoặc thông tin xác thực.", "Configure server-side providers. Chat cannot override the provider, model, or credential.")} locale={locale} revision={configuration.version} updatedAt={configuration.updatedAt} error={error} message={message}
    actions={canManage ? <StudioButton tone="primary" icon={<Save size={15}/>} loading={busy} disabled={busy} onClick={() => void run(() => saveAiConfiguration(draft, configuration.version), text("Đã lưu bản nháp.", "Draft saved."))}>{text("Lưu bản nháp", "Save draft")}</StudioButton> : undefined}>
    <div className="grid gap-5 xl:grid-cols-2">
      <StudioSection title={text("Nhà cung cấp chính", "Primary provider")} description={`${text("Trạng thái đang hoạt động", "Active status")}: ${configuration.status}`}>
        {configuration.status === "ACTIVE" ? <div className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm" data-ai-active-configuration="true"><strong>{text("Đang hoạt động", "Active")}</strong>: {configuration.primaryProvider} / {configuration.primaryModel}</div> : null}
        {configuration.pendingDraft ? <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm" data-ai-pending-configuration="true"><strong>{text("Bản nháp chờ kích hoạt", "Pending draft")}</strong>: {configuration.pendingDraft.primaryProvider} / {configuration.pendingDraft.primaryModel}</div> : null}
        <div className="space-y-4"><label className="block text-sm font-medium">{text("Nhà cung cấp", "Provider")}<select className={`${selectClass} mt-1`} disabled={!canManage || busy} value={draft.primaryProvider} onChange={(event) => { const provider = event.target.value as "GEMINI"|"OPENAI"; const entry = catalog.find((item) => item.id === provider); const model = entry?.models[0]; if (!model) return; const fallbackCandidate = draft.fallbackEnabled && draft.fallbackProvider === provider ? catalog.find((item) => item.id !== provider) : undefined; const fallbackModel = fallbackCandidate?.models[0]; setDraft({ ...draft, primaryProvider: provider, primaryModel: model.id, ...(fallbackCandidate && fallbackModel ? { fallbackProvider: fallbackCandidate.id, fallbackModel: fallbackModel.id } : {}) }); }}>{catalog.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label>
        <label className="block text-sm font-medium">Model<select className={`${selectClass} mt-1`} disabled={!canManage || busy} value={draft.primaryModel} onChange={(event) => setDraft({ ...draft, primaryModel: event.target.value })}>{primary?.models.map((model) => <option key={model.id} value={model.id}>{model.displayName}</option>)}</select></label>
        <label className="block text-sm font-medium">{text("Nguồn thông tin xác thực", "Credential source")}<select className={`${selectClass} mt-1`} disabled={!canManage || busy} value={draft.primaryCredentialSource} onChange={(event) => setDraft({ ...draft, primaryCredentialSource: event.target.value as "WORKSPACE"|"DEPLOYMENT" })}><option value="DEPLOYMENT">Deployment</option><option value="WORKSPACE">Workspace</option></select></label>
        {canManage && draft.primaryCredentialSource === "WORKSPACE" ? <div><label className="block text-sm font-medium">API key<input type="password" autoComplete="new-password" className={`${selectClass} mt-1`} value={credential} onChange={(event) => setCredentialValue(event.target.value)} /></label><StudioButton icon={<KeyRound size={14}/>} disabled={!credential || busy} onClick={() => void run(async () => { const value = await setAiCredential(credential, false, configuration.version); setCredentialValue(""); return value; }, text("Đã cập nhật thông tin xác thực.", "Credential updated."))}>{editableCredentialState.primaryCredentialConfigured ? text("Xoay vòng khóa", "Rotate key") : text("Đặt khóa", "Set key")}</StudioButton></div> : null}</div>
      </StudioSection>
      <StudioSection title={text("Dự phòng có kiểm soát", "Controlled fallback")} description={text("Tắt mặc định; khi bật, context AI an toàn có thể được gửi tới nhà cung cấp thứ hai.", "Off by default; enabling permits safe AI context to be sent to the second provider.")}>
        <label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={!canManage || busy} checked={draft.fallbackEnabled} onChange={(event) => { const enabled = event.target.checked; const candidate = catalog.find((item) => item.id !== draft.primaryProvider); setDraft({ ...draft, fallbackEnabled: enabled, fallbackProvider: enabled ? candidate?.id : null, fallbackModel: enabled ? candidate?.models[0]?.id : null, fallbackCredentialSource: enabled ? "DEPLOYMENT" : null }); }}/>{text("Bật failover chéo nhà cung cấp", "Enable cross-provider failover")}</label>
        <label className="mt-3 flex items-start gap-2 text-sm"><input type="checkbox" disabled={!canManage || busy} checked={draft.retryRateLimited} onChange={(event) => setDraft({ ...draft, retryRateLimited: event.target.checked })}/><span>{text("Cho phép thử lại và chuyển sang nhà cung cấp dự phòng khi nhà cung cấp trả về giới hạn 429.", "Allow retry and cross-provider failover when the provider returns rate limit 429.")}</span></label>
        {draft.fallbackEnabled ? <div className="mt-4 space-y-4"><label className="block text-sm font-medium">{text("Nhà cung cấp dự phòng", "Fallback provider")}<select className={`${selectClass} mt-1`} disabled={!canManage || busy} value={draft.fallbackProvider ?? ""} onChange={(event) => { const provider = event.target.value as "GEMINI"|"OPENAI"; const model = catalog.find((item) => item.id === provider)?.models[0]; if (model) setDraft({ ...draft, fallbackProvider: provider, fallbackModel: model.id }); }}>{catalog.filter((item) => item.id !== draft.primaryProvider).map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label className="block text-sm font-medium">Model<select className={`${selectClass} mt-1`} disabled={!canManage || busy} value={draft.fallbackModel ?? ""} onChange={(event) => setDraft({ ...draft, fallbackModel: event.target.value })}>{fallback?.models.map((model) => <option key={model.id} value={model.id}>{model.displayName}</option>)}</select></label><label className="block text-sm font-medium">{text("Nguồn thông tin xác thực", "Credential source")}<select className={`${selectClass} mt-1`} disabled={!canManage || busy} value={draft.fallbackCredentialSource ?? "DEPLOYMENT"} onChange={(event) => setDraft({ ...draft, fallbackCredentialSource: event.target.value as "WORKSPACE"|"DEPLOYMENT" })}><option value="DEPLOYMENT">Deployment</option><option value="WORKSPACE">Workspace</option></select></label>{canManage && draft.fallbackCredentialSource === "WORKSPACE" ? <div><label className="block text-sm font-medium">API key<input type="password" autoComplete="new-password" className={`${selectClass} mt-1`} value={fallbackCredential} onChange={(event) => setFallbackCredential(event.target.value)} /></label><StudioButton icon={<KeyRound size={14}/>} disabled={!fallbackCredential || busy} onClick={() => void run(async () => { const value = await setAiCredential(fallbackCredential, true, configuration.version); setFallbackCredential(""); return value; }, text("Đã cập nhật khóa dự phòng.", "Fallback credential updated."))}>{editableCredentialState.fallbackCredentialConfigured ? text("Xoay vòng khóa", "Rotate key") : text("Đặt khóa", "Set key")}</StudioButton></div> : null}</div> : null}
      </StudioSection>
    </div>
    <StudioSection className="mt-5" title={text("Xác minh và kích hoạt", "Validate and activate")} description={text("Kiểm tra dùng dữ liệu tổng hợp, không gửi bản ghi CRM.", "Connection tests use synthetic input and do not send CRM records.")} actions={canManage ? <div className="flex gap-2"><StudioButton icon={<Play size={14}/>} disabled={busy} onClick={() => void run(() => testAiConfiguration(configuration.version), text("Kiểm tra kết nối thành công.", "Connection test passed."))}>{text("Kiểm tra", "Test")}</StudioButton><StudioButton tone="primary" icon={<CheckCircle2 size={14}/>} disabled={busy || !draftValidated} onClick={() => void run(() => activateAiConfiguration(configuration.version), text("Đã kích hoạt cấu hình AI.", "AI configuration activated."))}>{text("Kích hoạt", "Activate")}</StudioButton><StudioButton tone="danger" icon={<Power size={14}/>} disabled={busy || configuration.status !== "ACTIVE"} onClick={() => void run(() => disableAiConfiguration(configuration.version), text("Đã tắt cấu hình AI.", "AI configuration disabled."))}>{text("Tắt", "Disable")}</StudioButton></div> : undefined}>
      <p className="text-sm text-slate-600">{draftValidated ? text("Bản nháp đã được xác minh.", "Draft is validated.") : text("Bản nháp chưa được xác minh.", "Draft is not validated.")}</p>
      {usage ? <dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div><dt className="text-slate-500">{text("Lượt chạy (30 ngày)", "Executions (30 days)")}</dt><dd className="font-semibold">{usage.executions}</dd></div><div><dt className="text-slate-500">{text("Thành công", "Successful")}</dt><dd className="font-semibold">{usage.successfulExecutions}</dd></div><div><dt className="text-slate-500">{text("Lần gọi provider", "Provider attempts")}</dt><dd className="font-semibold">{usage.providerAttempts}</dd></div><div><dt className="text-slate-500">Tokens</dt><dd className="font-semibold">{usage.inputTokens + usage.outputTokens}</dd></div></dl> : null}
    </StudioSection>
  </StudioPageFrame>;
}

function safeError(cause: unknown, text: (vi: string, en: string) => string): string {
  const code = typeof cause === "object" && cause && "code" in cause ? String((cause as { code?: unknown }).code) : "";
  if (code.includes("ACCESS_DENIED")) return text("Bạn không có quyền quản lý cấu hình AI.", "You do not have permission to manage AI configuration.");
  if (code.includes("VERSION_CONFLICT")) return text("Cấu hình đã thay đổi. Hãy tải lại.", "Configuration changed. Reload and try again.");
  if (code.includes("RATE_LIMITED")) return text("Nhà cung cấp đang giới hạn lưu lượng.", "The provider is rate limited.");
  return text("Không thể hoàn tất thao tác cấu hình AI.", "The AI configuration operation could not be completed.");
}
