import { CAPABILITIES } from "@/platform/access-control";
import type { PilotMetricDefinition, PilotStepDefinition } from "./pilotAcceptance.types";

export const PILOT_STEP_DEFINITIONS: readonly PilotStepDefinition[] = [
  {
    id: "lead-ingress",
    sequence: 1,
    title: { vi: "Tiếp nhận Lead và chống trùng", en: "Lead intake and deduplication" },
    purpose: { vi: "Xác nhận nhập tay, import và webhook tạo đúng Lead mà không nhân bản dữ liệu.", en: "Verify manual, import, and webhook intake without duplicating lead data." },
    actorRoles: ["SALES", "WORKSPACE_ADMIN", "PRODUCT_ENGINEERING"],
    routeKey: "LEADS",
    requiredCapabilities: [CAPABILITIES.LEADS_CREATE, CAPABILITIES.LEADS_READ],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Có bằng chứng cho cả ba kênh tiếp nhận.", en: "Evidence exists for all three intake channels." },
      { vi: "Webhook lặp lại khớp bản ghi hiện hữu và có log retry/idempotency.", en: "A repeated webhook matches the existing record with retry/idempotency evidence." },
    ],
  },
  {
    id: "owner-and-sla",
    sequence: 2,
    title: { vi: "Owner, phạm vi xem và SLA", en: "Owner, visibility, and SLA" },
    purpose: { vi: "Xác nhận Lead thuộc đúng Sales, có audit và không biến mất sau khi lưu.", en: "Verify the lead belongs to the correct salesperson, is audited, and remains visible after save." },
    actorRoles: ["SALES", "SALES_MANAGER"],
    routeKey: "LEAD_DETAIL",
    requiredCapabilities: [CAPABILITIES.LEADS_READ, CAPABILITIES.LEADS_UPDATE],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Owner khớp người tạo hoặc bàn giao hợp lệ.", en: "Owner matches the creator or an authorized reassignment." },
      { vi: "SLA phản hồi đầu tiên và phạm vi Của tôi/Của đội được xác nhận.", en: "First-response SLA and Mine/Team visibility are verified." },
    ],
  },
  {
    id: "customer-conversion",
    sequence: 3,
    title: { vi: "Chuyển đổi và Customer 360", en: "Conversion and Customer 360" },
    purpose: { vi: "Chuyển Lead thành Contact/Organization mà không mất lịch sử hoặc tạo quan hệ mồ côi.", en: "Convert a lead into Contact/Organization without losing history or creating orphan relationships." },
    actorRoles: ["SALES"],
    routeKey: "LEAD_QUALIFY",
    requiredCapabilities: [CAPABILITIES.LEADS_QUALIFY, CAPABILITIES.CONTACTS_CREATE, CAPABILITIES.ORGANIZATIONS_CREATE],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Lead, Contact và Organization dùng cùng một quan hệ chuẩn.", en: "Lead, Contact, and Organization share one canonical relationship." },
      { vi: "Lịch sử trước chuyển đổi vẫn hiển thị trong Customer 360.", en: "Pre-conversion history remains visible in Customer 360." },
    ],
  },
  {
    id: "deal-pipeline",
    sequence: 4,
    title: { vi: "Cơ hội và sức khỏe pipeline", en: "Deal and pipeline health" },
    purpose: { vi: "Xác nhận Deal có owner, next step, ngày đóng và chỉ báo pipeline đúng.", en: "Verify the deal has an owner, next step, close date, and correct pipeline signals." },
    actorRoles: ["SALES", "SALES_MANAGER"],
    routeKey: "DEAL_DETAIL",
    requiredCapabilities: [CAPABILITIES.DEALS_CREATE, CAPABILITIES.DEALS_UPDATE],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Deal liên kết đúng Lead và quan hệ khách hàng.", en: "The deal links to the correct lead and customer relationship." },
      { vi: "Next step, hạn và forecast category được kiểm tra.", en: "Next step, due date, and forecast category are reviewed." },
    ],
  },
  {
    id: "quote-approval",
    sequence: 5,
    title: { vi: "Báo giá và phê duyệt", en: "Quote and approval" },
    purpose: { vi: "Xác nhận chiết khấu, tổng tiền và bằng chứng phê duyệt được giữ đúng.", en: "Verify discount, totals, and approval evidence are retained." },
    actorRoles: ["SALES", "SALES_MANAGER"],
    routeKey: "QUOTE_DETAIL",
    requiredCapabilities: [CAPABILITIES.QUOTES_CREATE, CAPABILITIES.QUOTES_APPROVE],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Báo giá liên kết đúng Deal và khách hàng.", en: "The quote links to the correct deal and customer." },
      { vi: "Báo giá cần phê duyệt chỉ được chấp nhận sau khi có quyết định.", en: "A quote requiring approval is accepted only after an approval decision." },
    ],
  },
  {
    id: "order-creation",
    sequence: 6,
    title: { vi: "Tạo đơn hàng từ báo giá", en: "Create order from quote" },
    purpose: { vi: "Xác nhận đơn hàng giữ nguyên nguồn, khách hàng và tổng thương mại.", en: "Verify the order preserves its source, customer, and commercial totals." },
    actorRoles: ["SALES"],
    routeKey: "ORDER_DETAIL",
    requiredCapabilities: [CAPABILITIES.ORDERS_CREATE, CAPABILITIES.ORDERS_READ],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Order truy vết được Quote và Deal nguồn.", en: "The order traces back to its source quote and deal." },
      { vi: "Quan hệ khách hàng và tổng tiền khớp báo giá được chấp nhận.", en: "Customer relationship and totals match the accepted quote." },
    ],
  },
  {
    id: "payment-reconciliation",
    sequence: 7,
    title: { vi: "Thanh toán và đối soát", en: "Payment and reconciliation" },
    purpose: { vi: "Xác nhận lịch thanh toán, giao dịch, phân bổ và đối soát theo đúng đơn hàng.", en: "Verify payment schedule, transactions, allocations, and reconciliation for the order." },
    actorRoles: ["FINANCE"],
    routeKey: "PAYMENT_DETAIL",
    requiredCapabilities: [CAPABILITIES.PAYMENTS_READ, CAPABILITIES.PAYMENTS_RECORD_MANUAL, CAPABILITIES.PAYMENTS_RECONCILE],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Tổng nghĩa vụ, tiền đã thu và còn phải thu đối chiếu được.", en: "Obligations, collected amount, and outstanding amount reconcile." },
      { vi: "Giao dịch thành công có trạng thái đối soát rõ ràng.", en: "Successful transactions have explicit reconciliation status." },
    ],
  },
  {
    id: "shipping-delivery",
    sequence: 8,
    title: { vi: "Vận đơn và bằng chứng giao hàng", en: "Shipping and delivery evidence" },
    purpose: { vi: "Xác nhận booking, retry và delivered evidence thuộc đúng Order.", en: "Verify booking, retry, and delivery evidence belong to the correct order." },
    actorRoles: ["OPERATIONS"],
    routeKey: "SHIPPING_DETAIL",
    requiredCapabilities: [CAPABILITIES.SHIPPING_CREATE],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Vận đơn có provider lifecycle và deliveredAt hợp lệ.", en: "The shipment has a provider lifecycle and valid deliveredAt evidence." },
      { vi: "Retry không tạo nhiều shipment group ngoài ý muốn.", en: "Retries do not create unintended shipment groups." },
    ],
  },
  {
    id: "return-resolution",
    sequence: 9,
    title: { vi: "Đổi trả và bằng chứng xử lý", en: "Return and resolution evidence" },
    purpose: { vi: "Xác nhận nhận hàng thực tế trước khi hoàn tiền hoặc giao thay thế.", en: "Verify actual receipt before refund or replacement fulfillment." },
    actorRoles: ["OPERATIONS", "FINANCE"],
    routeKey: "RETURN_DETAIL",
    requiredCapabilities: [CAPABILITIES.RETURNS_UPDATE, CAPABILITIES.RETURNS_RESOLVE],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Return có receivedAt và kiểm tra hàng trả.", en: "The return has receivedAt and returned-item inspection." },
      { vi: "Resolution liên kết Payment refund hoặc Shipping replacement đã hoàn tất.", en: "Resolution links to a completed payment refund or replacement shipment." },
    ],
  },
  {
    id: "support-and-reconciliation",
    sequence: 10,
    title: { vi: "Hỗ trợ và đối soát cuối hành trình", en: "Support and final reconciliation" },
    purpose: { vi: "Xác nhận Support/Task, Customer 360, Dashboard và Reports cùng phản ánh một chuỗi dữ liệu.", en: "Verify Support/Task, Customer 360, Dashboard, and Reports reflect the same data chain." },
    actorRoles: ["OPERATIONS", "WORKSPACE_ADMIN", "PRODUCT_ENGINEERING"],
    routeKey: "SUPPORT_CASE_DETAIL",
    requiredCapabilities: [CAPABILITIES.SUPPORT_CREATE, CAPABILITIES.TASKS_CREATE, CAPABILITIES.REPORTS_READ, CAPABILITIES.AUDIT_READ],
    manualEvidenceRequired: true,
    expectedEvidence: [
      { vi: "Support có Task phụ trách và SLA được ghi nhận.", en: "Support has assigned work and recorded SLA evidence." },
      { vi: "Không có bản ghi mồ côi; Dashboard, Reports và dữ liệu gốc khớp.", en: "There are no orphan records; Dashboard, Reports, and source data reconcile." },
    ],
  },
] as const;

export const PILOT_METRIC_DEFINITIONS: readonly PilotMetricDefinition[] = [
  { id: "lead-create-duration", label: { vi: "Thời gian trung vị tạo Lead", en: "Median Lead creation time" }, unit: "milliseconds", lowerIsBetter: true, evidenceOwner: { vi: "Vận hành Sales", en: "Sales operations" } },
  { id: "deal-create-duration", label: { vi: "Thời gian trung vị tạo Deal", en: "Median Deal creation time" }, unit: "milliseconds", lowerIsBetter: true, evidenceOwner: { vi: "Vận hành Sales", en: "Sales operations" } },
  { id: "form-abandonment-rate", label: { vi: "Tỷ lệ bỏ dở form", en: "Form abandonment rate" }, unit: "rate", lowerIsBetter: true, target: 0.15, evidenceOwner: { vi: "Product Analytics", en: "Product analytics" } },
  { id: "missing-owner-next-step-rate", label: { vi: "Tỷ lệ thiếu owner hoặc next step", en: "Missing owner or next-step rate" }, unit: "rate", lowerIsBetter: true, target: 0, evidenceOwner: { vi: "Quản lý Sales", en: "Sales management" } },
  { id: "lead-sla-rate", label: { vi: "Tỷ lệ Lead đạt SLA", en: "Lead SLA compliance rate" }, unit: "rate", lowerIsBetter: false, target: 0.9, evidenceOwner: { vi: "Quản lý Sales", en: "Sales management" } },
  { id: "outside-crm-action-count", label: { vi: "Số thao tác ngoài CRM", en: "Actions completed outside CRM" }, unit: "count", lowerIsBetter: true, target: 0, evidenceOwner: { vi: "Điều phối pilot", en: "Pilot coordinator" } },
  { id: "dashboard-report-reconciliation-delta", label: { vi: "Sai lệch Dashboard–Reports", en: "Dashboard–Reports reconciliation delta" }, unit: "currency-delta", lowerIsBetter: true, target: 0, evidenceOwner: { vi: "Tài chính và Product", en: "Finance and Product" } },
  { id: "order-operations-quality-rate", label: { vi: "Chất lượng vận hành đơn hàng", en: "Order operations quality rate" }, unit: "rate", lowerIsBetter: false, target: 0.95, evidenceOwner: { vi: "Tài chính và vận hành", en: "Finance and operations" } },
] as const;
