export type LeadSystemColumnKey =
  | "tags"
  | "salutation"
  | "name"
  | "lastName"
  | "firstName"
  | "title"
  | "phone"
  | "companyPhone"
  | "email"
  | "personalEmail"
  | "companyName"
  | "address"
  | "city"
  | "district"
  | "ward"
  | "source"
  | "companyType"
  | "industry"
  | "description"
  | "ownerId"
  | "createdBy"
  | "createdAt"
  | "updatedBy"
  | "updatedAt"
  | "status"
  | "nextFollowUpAt"
  | "lastInteractionAt"
  | "disqualificationReason"
  | "recontactAt"
  | "interestedProducts"
  | "campaignId";

/** Custom backend fields are technical keys supplied by ObjectSchemaRegistry. */
export type ColumnKeyType = LeadSystemColumnKey | (string & {});
