import type { CustomerDisplay as Customer } from "@/modules/customers";

export const CUSTOMER_RELATIONSHIP_MIGRATION_RECORDS: Customer[] = [
  {
    id: "c1",
    customerCode: "KH0000001",
    type: "COMPANY",
    displayName: "Công ty TNHH TechVision",
    companyName: "Công ty TNHH TechVision",
    phone: "0365686791",
    email: "contact@techvision.vn",
    taxCode: "0314959291",
    segment: "Enterprise",
    ownerId: "u5", // CSM Phạm Thi D
    industry: "Hạ tầng & Giải pháp đám mây",
    address: "Tòa nhà Keangnam, Cầu Giấy, Hà Nội",
    source: "Hội thảo / Webinar",
    status: "active",
    tags: ["VIP SLA", "Enterprise", "Active Customer"],
    totalRevenue: 336000000,
    outstandingDebt: 0,
    purchaseCount: 2,
    lastPurchaseDate: "2025-12-12",
    purchaseCycleDays: 90,
    mrr: 28000000,
    health: "Tốt",
    renewalDate: "2026-12-12",
    productsOwned: [
      { id: "po1", productId: "prod_3", productNameSnapshot: "Enterprise ERP Suite 2024", purchaseDate: "2025-12-12", quantity: 1, amount: 28000000, status: "active", expiryDate: "2026-12-12" },
      { id: "po2", productId: "prod_4", productNameSnapshot: "Dịch vụ Triển khai Onboarding & Đào Tạo", purchaseDate: "2025-12-12", quantity: 1, amount: 0, status: "active", expiryDate: "2026-07-01" }
    ]
  },
  {
    id: "c2",
    customerCode: "KH0000002",
    type: "COMPANY",
    displayName: "Công ty TNHH TechHub",
    companyName: "Công ty TNHH TechHub",
    phone: "0365111222",
    email: "contact@techhub.vn",
    taxCode: "0314999111",
    segment: "Enterprise",
    ownerId: "u5",
    industry: "Thương mại điện tử & Logistics",
    address: "Tòa nhà Viettel, Quận 10, TP.HCM",
    source: "Tư vấn trực tiếp",
    status: "churned",
    tags: ["Renewal Critical", "Enterprise"],
    totalRevenue: 540000000,
    outstandingDebt: 45000000,
    purchaseCount: 4,
    lastPurchaseDate: "2026-02-15",
    purchaseCycleDays: 180,
    mrr: 45000000,
    health: "Cảnh báo",
    renewalDate: "2026-11-20",
    productsOwned: [
      { id: "po3", productId: "prod_2", productNameSnapshot: "Unicore CRM Cloud Suite", purchaseDate: "2026-02-15", quantity: 1, amount: 45000000, status: "active", expiryDate: "2026-11-20" }
    ]
  },
  {
    id: "c3",
    customerCode: "KH0000003",
    type: "INDIVIDUAL",
    displayName: "Nguyễn Minh Tuấn",
    individualName: "Nguyễn Minh Tuấn",
    phone: "0912345678",
    email: "tuan.nguyen@gmail.com",
    segment: "Standard",
    ownerId: "u3", // Hoàng Lê
    address: "72 Nguyễn Trãi, Thanh Xuân, Hà Nội",
    source: "Facebook Ads",
    status: "active",
    tags: ["Retail", "B2C Loyalty"],
    totalRevenue: 15400000,
    outstandingDebt: 0,
    purchaseCount: 5,
    lastPurchaseDate: "2026-05-18",
    purchaseCycleDays: 30,
    mrr: 0,
    health: "Trung bình",
    productsOwned: []
  },
  {
    id: "c4",
    customerCode: "KH0000004",
    type: "COMPANY",
    displayName: "Tập đoàn Vận tải Viễn Đông",
    companyName: "Tập đoàn Vận tải Viễn Đông",
    phone: "0388 777 666",
    email: "tuan.pm@viendongtrans.vn",
    segment: "Enterprise",
    ownerId: "u1",
    address: "Bình Thạnh, TP.HCM",
    source: "Google Ads",
    status: "active",
    tags: ["Logistics", "Enterprise", "Active Customer"],
    totalRevenue: 500000000,
    outstandingDebt: 0,
    purchaseCount: 1,
    lastPurchaseDate: "2026-06-12",
    mrr: 0,
    health: "Tốt",
    productsOwned: []
  },
  {
    id: "c5",
    customerCode: "KH0000005",
    type: "COMPANY",
    displayName: "Công ty Cổ phần Đầu tư Hoàng Gia",
    companyName: "Công ty Cổ phần Đầu tư Hoàng Gia",
    phone: "0987 654 321",
    email: "lephuong@royalinvest.com.vn",
    segment: "Key Account",
    ownerId: "u1",
    address: "12 Láng Hạ, Đống Đa, Hà Nội",
    source: "Google Search",
    status: "active",
    tags: ["Finance", "Active Customer"],
    totalRevenue: 450000000,
    outstandingDebt: 0,
    purchaseCount: 1,
    lastPurchaseDate: "2026-06-11",
    mrr: 0,
    health: "Tốt",
    productsOwned: []
  }
];
