import type { FieldGuidance } from "@/guidance/domain/guidance.types";

export const FIELD_GUIDANCE: FieldGuidance[] = [
  {
    helpKey: "field.customers.relationship-integrity",
    title: { vi: "Tính nhất quán quan hệ khách hàng", en: "Customer relationship integrity" },
    purpose: { vi: "Kiểm tra Contact hoặc Organization nguồn và các giao dịch có cùng tham chiếu một quan hệ chuẩn hay không.", en: "Checks whether the source Contact or Organization and transactions resolve to the same canonical relationship." },
    example: { vi: "Deal, Quote và Order của cùng khách hàng phải có cùng quan hệ người mua; Payment, Shipping và Return phải truy ngược được về Order đó.", en: "A customer's Deal, Quote, and Order must share the same buyer relationship; Payment, Shipping, and Return must trace back to that Order." },
    impact: { vi: "Liên kết sai có thể làm thiếu timeline, sai tổng khách hàng hoặc tạo bản ghi mồ côi.", en: "Incorrect links can cause an incomplete timeline, wrong customer totals, or orphan records." },
    requiredWhen: { vi: "Được hệ thống đánh giá tự động; cảnh báo phải được rà soát trước khi dùng Customer 360 để đối soát.", en: "Evaluated automatically; warnings should be reviewed before using Customer 360 for reconciliation." },
    keywords: { vi: "customer 360 quan hệ mồ côi trùng dữ liệu", en: "customer 360 relationship orphan duplicate data" },
  },
  {
    helpKey: "field.orders.customer",
    title: { vi: "Buyer của đơn hàng", en: "Order buyer" },
    purpose: { vi: "Xác định người mua chịu trách nhiệm cho cam kết mua và liên kết lịch sử giao dịch.", en: "Identifies the buyer responsible for the purchase commitment and links transaction history." },
    example: { vi: "Chọn Contact hoặc Organization đang mua; Customer chỉ được hệ thống hình thành sau khi có bằng chứng mua hàng.", en: "Select the buying Contact or Organization; the system forms a Customer only after purchase evidence exists." },
    impact: { vi: "Ảnh hưởng báo cáo khách hàng, bằng chứng thương mại và các quy trình hỗ trợ sau bán.", en: "Affects customer reporting, commercial evidence, and after-sales support." },
    requiredWhen: { vi: "Luôn bắt buộc khi tạo đơn; không yêu cầu Customer projection đã tồn tại.", en: "Always required when creating an order; an existing Customer projection is not required." },
    keywords: { vi: "buyer người mua khách hàng đơn hàng", en: "buyer customer order" },
  },
  {
    helpKey: "field.orders.recipient",
    title: { vi: "Người nhận và địa chỉ giao hàng", en: "Recipient and delivery address" },
    purpose: { vi: "Cung cấp dữ liệu giao nhận mà Vận đơn sử dụng khi tạo yêu cầu với nhà vận chuyển.", en: "Provides delivery data used by Shipping when creating a provider request." },
    example: { vi: "Tên người nhận, số điện thoại có thể liên lạc và địa chỉ giao hàng đầy đủ.", en: "Recipient name, reachable phone number, and complete delivery address." },
    impact: { vi: "Thông tin thiếu hoặc sai có thể làm vận đơn không đủ điều kiện hoặc giao hàng thất bại.", en: "Missing or incorrect data can make shipping ineligible or cause delivery failure." },
    requiredWhen: { vi: "Bắt buộc với đơn cần giao hàng.", en: "Required for orders that need delivery." },
  },
  {
    helpKey: "field.orders.payment-plan",
    title: { vi: "Kế hoạch thanh toán", en: "Payment plan" },
    purpose: { vi: "Mô tả các đợt thu dự kiến, mục đích, thời điểm và điều khoản; không phải giao dịch đã thu tiền.", en: "Describes expected installments, purpose, timing, and terms; it is not a completed payment transaction." },
    example: { vi: "Đặt cọc 30% khi xác nhận, 70% trước khi giao hàng.", en: "30% deposit at confirmation, 70% before delivery." },
    impact: { vi: "Giúp vận hành biết kỳ vọng thu tiền; giao dịch thực tế vẫn phải ghi nhận trong Thanh toán.", en: "Sets collection expectations; actual transactions must still be recorded in Payments." },
    requiredWhen: { vi: "Theo chính sách đơn hàng và phương thức bán của workspace.", en: "As required by workspace order and selling policy." },
  },
  {
    helpKey: "field.shipping.provider",
    title: { vi: "Nhà vận chuyển", en: "Shipping provider" },
    purpose: { vi: "Xác định bên tiếp nhận yêu cầu giao hàng và trạng thái bên ngoài sẽ được đồng bộ.", en: "Identifies the party receiving the delivery request and whose external status is synchronized." },
    example: { vi: "Chọn nhà vận chuyển đã được bật trong Thiết lập hoặc Manual khi xử lý thủ công.", en: "Choose an enabled provider from Settings or Manual for offline handling." },
    impact: { vi: "Ảnh hưởng cách tạo mã vận đơn, đồng bộ trạng thái và xử lý thử lại.", en: "Affects booking creation, status synchronization, and retry handling." },
    requiredWhen: { vi: "Bắt buộc khi tạo vận đơn.", en: "Required when creating a shipping booking." },
  },
  {
    helpKey: "field.returns.eligibility",
    title: { vi: "Kết quả kiểm tra điều kiện đổi/trả", en: "Return eligibility result" },
    purpose: { vi: "Giải thích yêu cầu có đáp ứng chính sách hay không trước khi người có quyền ra quyết định phê duyệt.", en: "Explains whether the request satisfies policy before an authorized user makes the approval decision." },
    example: { vi: "Trong thời hạn đổi/trả và số lượng yêu cầu không vượt số lượng đã mua.", en: "Within the return window and requested quantity does not exceed purchased quantity." },
    impact: { vi: "Không tự động thay thế quyết định phê duyệt; ngoại lệ phải có lý do rõ ràng.", en: "Does not replace the approval decision; overrides require a clear reason." },
    requiredWhen: { vi: "Luôn được đánh giá trước khi phê duyệt hoặc từ chối.", en: "Always evaluated before approval or rejection." },
  },

  {
    helpKey: "field.leads.owner",
    title: { vi: "Người phụ trách Lead", en: "Lead owner" },
    purpose: { vi: "Xác định người chịu trách nhiệm phản hồi, xác minh và theo dõi Lead.", en: "Identifies the person accountable for responding to, verifying, and following up the Lead." },
    example: { vi: "Khi bạn tạo Lead, hệ thống mặc định giao cho bạn. Người có quyền phân công mới có thể chọn thành viên khác trong phạm vi cho phép.", en: "When you create a Lead, it is assigned to you by default. Only a permitted assigner can choose another member within scope." },
    impact: { vi: "Ảnh hưởng hàng đợi công việc, SLA, báo cáo hiệu suất và khả năng tìm lại bản ghi.", en: "Affects work queues, SLA, performance reporting, and record visibility." },
    requiredWhen: { vi: "Luôn có khi Lead được lưu; thay đổi người phụ trách phải có lý do.", en: "Always set when a Lead is saved; changing it requires a reason." },
    keywords: { vi: "owner người phụ trách giao lead bàn giao của tôi", en: "owner assignee lead handover mine" },
  },
  {
    helpKey: "field.deals.owner",
    title: { vi: "Người phụ trách cơ hội", en: "Opportunity owner" },
    purpose: { vi: "Xác định người chịu trách nhiệm thúc đẩy cơ hội, cập nhật bước tiếp theo và dự báo.", en: "Identifies the person accountable for progressing the opportunity, maintaining the next step, and forecasting." },
    example: { vi: "Cơ hội mới mặc định thuộc người tạo; chỉ người có quyền mới được bàn giao cho thành viên khác.", en: "A new opportunity belongs to its creator by default; only an authorized user may hand it to another member." },
    impact: { vi: "Ảnh hưởng pipeline cá nhân/đội, forecast, KPI và phạm vi xem bản ghi.", en: "Affects personal/team pipeline, forecast, KPI, and record visibility." },
    requiredWhen: { vi: "Luôn có khi cơ hội được lưu; bàn giao phải ghi lý do.", en: "Always set when an opportunity is saved; handover requires a reason." },
    keywords: { vi: "owner người phụ trách cơ hội bàn giao pipeline", en: "owner opportunity assignee handover pipeline" },
  },

  {
    helpKey: "field.leads.source",
    title: { vi: "Nguồn khách hàng tiềm năng", en: "Lead source" },
    purpose: { vi: "Cho biết nhu cầu được tiếp nhận từ kênh nào để đánh giá chất lượng và hiệu quả tiếp nhận.", en: "Shows which channel captured the need so intake quality and effectiveness can be assessed." },
    example: { vi: "Biểu mẫu website, giới thiệu, cuộc gọi đến hoặc sự kiện.", en: "Website form, referral, inbound call, or event." },
    impact: { vi: "Ảnh hưởng báo cáo nguồn, phân công và cách theo dõi tiếp theo.", en: "Affects source reporting, assignment, and follow-up planning." },
    requiredWhen: { vi: "Nên có ngay khi tiếp nhận; bắt buộc nếu quy trình phân công hoặc báo cáo dựa trên nguồn.", en: "Recommended at intake and required when assignment or reporting depends on source." },
    keywords: { vi: "nguồn lead kênh tiếp nhận website giới thiệu", en: "lead source intake channel website referral" },
  },
  {
    helpKey: "field.leads.qualification-outcome",
    title: { vi: "Kết quả xác minh", en: "Qualification outcome" },
    purpose: { vi: "Xác định bước nghiệp vụ tiếp theo sau khi đã kiểm tra nhu cầu và dữ liệu khách hàng tiềm năng.", en: "Determines the next business path after the lead's need and information have been verified." },
    example: { vi: "Tạo quan hệ, tạo cơ hội, bán trực tiếp hoặc không tiếp tục.", en: "Create relationship, create opportunity, direct sale, or stop." },
    impact: { vi: "Có thể tạo bản ghi mới và thay đổi hàng đợi xử lý tiếp theo.", en: "May create new records and change the downstream work queue." },
    requiredWhen: { vi: "Bắt buộc khi hoàn tất bước xác minh.", en: "Required when qualification is completed." },
  },
  {
    helpKey: "field.deals.stage",
    title: { vi: "Giai đoạn cơ hội", en: "Opportunity stage" },
    purpose: { vi: "Phản ánh mốc tiến triển thực tế của cơ hội trong quy trình bán hàng.", en: "Represents the opportunity's real progress milestone in the sales process." },
    example: { vi: "Chỉ chuyển giai đoạn sau khi có cuộc trao đổi, xác nhận nhu cầu hoặc bằng chứng tương ứng.", en: "Advance only after a conversation, need confirmation, or equivalent evidence." },
    impact: { vi: "Ảnh hưởng pipeline, dự báo và công việc ưu tiên.", en: "Affects pipeline, forecasting, and work prioritization." },
    requiredWhen: { vi: "Luôn bắt buộc với cơ hội đang được theo dõi.", en: "Always required for a tracked opportunity." },
  },
  {
    helpKey: "field.quotes.valid-until",
    title: { vi: "Hiệu lực báo giá", en: "Quote validity" },
    purpose: { vi: "Xác định thời điểm đề xuất thương mại hết hiệu lực và cần được xem xét lại.", en: "Defines when the commercial proposal expires and must be reviewed again." },
    example: { vi: "Có hiệu lực đến hết ngày được ghi trên báo giá.", en: "Valid through the date stated on the quote." },
    impact: { vi: "Ảnh hưởng việc phát hành, chấp nhận và khả năng tạo đơn hàng từ báo giá.", en: "Affects issuance, acceptance, and order creation from the quote." },
    requiredWhen: { vi: "Theo chính sách báo giá của workspace.", en: "As required by the workspace quote policy." },
  },
  {
    helpKey: "field.quotes.discount",
    title: { vi: "Chiết khấu báo giá", en: "Quote discount" },
    purpose: { vi: "Điều chỉnh giá thương mại theo dòng hàng hoặc toàn báo giá trong phạm vi được phép.", en: "Adjusts commercial pricing by line or quote within permitted limits." },
    example: { vi: "Chiết khấu theo phần trăm hoặc số tiền theo chính sách bán hàng.", en: "Percentage or amount discount according to sales policy." },
    impact: { vi: "Thay đổi tổng tiền, lợi nhuận và có thể kích hoạt yêu cầu phê duyệt.", en: "Changes totals and margin and may trigger approval." },
    requiredWhen: { vi: "Chỉ nhập khi có thỏa thuận hoặc chính sách cho phép.", en: "Use only when supported by an agreement or policy." },
  },
  {
    helpKey: "field.payments.reference",
    title: { vi: "Mã tham chiếu thanh toán", en: "Payment reference" },
    purpose: { vi: "Liên kết giao dịch trong CRM với chứng từ ngân hàng, cổng thanh toán hoặc biên nhận thực tế.", en: "Links the CRM transaction to a bank record, payment gateway, or real receipt." },
    example: { vi: "Mã giao dịch ngân hàng hoặc mã biên nhận không trùng.", en: "A unique bank transaction or receipt reference." },
    impact: { vi: "Hỗ trợ đối soát, điều tra trùng giao dịch và kiểm tra hoàn tiền.", en: "Supports reconciliation, duplicate investigation, and refund verification." },
    requiredWhen: { vi: "Bắt buộc khi phương thức thanh toán cung cấp mã tham chiếu.", en: "Required when the payment method provides a reference." },
  },
  {
    helpKey: "field.shipping.pickup-location",
    title: { vi: "Điểm lấy hàng", en: "Pickup location" },
    purpose: { vi: "Xác định nơi nhà vận chuyển đến nhận hàng và người liên hệ tại điểm lấy.", en: "Defines where the provider collects the parcel and who can be contacted there." },
    example: { vi: "Kho đang hoạt động với địa chỉ đầy đủ và số điện thoại liên hệ được.", en: "An active warehouse with a complete address and reachable phone number." },
    impact: { vi: "Ảnh hưởng phí, khả năng tiếp nhận và thời gian lấy hàng.", en: "Affects fees, provider acceptance, and pickup timing." },
    requiredWhen: { vi: "Bắt buộc khi tạo vận đơn cần nhà vận chuyển đến lấy hàng.", en: "Required when the provider must collect the parcel." },
  },
  {
    helpKey: "field.returns.resolution",
    title: { vi: "Phương án xử lý đổi / trả", en: "Return resolution" },
    purpose: { vi: "Xác định yêu cầu sẽ được hoàn tiền, gửi hàng thay thế hoặc xử lý theo phương án được phép khác.", en: "Defines whether the request will be refunded, replaced, or handled through another allowed resolution." },
    example: { vi: "Hoàn tiền sau khi nhận hàng hoặc gửi sản phẩm thay thế.", en: "Refund after receipt or ship a replacement product." },
    impact: { vi: "Quyết định bằng chứng cần có từ Thanh toán hoặc Vận đơn trước khi hoàn tất.", en: "Determines the Payment or Shipping evidence required before completion." },
    requiredWhen: { vi: "Bắt buộc trước khi phê duyệt yêu cầu.", en: "Required before approval." },
  },
  {
    helpKey: "field.support.priority",
    title: { vi: "Mức ưu tiên phiếu hỗ trợ", en: "Support priority" },
    purpose: { vi: "Phản ánh mức độ ảnh hưởng và thời gian cần phản hồi để sắp xếp xử lý.", en: "Represents impact and response urgency for work prioritization." },
    example: { vi: "Ưu tiên cao khi nhiều người dùng bị gián đoạn hoặc có rủi ro tài chính rõ ràng.", en: "High priority when many users are blocked or clear financial risk exists." },
    impact: { vi: "Ảnh hưởng hàng đợi, lần theo dõi và kỳ vọng xử lý.", en: "Affects queues, follow-up, and handling expectations." },
    requiredWhen: { vi: "Luôn bắt buộc khi tạo phiếu hỗ trợ.", en: "Always required when creating a support ticket." },
  },
  {
    helpKey: "field.tasks.due-at",
    title: { vi: "Hạn xử lý công việc", en: "Task due time" },
    purpose: { vi: "Xác định thời điểm hành động cần hoàn thành để người phụ trách ưu tiên đúng.", en: "Defines when the action must be complete so the owner can prioritize correctly." },
    example: { vi: "Chọn ngày và giờ phù hợp với cam kết hoặc lần hẹn tiếp theo.", en: "Choose a date and time aligned with the commitment or next follow-up." },
    impact: { vi: "Ảnh hưởng Công việc của tôi, Lịch và cảnh báo quá hạn.", en: "Affects My Work, Calendar, and overdue alerts." },
    requiredWhen: { vi: "Bắt buộc khi công việc có cam kết thời gian.", en: "Required when the task has a time commitment." },
  },
  {
    helpKey: "field.organizations.representative-role",
    title: { vi: "Vai trò người đại diện", en: "Representative role" },
    purpose: { vi: "Giải thích một liên hệ đại diện cho tổ chức theo trách nhiệm nào trong quan hệ.", en: "Explains how a contact represents the organization within the relationship." },
    example: { vi: "Người quyết định, người mua, kế toán hoặc đầu mối vận hành.", en: "Decision maker, buyer, finance contact, or operations contact." },
    impact: { vi: "Giúp chọn đúng người khi bán hàng, giao nhận, thanh toán hoặc hỗ trợ.", en: "Helps select the right person for sales, delivery, payment, or support." },
    requiredWhen: { vi: "Nên có khi liên kết một liên hệ với tổ chức.", en: "Recommended when linking a contact to an organization." },
  },
  {
    helpKey: "field.customers.health-score",
    title: { vi: "Điểm sức khỏe khách hàng", en: "Customer health score" },
    purpose: { vi: "Tổng hợp các tín hiệu để hỗ trợ ưu tiên chăm sóc và phát hiện rủi ro quan hệ.", en: "Combines signals to support care prioritization and relationship-risk detection." },
    example: { vi: "Điểm giảm khi có phiếu hỗ trợ quá hạn hoặc tín hiệu giao dịch suy giảm.", en: "The score may fall with overdue support work or declining transaction signals." },
    impact: { vi: "Ảnh hưởng thứ tự ưu tiên nhưng không tự thay đổi trạng thái khách hàng.", en: "Affects prioritization but does not automatically change customer state." },
    requiredWhen: { vi: "Được hệ thống tính khi có đủ tín hiệu; không phải trường người dùng tự nhập.", en: "Calculated when enough signals exist; it is not manually entered." },
  },
  {
    helpKey: "field.deals.next-step",
    title: { vi: "Bước tiếp theo của cơ hội", en: "Opportunity next step" },
    purpose: { vi: "Biến ý định bán hàng thành một hành động cụ thể có thời hạn để cơ hội không bị bỏ quên.", en: "Turns sales intent into a concrete, time-bound action so the opportunity is not forgotten." },
    example: { vi: "Xác nhận phạm vi giải pháp với khách hàng trước 15:00 ngày mai.", en: "Confirm the solution scope with the customer by 3:00 PM tomorrow." },
    impact: { vi: "Cơ hội thiếu hoặc quá hạn bước tiếp theo sẽ được cảnh báo trên pipeline và ưu tiên cho người phụ trách.", en: "Opportunities with a missing or overdue next step are flagged in the pipeline and prioritized for the owner." },
    requiredWhen: { vi: "Bắt buộc với mọi cơ hội đang mở.", en: "Required for every open opportunity." },
    keywords: { vi: "cơ hội bước tiếp theo hạn follow up", en: "opportunity next step due follow up" },
  },
  {
    helpKey: "field.deals.forecast-category",
    title: { vi: "Nhóm dự báo cơ hội", en: "Opportunity forecast category" },
    purpose: { vi: "Thể hiện mức độ tin cậy của cơ hội trong dự báo mà không thay thế giai đoạn hoặc bằng chứng chốt bán.", en: "Expresses opportunity confidence in the forecast without replacing stage or closing evidence." },
    example: { vi: "Pipeline cho cơ hội sớm; Best Case khi có khả năng nhưng còn điều kiện; Commit khi đội Sales cam kết cao.", en: "Pipeline for early opportunities, Best Case when likely but conditional, and Commit when Sales has high confidence." },
    impact: { vi: "Ảnh hưởng dự báo quản lý; mọi thay đổi cùng ngày đóng hoặc xác suất được giữ trong lịch sử.", en: "Affects management forecasting; changes alongside close date or probability are retained in history." },
    requiredWhen: { vi: "Bắt buộc từ giai đoạn Đề xuất hoặc Đàm phán và nên được rà soát khi bằng chứng thay đổi.", en: "Required from Proposal or Negotiation and should be reviewed whenever evidence changes." },
    keywords: { vi: "forecast commit best case pipeline dự báo", en: "forecast commit best case pipeline" },
  },

];
