import type {
  PilotActor,
  PilotJourneyStep,
  PilotMetricDefinition,
  PilotRecord,
} from "./userExperienceBaseline.types";

export const PILOT_ACTORS: readonly PilotActor[] = [
  { id: "actor-sales", memberId: "pilot-member-sales", role: "SALES" },
  { id: "actor-manager", memberId: "pilot-member-manager", role: "SALES_MANAGER" },
  { id: "actor-finance", memberId: "pilot-member-finance", role: "FINANCE" },
  { id: "actor-operations", memberId: "pilot-member-operations", role: "OPERATIONS" },
  { id: "actor-admin", memberId: "pilot-member-admin", role: "WORKSPACE_ADMIN" },
  { id: "actor-product", memberId: "pilot-member-product", role: "PRODUCT_ENGINEERING" },
] as const;

export const PILOT_LEAD_INGRESS_CASES = [
  { id: "ingress-manual", channel: "manual", dedupeKey: "pilot-contact@example.invalid", expectedResult: "CREATE" },
  { id: "ingress-import", channel: "import", dedupeKey: "+84000000001", expectedResult: "CREATE" },
  { id: "ingress-webhook", channel: "webhook", dedupeKey: "pilot-contact@example.invalid", expectedResult: "MATCH_EXISTING" },
] as const;

const relationshipId = "pilot-relationship-001";
const salesOwnerId = "pilot-member-sales";

export const PILOT_RECORDS: readonly PilotRecord[] = [
  {
    id: "pilot-lead-001",
    kind: "lead",
    ownerId: salesOwnerId,
    customerRelationshipId: relationshipId,
    links: { convertedContactId: "pilot-contact-001", convertedOrganizationId: "pilot-organization-001" },
  },
  {
    id: "pilot-contact-001",
    kind: "contact",
    ownerId: salesOwnerId,
    customerRelationshipId: relationshipId,
    links: { organizationId: "pilot-organization-001", convertedFromLeadId: "pilot-lead-001" },
  },
  {
    id: "pilot-organization-001",
    kind: "organization",
    ownerId: salesOwnerId,
    customerRelationshipId: relationshipId,
    links: { primaryContactId: "pilot-contact-001", convertedFromLeadId: "pilot-lead-001" },
  },
  {
    id: "pilot-deal-001",
    kind: "deal",
    ownerId: salesOwnerId,
    customerRelationshipId: relationshipId,
    links: { contactId: "pilot-contact-001", organizationId: "pilot-organization-001", quoteId: "pilot-quote-001" },
  },
  {
    id: "pilot-quote-001",
    kind: "quote",
    ownerId: salesOwnerId,
    customerRelationshipId: relationshipId,
    links: { dealId: "pilot-deal-001", orderId: "pilot-order-001" },
  },
  {
    id: "pilot-order-001",
    kind: "order",
    ownerId: salesOwnerId,
    customerRelationshipId: relationshipId,
    links: { quoteId: "pilot-quote-001", paymentId: "pilot-payment-001", shippingId: "pilot-shipping-001" },
  },
  {
    id: "pilot-payment-001",
    kind: "payment",
    ownerId: "pilot-member-finance",
    customerRelationshipId: relationshipId,
    links: { orderId: "pilot-order-001", returnId: "pilot-return-001" },
  },
  {
    id: "pilot-shipping-001",
    kind: "shipping",
    ownerId: "pilot-member-operations",
    customerRelationshipId: relationshipId,
    links: { orderId: "pilot-order-001", returnId: "pilot-return-001" },
  },
  {
    id: "pilot-return-001",
    kind: "return",
    ownerId: "pilot-member-operations",
    customerRelationshipId: relationshipId,
    links: { orderId: "pilot-order-001", paymentId: "pilot-payment-001", shippingId: "pilot-shipping-001" },
  },
  {
    id: "pilot-support-001",
    kind: "support",
    ownerId: "pilot-member-operations",
    customerRelationshipId: relationshipId,
    links: { orderId: "pilot-order-001", taskId: "pilot-task-001" },
  },
  {
    id: "pilot-task-001",
    kind: "task",
    ownerId: "pilot-member-operations",
    customerRelationshipId: relationshipId,
    links: { supportId: "pilot-support-001" },
  },
] as const;

export const PILOT_JOURNEY_STEPS: readonly PilotJourneyStep[] = [
  {
    id: "pilot-step-lead-ingress",
    sequence: 1,
    actorRole: "SALES",
    routeKey: "LEADS",
    recordIds: ["pilot-lead-001"],
    expectedEvidence: ["Manual, import, and webhook cases are characterized", "Duplicate matching result is recorded"],
  },
  {
    id: "pilot-step-owner-sla",
    sequence: 2,
    actorRole: "SALES_MANAGER",
    routeKey: "LEAD_DETAIL",
    recordIds: ["pilot-lead-001"],
    expectedEvidence: ["Owner equals authenticated Sales member", "Visible scope and first-response SLA are recorded"],
  },
  {
    id: "pilot-step-conversion",
    sequence: 3,
    actorRole: "SALES",
    routeKey: "LEAD_QUALIFY",
    recordIds: ["pilot-lead-001", "pilot-contact-001", "pilot-organization-001"],
    expectedEvidence: ["Lead history remains linked", "Contact and Organization share one relationship identity"],
  },
  {
    id: "pilot-step-deal",
    sequence: 4,
    actorRole: "SALES",
    routeKey: "DEAL_DETAIL",
    recordIds: ["pilot-deal-001"],
    expectedEvidence: ["Pipeline stage, next step, expected close date, and owner are recorded"],
  },
  {
    id: "pilot-step-quote",
    sequence: 5,
    actorRole: "SALES_MANAGER",
    routeKey: "QUOTE_DETAIL",
    recordIds: ["pilot-quote-001"],
    expectedEvidence: ["Discount and approval evidence are retained", "Customer identity matches the Deal"],
  },
  {
    id: "pilot-step-order",
    sequence: 6,
    actorRole: "SALES",
    routeKey: "ORDER_DETAIL",
    recordIds: ["pilot-order-001"],
    expectedEvidence: ["Order originates from the accepted Quote", "Customer and commercial totals remain consistent"],
  },
  {
    id: "pilot-step-payment",
    sequence: 7,
    actorRole: "FINANCE",
    routeKey: "PAYMENT_DETAIL",
    recordIds: ["pilot-payment-001"],
    expectedEvidence: ["Payment schedule, transaction, and reconciliation evidence are recorded"],
  },
  {
    id: "pilot-step-shipping",
    sequence: 8,
    actorRole: "OPERATIONS",
    routeKey: "SHIPPING_DETAIL",
    recordIds: ["pilot-shipping-001"],
    expectedEvidence: ["Provider lifecycle and delivered evidence are recorded"],
  },
  {
    id: "pilot-step-return",
    sequence: 9,
    actorRole: "OPERATIONS",
    routeKey: "RETURN_DETAIL",
    recordIds: ["pilot-return-001"],
    expectedEvidence: ["Receipt is confirmed", "Refund or replacement evidence links to Payment or Shipping"],
  },
  {
    id: "pilot-step-support-and-reconciliation",
    sequence: 10,
    actorRole: "PRODUCT_ENGINEERING",
    routeKey: "SUPPORT_CASE_DETAIL",
    recordIds: ["pilot-support-001", "pilot-task-001"],
    expectedEvidence: ["Support work is assigned", "Customer View, modules, Dashboard, and Report totals reconcile"],
  },
] as const;

export const PILOT_METRICS: readonly PilotMetricDefinition[] = [
  {
    id: "lead-create-duration",
    label: "Median Lead creation duration",
    unit: "duration",
    sourceRecordKinds: ["lead"],
    dimensions: ["ingressChannel", "actorRole", "deviceClass"],
    evidenceOwner: "Sales operations",
  },
  {
    id: "deal-create-duration",
    label: "Median Deal creation duration",
    unit: "duration",
    sourceRecordKinds: ["deal"],
    dimensions: ["actorRole", "source", "deviceClass"],
    evidenceOwner: "Sales operations",
  },
  {
    id: "form-abandonment-rate",
    label: "Creation-form abandonment rate",
    unit: "rate",
    sourceRecordKinds: ["lead", "contact", "deal"],
    dimensions: ["recordKind", "actorRole", "deviceClass"],
    evidenceOwner: "Product analytics",
  },
  {
    id: "missing-owner-next-step-rate",
    label: "Records missing owner or next step",
    unit: "rate",
    sourceRecordKinds: ["lead", "deal"],
    dimensions: ["recordKind", "ownerTeam", "source"],
    evidenceOwner: "Sales management",
  },
  {
    id: "lead-sla-rate",
    label: "Lead first-response SLA rate",
    unit: "rate",
    sourceRecordKinds: ["lead"],
    dimensions: ["owner", "team", "source"],
    evidenceOwner: "Sales management",
  },
  {
    id: "outside-crm-action-count",
    label: "Actions completed outside CRM",
    unit: "count",
    sourceRecordKinds: ["lead", "deal", "support", "task"],
    dimensions: ["actorRole", "activityType"],
    evidenceOwner: "Pilot coordinator",
  },
  {
    id: "dashboard-report-reconciliation-delta",
    label: "Dashboard, report, and manual reconciliation delta",
    unit: "currency-delta",
    sourceRecordKinds: ["deal", "quote", "order", "payment"],
    dimensions: ["metricId", "period", "currency"],
    evidenceOwner: "Finance and product analytics",
  },
  {
    id: "order-operations-quality-rate",
    label: "Delivery, COD, return, and refund quality rate",
    unit: "rate",
    sourceRecordKinds: ["payment", "shipping", "return"],
    dimensions: ["provider", "resolutionType", "period"],
    evidenceOwner: "Finance and operations",
  },
] as const;
